### ISSUE TITLE
Add support for RC2/3DES/PBES protected PKCS12 files

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/PKI.js#101]
Windows only supports weak crypto for PKCS#12 files - http://unmitigatedrisk.com/?p=543

If a web application wants to support interoperating with Windows they will need to be able to create/consume files based on these weak cipher suites.

To do this we would need:
- [RC2](https://github.com/tomyun/crypto-js/blob/xeit/src/rc2.js)
- [3DES](https://github.com/tomyun/crypto-js/blob/xeit/src/tripledes.js  )
- [PBES](https://github.com/digitalbazaar/forge/blob/94cd061f005dc2746ea9e4dddf6b23ad9c0044f9/lib/pbe.js#L642)

This is the largest part of the work. Support for these algorithms could be done in webcrypto-liner, or embedded custom [CryptoEngine](https://github.com/PeculiarVentures/PKI.js/blob/b3bb3f9516d1c094f75dd08f6e8906b3ca477aad/src/CryptoEngine.js) that contained these algorithms:

There is value to both approaches, adding a custom CryptoEngine would result in a solution that would interoperate but would not encourage the use of the weak algorithms by others which I think would happen if we added it to webcrypto-liner.

The narrowest solution would probably be the CryptoEngine.

**Comment by YuryStrozhevsky** [comment]
Done in [this example](https://github.com/PeculiarVentures/PKI.js/tree/master/examples/NodePKCS12Example).
