### ISSUE TITLE
Error while executing an example with pkcs12

### ISSUE THREAD

**Issue by vovkvlad** [PeculiarVentures/PKI.js#103]
Hi! 
I am trying to execute example with pkcs12, and getting error:
`Uncaught (in promise) DOMException: KDF keys must set extractable=false`

It throws me an error at this promise:
```
sequence = sequence.then(
        function(result)
        {
            return pkcs12.parsedValue.authenticatedSafe.makeInternalValues({
                safeContents: [
                    {
                        // Empty parameters since we have "No Privacy" protection level for SafeContents
                    }
                ]
            });
        }
    );
```

I am using version 1.3.32 as written in package.json

Will be really gratefully for any kind of help, thanks!
If any other details needed - let me know

**Comment by YuryStrozhevsky** [comment]
We are not supporting v1 anymore. Please move to latest v2.
