### ISSUE TITLE
Wrong license

### ISSUE THREAD

**Issue by jamesiri** [PeculiarVentures/PKI.js#111]
You package.json lists the package licensed under MIT but you then provide the BSD-3 license as well as use the BDS-3 license in your readme. Would like to see one selected or officially support a dual license.

**Comment by rmhrisk** [comment]
BSD-3 is the license, package.json will be updated.

**Comment by rmhrisk** [comment]
See : https://github.com/PeculiarVentures/PKI.js/pull/112
