### ISSUE TITLE
Error on CertificateChainValidationEngine.verify

### ISSUE THREAD

**Issue by microshine** [PeculiarVentures/PKI.js#113]
`CertificateChainValidationEngine.verify` from `npm` throw error in nodejs.

```
ReferenceError: regeneratorRuntime is not defined
    at CertificateChainValidationEngine.sort (C:\github\pkijs_test\node_modules\pkijs\build\CertificateChainValidationEngine.js:88:89
)
    at CertificateChainValidationEngine.verify (C:\github\pkijs_test\node_modules\pkijs\build\CertificateChainValidationEngine.js:117
6:20)
```

I created simple project which reproduce curret error https://github.com/microshine/pkijs_test/tree/master

**Comment by rmhrisk** [comment]
Based on: https://stackoverflow.com/questions/33527653/babel-6-regeneratorruntime-is-not-defined-with-async-await

It seems like this is because your runtime environment may not have support for async-await and PKIjs doesn't include:
`require('babel-polyfill');` 

I think this manifests as two issues then:
1. If you upgrade to Node 7 or later it should work without this polyfill.
2. PKIjs should probably list the babel-polyfill as a dependency so other users can use it without upgrading to a non-stable node build.

@microshine can you try Node 7 or later?

**Comment by rmhrisk** [comment]
As I think about this, it seems if we do not include the babel-polyfill in package.json and in index.js we wont work for any ES5 users.

@YuryStrozhevsky can you confirm my understanding is correct?

**Comment by rmhrisk** [comment]
@YuryStrozhevsky ping

**Comment by orgoldfus** [comment]
I get the same error and I'm using Node 8.4.0
Any ideas?

**Comment by rmhrisk** [comment]
@YuryStrozhevsky ping

**Comment by YuryStrozhevsky** [comment]
In fact PKI.js itself does not need to have "babel-polyfill" as a dependency. It is necessary for application to have such package. Of course if application, using PKI.js, requires to use ES5 code. PKI.js is a native ES6 library and ES5 code is an option.

**Comment by rmhrisk** [comment]
@YuryStrozhevsky you may be right, however it seems odd to me that the calling application must know that the ES5 from PKIjs is transpiled with Babel.

I was looking around to see if there is a standard answer for this and if there is reasonable way to include the babel dependency in the ES5 transpilation and I found this : https://github.com/sindresorhus/ama/issues/446 

I would be interested in what you though about this topic.

**Comment by YuryStrozhevsky** [comment]
@rmhrisk If I understood you correctly you are suggesting to include babel-polyfill code in ES5 code we build in PKIjs code. If yes I need to say that if we do this it would lead to a much more code. But it is not a worst thing: if we do this and in end-user application would be also using babel-polyfill user would have error like “two instances of babel-polyfilll are running at the same time” (I hope you remember the error, we already had in in Hancock for a few times).

**Comment by rmhrisk** [comment]
@YuryStrozhevsky I am not sure what the right solution is. It seems broken to me someone can't just add pkijs to their project and start using it even though we ship an ES5 and ES6 version of PKIjs.

For all other npm packages I have ever used adding the package was enough to be able to use it.

**Comment by YuryStrozhevsky** [comment]
Closed as seems all came to conclusion there is no other choice here.
