### ISSUE TITLE
Wrong chain on CertificateChainValidationEngine.sort

### ISSUE THREAD

**Issue by microshine** [PeculiarVentures/PKI.js#114]
__Incoming data:__
Certificates: A, B, C
Where A is Root self-signed certificate for B and C

__Task:__
I need to build chain for B certificate

> NOTE: CertificateChainValidationEngine builds chain for the last certificate in `certs` param ([source](https://github.com/PeculiarVentures/PKI.js/blob/master/src/CertificateChainValidationEngine.js#L594))

__Code:__
```js
const allCerts = [A, B, C];

const trustedCerts = [A];
const certs = allCerts.map(item => item); // copy allCerts to certs

// Add B to the end of list
certs.push(B); // certs: [A, B, C, B]

const chainBuilder = new CertificateChainValidationEngine({
  trustedCert,
  certs,
});

const chain = await chainBuilder.sort();

// sort() - removes duplicates
// localCerts: [A, B, C]

console.log(chain); // [C, A]
```

**Comment by YuryStrozhevsky** [comment]
@microshine Do not mix "trusted certs" and "intermediate certs". And finally take a looks at [example](https://github.com/PeculiarVentures/PKI.js/blob/master/examples/NISTPKITS/es6.js).
