### ISSUE TITLE
client certificate and auto certificate pickup from browser keystore for TLS connection via Jquery

### ISSUE THREAD

**Issue by sanaullah82** [PeculiarVentures/PKI.js#115]
I have configured my own CA so called a self-signed CA. we are generating the server and client certificate signed by that  CA. all the server connection required a valid client certificate.I have tested the key generation and certificate request, and successfully get back the signed certificate using pkijs.

in the 2nd part i have to connect to the webservice using the client certificate over ssl using jquery how can i achieve this ? where should i store the keys in the browser and jquery connection could auto select the certificate and connect to the webservice ? 
do you think PKIjs can help me on this? as the CA is selfsigned so all the browser also throwing the warnings for self-signed certificate as well ?

**Comment by YuryStrozhevsky** [comment]
We are not consulting regarding PKI applications. All your questions are out of scope for PKI.js

**Comment by rmhrisk** [comment]
As you point out browsers will not trust your certificate,  you can define your own protocol that uses certificates and run that over HTTP,  the client and/or implementation of that protocol could use PKIjs.

 That said this is likely not what you want,  without more for information I couldn't tell you anything useful.

 In general, Yury is right, it's not possible for us to provide security consulting via GitHub.

**Comment by sanaullah82** [comment]
I am not asking for security consulting. i thought may be PKI.js has some support for key storage in browser and auto certificate pickup on a webservice call.

Anyways Thanks.

**Comment by sanaullah82** [comment]
got it!
