### ISSUE TITLE
PDF signature validation example is not working correctly

### ISSUE THREAD

**Issue by alex-mironov** [PeculiarVentures/PKI.js#116]
https://pkijs.org/examples/PDFexample.html

I'm trying to use this example to validate if a file is signed with the proper certificate. I upload some certificate and signed pdf. No matter which certificate was used for signing pdf, the result of example is always "Pdf successfully verified!". Even when no certificate was provided.

**Comment by YuryStrozhevsky** [comment]
@alex-mironov In the example we have "Select CA bundle file" field. Do you understand what "CA bundle" means? This is a file having all root certificates. If, for example, you have signed PDF with self-signed certificate then in **all** cases (except corrupted signature, of course) the "Pdf successfully verified!". So, please check you have a correct input data for the example.

**Comment by alex-mironov** [comment]
@YuryStrozhevsky you're correct, my bad. I thought it would be possible to check if the file was updated after its signing.

e.g. user signs pdf in adobe reader and then on server having public key we validate if file was really signed by that user https://helpx.adobe.com/acrobat/using/digital-ids.html

**Comment by alex-mironov** [comment]
sorry if the question is stupid, just wanted to know if this something we can achieve with PKI?

**Comment by YuryStrozhevsky** [comment]
@alex-mironov "...and then on server having public key we validate if file was really signed by that user" - in fact in order to do this you need a user certificate signed by trusted CA and that is all. Details of such application are out of scope for PKI.js, but yes, it could be achieved with PKI.
