### ISSUE TITLE
PDF example incorrectly verifies pdf signed by another user 

### ISSUE THREAD

**Issue by sadam36** [PeculiarVentures/PKI.js#117]
I am trying to verify pdf signature using provided "How to verify signature in PDF file" example (ran locally and on https://pkijs.org/examples/PDFexample.html).

I generated two different identities (John Doe and Jane Doe) in Adobe Reader and used them to sign two different PDFs (johndoe_signed.pdf and janedoe_signed.pdf - attached).

[janedoe_signed.pdf](https://github.com/PeculiarVentures/PKI.js/files/1182995/janedoe_signed.pdf)
[johndoe_signed.pdf](https://github.com/PeculiarVentures/PKI.js/files/1182996/johndoe_signed.pdf)

Later, I exported the IDs to .cer format and extracted public keys from them:
```
openssl x509 -in CertExchangeJaneDoe.cer -out JaneDoe.pem -outform PEM -inform der
openssl x509 -in CertExchangeJohnDoe.cer -out JohnDoe.pem -outform PEM -inform der
``` 

(Unfortunately I can't upload them to github, so I attached them here: https://pastebin.com/dXdqa4vM and https://pastebin.com/XLzd5Vvk).

Now, when I provide JohnDoe.pem and johndoe_signed.pdf to the example, I get "PDF successfully verified!" alert. The same happens for JaneDoe.pem and janedoe_signed.pdf. 
The problem appears when I provide a public key of one user and pdf signed by another user (e.g. JohnDoe.pem and janedoe_signed.pdf) - I still get "PDF successfully verified!", while I would expect totally different result.

Did I do something incorrectly, or misunderstood the example?

**Comment by YuryStrozhevsky** [comment]
@sadam36 Bet you have the same misunderstanding as in [this issue](https://github.com/PeculiarVentures/PKI.js/issues/116). Please check it.

**Comment by sadam36** [comment]
@YuryStrozhevsky you are right. Apparently I was searching only in the open tickets and missed that issue. Thank you
