### ISSUE TITLE
Problem with encrypt/decrypt ECDSA based certificates

### ISSUE THREAD

**Issue by ip6li** [PeculiarVentures/PKI.js#118]
When encrypting/decrypting is done with RSA certificates, everything runs well. If ECDSA certificates are used, encryption ends up with an exception.

### Steps to reproduce
git clone https://github.com/ip6li/x509sessions
cd x509sessions/x509
npm install
firefox web/test.html

Open Firefox debugger. After Reload you see an error in debugger. Comment cftestECDSA() and uncomment cftestRSA() - now it works, so I consider my code is not completely wrong. ECDSA certificate seems also to be ok, OpenSSL is able to encrypt/decrypt.

Also reproducable on test server at https://test2.cdn6.de/test.html where both methods are enabled, RSA succeeds, ECDSA fails.

*npm install* downloads PKI.js from Github and creates a bundle.js in web/js. Do not care about Java (server) stuff and other files. bundle.js and test.html are working like PKI.js examples.

### code snippet
```
    //*********************************************************************************
    function envelopedEncrypt(pkcs) {
        return Promise.resolve().then(() => {
            const encodedCertificate = pkcs.certificate;
            const clearEncodedCertificate = encodedCertificate.replace(certificateDelimiter, "");
            pkcs.certificateBuffer = stringToArrayBuffer(fromBase64(clearEncodedCertificate));
        }).then(() => envelopedEncryptInternal(pkcs)).then(() => {
                let resultString = "-----BEGIN CMS-----\r\n";
                resultString = `${resultString}${formatPEM(toBase64(arrayBufferToString(pkcs.cmsEnvelopedBuffer)))}`;
                resultString = `${resultString}\r\n-----END CMS-----\r\n`;
                return resultString;
            },
            error => Promise.reject(`ERROR DURING ENCRYPTION PROCESS: ${error}`)
        );
    }

    function envelopedDecryptInternal(pkcs) {
        //region Decode input certificate
        let asn1 = fromBER(pkcs.certificateBuffer);
        const certSimpl = new Certificate({schema: asn1.result});
        //endregion

        //region Decode CMS Enveloped content
        asn1 = fromBER(pkcs.cmsEnvelopedBuffer);
        const cmsContentSimpl = new ContentInfo({schema: asn1.result});
        const cmsEnvelopedSimp = new EnvelopedData({schema: cmsContentSimpl.content});
        //endregion

        return cmsEnvelopedSimp.decrypt(0,
            {
                recipientCertificate: certSimpl,
                recipientPrivateKey: pkcs.privateKeyBuffer
            }).then(
            result => result,
            error => {
                console.log (`Something bad happened while decrypting: ${error}`);
                Promise.reject(`E002: ${error}`);
            }
        );
    }
```

They are extracted from PKI.js examples, global vars were replaced by local ones.

Any hints?

**Comment by YuryStrozhevsky** [comment]
@ip6li Have you checked [this example](https://pkijs.org/examples/CMSEnvelopedExample.html)? I just made a simple check: ECDSA works well there.

**Comment by ip6li** [comment]
I checked examples, most of my PKI.js interfaces are derived from that examples.

My code works in an isolated environment, too - that means a bundle.js which does nothing else than encrypt/decrypt like your example. It makes a difference if I do the *rollem* (seems to be something like *make*) as a standalone module or as a big module. The standalone module works, the big module not.

Are there any global var names which should i **not** use with PKI.js?

**Comment by YuryStrozhevsky** [comment]
You had error. Which one?

**Comment by ip6li** [comment]
It was a nasty dependency problem. Import statement
```
import * as asn1js from "asn1js";
import {arrayBufferToString, toBase64, stringToArrayBuffer, fromBase64} from "pvutils";
```
caused that ECDSA problem. Modifying to 
```
import * as asn1js from "../PKI.js/node_modules/asn1js";
import {arrayBufferToString, toBase64, stringToArrayBuffer, fromBase64} from "../PKI.js/node_modules/pvutils";
```
Obviously there are other NPM modules named also asn1js and pvutils.
