### ISSUE TITLE
Cannot load certificate PEM bundle

### ISSUE THREAD

**Issue by markb-trustifi** [PeculiarVentures/PKI.js#120]
I want to load a PEM bundle: https://www.digistamp.com/pubkeys/dgs_bundle_ca80.pem 
to an array of PKI certificates with this code:
````JS
LoadCABundle(pembundle) {
        this.trustedCertificates = [];

        let lines = pembundle.split('\n'), cert = [];
        for(let line of lines) {
            if(line.indexOf('BEGIN CERTIFICATE') > 0) {
                cert = [];
            }
            else if(line.indexOf('END CERTIFICATE') > 0) {
                let certstr = cert.join('').split('\r').join('');

                try
                {
                    let asn1obj = asn1.fromBER(new Uint8Array(new Buffer(certstr, 'base64')).buffer);
                    let certObj = new pki.Certificate({ schema: asn1obj.result });
                    this.trustedCertificates.push(certObj);
                }
                catch(ex)
                {
                    logger.error(ex);
                }
            }
            else {
                cert.push(line);
            }
        }
    }
````

And receive these errors:
Error: Object's schema was not verified against input data for CERT
Error: Object's schema was not verified against input data for CERT
Error: Object's schema was not verified against input data for CERT
Error: Object's schema was not verified against input data for CERT
Error: Object's schema was not verified against input data for CERT
Error: Incorrect curve OID: 1.3.36.3.3.2.8.1.1.13
Error: Incorrect curve OID: 1.3.36.3.3.2.8.1.1.13
Error: Incorrect curve OID: 1.3.36.3.3.2.8.1.1.13
Error: Incorrect curve OID: 1.3.36.3.3.2.8.1.1.13
Error: Incorrect curve OID: 1.3.36.3.3.2.8.1.1.13
Error: Incorrect curve OID: 1.3.36.3.3.2.8.1.1.13
Info: Loaded 4 trusted certificates

Some of the certificates are loaded and some are not.

**Comment by rmhrisk** [comment]
Please attach the certificates

**Comment by rmhrisk** [comment]
That OID is a brain pool OID, we won't be able to verify it because WebCrypto doesn't support Brainpool.

To verify it we would need a polyfill like webcrypto-liner extended to support this curve and then we could extend PKIjs to be able to support them.

I would expect you to be able to decode these either way though, please provide the certificates so we can see what is wrong with them or PKIjs.

**Comment by rmhrisk** [comment]
Nevertheless mind I see guy provided a link. Maybe yury can take a quick look.

**Comment by YuryStrozhevsky** [comment]
@markb-trustifi In fact problems were because of unknown named curve OID. But in fact PKI.js must parse such certificates anyway. Now I prevent PKI.js from crushing during parsing of such certificates. So, now you will have parsed certificates, but without some internal info about public keys.

**Comment by markb-trustifi** [comment]
Much thanks!
Now there left 5 certs that still fail to load and I cannot verify timestamp without them:
Error: Object's schema was not verified against input data for CERT
Error: Object's schema was not verified against input data for CERT
Error: Object's schema was not verified against input data for CERT
Error: Object's schema was not verified against input data for CERT
Error: Object's schema was not verified against input data for CERT
Info: Loaded 10 trusted certificates

**Comment by YuryStrozhevsky** [comment]
@markb-trustifi I manually extracted and have parsed all 15 certificates from the bundle: with latest PKI.js code every certificate was parsed just fine. So, probably you have a problem in your parsing code.

**Comment by markb-trustifi** [comment]
Thanks a lot for your help.
Now the certificate load and verification are working (see updated code sample).
I still have these errors:
(node:12197) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Unsupported named curve algorithm: 1.3.36.3.3.2.8.1.1.13
(node:12197) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): Unsupported named curve algorithm: 1.3.36.3.3.2.8.1.1.13

In checkChain verification (checkChain=false verifies correct):
````JS
let asn1obj = asn1.fromBER(new Buffer(tspResponseBuffer).buffer);
let tspRespSimpl = new pki.TimeStampResp({ schema: asn1obj.result });
let signedSimpl = new pki.SignedData({ schema: tspRespSimpl.timeStampToken.content });
signedSimpl
  .verify({ signer: 0, data: origBuffer, trustedCerts: this.trustedCertificates, checkChain: true, extendedMode:true })
  .then(...)
````

**Comment by YuryStrozhevsky** [comment]
@markb-trustifi It is clearly because "Unsupported named curve algorithm: 1.3.36.3.3.2.8.1.1.13" :) See previous comments from @rmhrisk about it. I see nothing else we could help here.

**Comment by rmhrisk** [comment]
@markb-trustifi the brain curves are not supported by WebCrypto, as an aside WebPKI CAs are not allowed to use these curves either. If you need to validate these you will need to use a webcrypto-polyfill that adds support for these curves.

https://github.com/indutny/elliptic has support for these algorithms.

You could do a PR to https://github.com/PeculiarVentures/webcrypto-liner that would enable code to use WebCrypto interfaces to do the verification.

This with a small PR to PKIjs would allow verification of signatures made with these curves.

Both of the above changes would be small.

I would have to think about if we would want these changes back though (e.g. would we accept the PRs or would you need to do this as a fork).

In general with webcrypto-liner it already conditionally loads dependencies and elliptic is already an optional dependency and the change to support these algorithms should be tiny code base wise. The main thing is there is no standard names for them in WebCrypto so it would be a bit of a hack. I think to accept the PR, in this case, we would want to see a draft `experimental` document capturing the names and reason behind them so W3C could potentially consider their addition.
