### ISSUE TITLE
Undefined is not iterable

### ISSUE THREAD

**Issue by microshine** [PeculiarVentures/PKI.js#121]
![image](https://user-images.githubusercontent.com/7333669/29652397-ed6aa6f0-88ad-11e7-8c8f-f46a11e90eb0.png)

It throws exception if certificate doesn't extensions ([source](https://github.com/PeculiarVentures/PKI.js/blob/master/src/SignedData.js#L617))

**Comment by YuryStrozhevsky** [comment]
Fixed.
