### ISSUE TITLE
Problem decrypt p12

### ISSUE THREAD

**Issue by pavel-kubik** [PeculiarVentures/PKI.js#123]
Hi,

we have an issue during decryption of P12. It shows an error "Incorrect OID for HMAC hash algorithm". It comes from https://github.com/PeculiarVentures/PKI.js/blob/eb777213fd1d6bd547e5626c219be89f363fdab6/src/EncryptedData.js#L445. Code is following:
```
function parsePKCS12Internal(buffer, password) {
    const passwordConverted = stringToArrayBuffer(password);
    const asn1 = asn1js.fromBER(buffer);
    const pkcs12 = new PFX({ schema: asn1.result });

    return new Promise(function(resolve, reject) {
        // Create an empty promise, could have used Promise.resolve() instead...
        resolve();
    }).then(function() {
        return pkcs12.parseInternalValues({
            password: passwordConverted,
            checkIntegrity: false // Do not check an integrity since OpenSSL produce HMAC using old PBKDF1 function
        });
    }).then(function() {
        let safeContentsArray = [];
        for (let authSafeIdx in pkcs12.parsedValue.authenticatedSafe.safeContents) {
            let authSafe = pkcs12.parsedValue.authenticatedSafe.safeContents[authSafeIdx];
            switch (authSafe.contentType) {
                case ENCRYPTED_DATA:
                    safeContentsArray.push({ password: passwordConverted });
                    break;
                default:
                    safeContentsArray.push({});
            }
        }
        return pkcs12.parsedValue.authenticatedSafe.parseInternalValues({
            safeContents: safeContentsArray
        });
    }).then(function() {
        let sequence = Promise.resolve();
        // decrypt safeBags
        for (let authSafeIdx in pkcs12.parsedValue.authenticatedSafe.parsedValue.safeContents) {
            let authSafe = pkcs12.parsedValue.authenticatedSafe.parsedValue.safeContents[authSafeIdx];
            for (let safeBagIdx in authSafe.value.safeBags) {
                let safeBag = authSafe.value.safeBags[safeBagIdx];
                if (typeof safeBag.bagValue.parsedValue == "undefined") {
                    sequence = sequence.then(function() {
                        return safeBag.bagValue.parseInternalValues({
                            password: passwordConverted
                        });
                    });
                }
            }
        }
        return sequence;
    }).then(function () {
        return pkcs12;
    }).catch(function (error) {
        UTILS.log(typeof error.message != 'undefined' ? error.message : error);
    });
}
```

I debug it and there is empty string in pbkdf2Params.prf.algorithmId (code: https://github.com/PeculiarVentures/PKI.js/blame/eb777213fd1d6bd547e5626c219be89f363fdab6/src/EncryptedData.js#L443)

Empty string comes from constructor of PBKDF2Params. Atribut prf is set by new AlgorithmIdentifier(); because of decrypt (code https://github.com/PeculiarVentures/PKI.js/blob/eb777213fd1d6bd547e5626c219be89f363fdab6/src/AuthenticatedSafe.js#L270) is called just with parameter password.

There is default hmac hash algorithm on line 439. However default hmac hash algorithm is not used when algorithm is set to "". Is it bug in the library or is it some error in our code?

**Comment by rmhrisk** [comment]
Sounds like a bug, @YuryStrozhevsky do you concur? If so we would accept a PR, otherwise we will get to it as quick as we can.

**Comment by YuryStrozhevsky** [comment]
@pavel-kubik I can not process further without initial PCKS#12 data. Also please aware that we do not support any "standard" Windows PKCS#12 bundles, only a specially prepared OpenSSL P12 bundles.

**Comment by jeromewagener** [comment]
@YuryStrozhevsky @rmhrisk 

Thank you for your quick relies. 

We are wondering whether we could send you an example P12 bundle by mail? If yes, would ```yury@strozhevsky.com``` be ok?

To give you some more context: We are currently converting "standard" Windows PKCS#12 bundles using Bouncy Castle to PKI.JS compatible PKCS#12 bundles.

Right now everything works perfect except that we have a "workaround" in the PKI.JS codebase as mentioned by @pavel-kubik in order to initialize the HMAC algorithm.

**Comment by YuryStrozhevsky** [comment]
@jeromewagener Yes, the e-mail address is right.

**Comment by jeromewagener** [comment]
@YuryStrozhevsky Thanks! The email has been send out.

**Comment by YuryStrozhevsky** [comment]
@pavel-kubik @jeromewagener Fixed in latest changes for PKI.js (was a problem with default value initialization for "PBKDF2Params" class).

**Comment by jeromewagener** [comment]
@YuryStrozhevsky I have just tested the latest PKI.JS version (which includes your changes regarding this issue) and it now works flawlessly without our previous "workaround"

Thanks a lot for your help and responsiveness.  :+1: 

This ticket can be closed from our side.

Kind regards,
Jérôme

**Comment by rmhrisk** [comment]
@jeromewagener if you can share we love hearing what people are doing with PKIjs.

**Comment by jeromewagener** [comment]
@rmhrisk We are still in a rather early phase. But we will send you a mail with some details. Thanks again.
