### ISSUE TITLE
Cannot verify timestamp on Heroku after updating pkijs to new version

### ISSUE THREAD

**Issue by markb-trustifi** [PeculiarVentures/PKI.js#125]
I have the following code. It works well in my local env but fails to verify timestamp on Heroku:

```JS
const WebCrypto = require('node-webcrypto-ossl');
const pki = require('pkijs');
require('babel-polyfill');

let webcrypto = new WebCrypto();
let subtle = new pki.CryptoEngine({ name: '', crypto: webcrypto, subtle: webcrypto.subtle });
pki.setEngine('ossl', webcrypto, subtle);

let asn1obj = asn1.fromBER(new Uint8Array(tspResponseBuffer).buffer);
let tspRespSimpl = new pki.TimeStampResp({ schema: asn1obj.result });
tspRespSimpl.verify({ signer: 0, data: origBuffer, trustedCerts: trustedCerts}).then(...);
```
I receive an error:
TypeError: Cannot read property 'apply' of undefined 
at CryptoEngine.digest (/app/node_modules/pkijs/build/CryptoEngine.js:752:42) 
at /app/node_modules/pkijs/build/TSTInfo.js:286:19 
at process._tickDomainCallback (internal/process/next_tick.js:135:7) :

### versions:
"babel-polyfill": "^6.26.0"
"pkijs": "^2.1.3"
"asn1js": "^2.0.15"
"node-webcrypto-ossl": "^1.0.31"

### node:
"node": "6.11.1"

**Comment by YuryStrozhevsky** [comment]
@markb-trustifi The way how to set crypto engine in Node envy was changed. You could check “roller.config.js” in any example’s folder for correct why for setting crypto engine.

**Comment by markb-trustifi** [comment]
Thanks for a tip.
I updated the previous comment with correct code. Now everything is working.
