### ISSUE TITLE
How to parse internal values of a timestamp response

### ISSUE THREAD

**Issue by badis** [PeculiarVentures/PKI.js#128]
I have used openssl commands in this webpage: https://www.freetsa.org/index_en.php to generate timestamp files (tsr).
I couldn't find any javascript solution to get internal values on the timestamp response.
Does this library to able to do it. And it would much better if it's able to do it in node.js as I have node.js script wrapping openssl commands.

**Comment by rmhrisk** [comment]
See : https://pkijs.org/examples/TSP_req_complex.example.html and https://pkijs.org/examples/TSP_resp_complex_example.html

**Comment by YuryStrozhevsky** [comment]
@badis Here is [the source code](https://github.com/PeculiarVentures/PKI.js/tree/master/examples/TSPResponseComplexExample) for "TSP Responce" example.
