### ISSUE TITLE
Bable (modules) as a dependency instead of devDependency

### ISSUE THREAD

**Issue by ksachdeva** [PeculiarVentures/PKI.js#130]
Hi @YuryStrozhevsky,

Excellent work with library.

Wrote a simple nodejs app and noticed that lot of babel modules were pulled in. Then I saw that in your package.json they are included as dependencies. I then realized that you are converting from es6 to es5 at post install and hence you put them in dependencies instead of devDependencies.

Normally you should be able to do this (i.e. the conversion) just at the publish time using `npm prepublish`. This way the user of your excellent library will not incur the cost of downloading all the babel modules (47 top level modules and have not counted how many of their dependencies .. IMHO the total number of npm modules downloaded that are used just for babel is quite high ). 

Thanks again for the wonderful work.

Regards
Kapil

**Comment by YuryStrozhevsky** [comment]
Looks reasonable, I will change the lib style, thanks.

**Comment by ksachdeva** [comment]
Hi @YuryStrozhevsky,

I have submitted the pull requests for this repo and the dependencies as well (asn1js and pvutils). I tested the changes by submitting the new packages (with prefix ks) on npm and then fetching them on my sample project.

Regards
Kapil
