### ISSUE TITLE
AttributeCertificateV1 is not exposed/exported via index.js

### ISSUE THREAD

**Issue by ksachdeva** [PeculiarVentures/PKI.js#131]
Hi @YuryStrozhevsky ,

May be it is intentional (may be because of it being work in progress) but just want to point out -

The AttributeCertificateV1 & AttributeCertificateV2 are not being exported in index.js. Your example/test is working because it is directly referencing them however when I imported your module in an app, I could not reference them as they are missing in index.js

Please suggest.

Regards
Kapil

**Comment by YuryStrozhevsky** [comment]
Yes seems I forgot to update index.js with these classes.

**Comment by ksachdeva** [comment]
One way to avoid this type of typo could (especially since you have quite a larger number of classes exposed) be to use index module from the various examples i.e.

instead of 
```
import Certificate from "../../src/Certificate";
import AttributeTypeAndValue from "../../src/AttributeTypeAndValue";
import Extension from "../../src/Extension";
import RSAPublicKey from "../../src/RSAPublicKey";
import CertificateChainValidationEngine from "../../src/CertificateChainValidationEngine";
import CertificateRevocationList from "../../src/CertificateRevocationList";
```

use this

```
import {
	Certificate,
	AttributeTypeAndValue,
	Extension,
	RSAPublicKey,
	CertificateChainValidationEngine,
	CertificateRevocationList
} from "../../src";
````

**Comment by YuryStrozhevsky** [comment]
@ksachdeva In case of ES6 variant of code yes, it could be a solution. But in case of ES5 variant - no, the ES5 code would be not in "src" but in "build" directory.

**Comment by ksachdeva** [comment]
@YuryStrozhevsky the problem for ES5 would be same with existing import style as well since you are importing from sub directories of "src" at present.
