### ISSUE TITLE
Global engine variable creating multiple issues

### ISSUE THREAD

**Issue by ksachdeva** [PeculiarVentures/PKI.js#134]
Hi @YuryStrozhevsky,

There are 2 main issues I am facing because of the global nature of the "engine" variable in common.js

**Issue 1**

Consider 2 projects that depend on pkijs.

The first project is `Lib1` that imports `pkiis` and provides some helper utilities & wrappers. (Will open source it shortly)

The second project is `App1` that imports `Lib1` & `pkijs`. It imports `pkijs` primarily to invoke setEngine().

Because of how nodejs works and global nature of "engine" singleton variable the copy that `Lib1` gets is different (essentially null/undefined) than the one set in `App1`

See this thread for more explanation on the caveats of node resolution.
http://justjs.com/posts/singletons-in-node-js-modules-cannot-be-trusted-or-why-you-can-t-just-do-var-foo-require-baz-init

**Issue 2**

Given the global nature of engine there is no way I can support two CryptoEngine implementations at the same time. For e.g. I have a use case where the same server app would use 2 different crypto engines (node-webcrypto-ossl & node-webcrypto-p11) based on some inputs from the client.

##

Both of the issues are happening because of the global variable usage. 

One way to avoid both of the issues at the same time is to not use the global variable and rather require passing the cryptoengine/subtleCrypto as the argument of the constructor of the classes that need it. 

For backward compatibility (if it is desired) then you can take the approach of "cryptoengine" being passed as an optional parameter. If it is passed then use it else use the global one (i.e. the current mechanism)

Please suggest.

Regards
Kapil

**Comment by YuryStrozhevsky** [comment]
PKIJS will continue using crypto engine as a global variable. If you want to use two engines at the same time you should create your own engine where use any optional parameters you want.

**Comment by ksachdeva** [comment]
Hi @YuryStrozhevsky,

I am not sure if having an implementation of CryptoEngine is going to solve the issues. The fundamental issue is that the global variable causes the issue of being specific to the module that will import pkijs (see the link I provided in about post)

Would appreciate if you could provide a technical reason on why global variable is required and the issue that you see in what I am suggesting as a solution that would keep your library backward compatible as well.

Regards
Kapil

**Comment by YuryStrozhevsky** [comment]
@ksachdeva If you want to use same engine in many applications then initialize engine in App1 and transfer it somehow to App2. In App2 then call setEngine. That is all.

If you want to use "two separate engines" then create a new engine where algorithms from both engines would be combined and then call the engine functions with a specific parameters. That is all.

PKIjs will continue using crypto engine as a global variable. That is all.

**Comment by ksachdeva** [comment]
@YuryStrozhevsky Unfortunately your suggestion of using the new crypto engine will not work. You have a fundamental design problem here that makes the library unsuitable to work in nodejs (server environment with multiple requests being entertained at the same time ) environment. I am not sure what is the benefit and reason for having the global variable (it is almost never a good idea anyways) but I would not belabor on it anymore and would find a different library for our needs. Still thanks for all this work, it is quite indeed a good work overall.

**Comment by YuryStrozhevsky** [comment]
PKIJS already perfectly working in Nodejs environment for many years. And you are not the first person trying to integrate the lib.
