### ISSUE TITLE
using PKI.js does creation of pkcs12 support with 3des encryption as AES based P12 file are not working in widows

### ISSUE THREAD

**Issue by mfurqan777** [PeculiarVentures/PKI.js#138]
I am using PKCS12SimpleExample for chrome and its working fine and I am able to generate the p12 but it doesn't work in windows as its required 3des.
I saw this new Example NodePKCS12Example where there is no documentation, is this have 3des for p12 and its for client side example like PKCS12SimpleExample
does this have 3des support?

I am newbie and may I have wrong understanding of the lib

**Comment by YuryStrozhevsky** [comment]
@mfurqan777 The PKI.js uses (by default) standard WebCrypto API realization. But there is possibility to work with almost any algorithms you want if you would make your own "crypto engine". In the NodePKCS12Example you mentioned we made "Node.js-specific" crypto engine having 3DES support. It is not possible to move the same functionality to browser. So, if you want 3DES in browser then you need to create your own "crypto engine" with 3DES support, use it during PKI.js initialization and then PKI.js would works just fine.
