### ISSUE TITLE
Problem with SignedData verification

### ISSUE THREAD

**Issue by fotisl** [PeculiarVentures/PKI.js#140]
I seem to have a problem with the verification of a `SignedData` structure. My structure has attached data, so the test at SignedData.js#799 is true. However, the `tagClass` is 1 and the `tagNumber` is 16, so data is set to `this.encapContentInfo.eContent.valueBlock.valueHex` at SignedData.js#813. In my case, `this.encapContentInfo.eContent.valueBlock` is of type `LocalConstructedValueBlock` and has no `valueHex`. In order to pass the validation, I need to use `this.encapContentInfo.eContent.valueBlock.valueBeforeDecode`. I believe that changing the assignment at SignedData.js#813 to:
```
if("valueHex" in this.encapContentInfo.eContent.valueBlock)
  data = this.encapContentInfo.eContent.valueBlock.valueHex;
else
  data = this.encapContentInfo.eContent.valueBlock.valueBeforeDecode;
```
would fix the problem. I haven't made a pull request, since I'm not sure if this is the correct patch, or if only `this.encapContentInfo.eContent.valueBlock.valueBeforeDecode` should be used.

**Comment by YuryStrozhevsky** [comment]
@fotisl Why your "eContent" has "tagNumber = 16" which is Sequence? In fact in RFC5662 the EncapsulatedContentInfo type has the schema:
```
   EncapsulatedContentInfo ::= SEQUENCE {
     eContentType ContentType,
     eContent [0] EXPLICIT OCTET STRING OPTIONAL }
```

However, in PKCS#7 (which is old "version" of RFC5662) the same structure has schema like this:
```
   ContentInfo ::= SEQUENCE {
     contentType ContentType,
     content
       [0] EXPLICIT ANY DEFINED BY contentType OPTIONAL }
```

Anyway, how did you get the SignedData and could you provide it here or send me to yury@strozhevsky.com?

**Comment by fotisl** [comment]
Exactly, I have a PKCS#7 SignedData structure. I can email it to you.

**Comment by YuryStrozhevsky** [comment]
@fotisl I made a fix and tested it locally with your data - all works fine. So, please check it.

**Comment by fotisl** [comment]
The patch works great, thanks! Could you let me know the new way of setting the engine? With 2.0.67 I just used:
```
import WebCrypto from 'node-webcrypto-ossl';
const webcrypto = new WebCrypto();
pkijs.setEngine('OpenSSL', webcrypto, webcrypto.subtle);
```
which doesn't work at newer versions.

**Comment by fotisl** [comment]
I created a CryptoEngine object and everything works great, thanks!
