### ISSUE TITLE
Add support for x509 v2 Certificates

### ISSUE THREAD

**Issue by fotisl** [PeculiarVentures/PKI.js#142]
It would be nice if @YuryStrozhevsky could add support for x509 v2 certificates.  Please find attached a x509 v2 certificate used by Microsoft's timestamping server. As far as I can tell, it is used for timestamping all third party software.
[cert2.zip](https://github.com/PeculiarVentures/PKI.js/files/1595223/cert2.zip)

**Comment by fotisl** [comment]
The code that fails parsing this certificate is the following:
```
const asn1 = asn1js.fromBER(contents);
const cert = new pkijs.Certificate({ schema: asn1.result });
```
where contents is an `ArrayBuffer` containing the file contents.

I am also attaching a countersig([counterSig3.zip](https://github.com/PeculiarVentures/PKI.js/files/1595242/counterSig3.zip)) that cannot be parsed due to a x509 v2 certificate contained in the SignedData. Trying to parse it using the following code:

```
const asn1 = asn1js.fromBER(contents);
const cmsContentSimp = new pkijs.ContentInfo({ schema: asn1.result });
const cmsSignedSimp = new pkijs.SignedData({schema: cmsContentSimp.content});
```
fails by throwing the following exception during the last line:
```
Error: Object's schema was not verified against input data for AttributeCertificateV1
```

**Comment by YuryStrozhevsky** [comment]
@fotisl I made a fix for it. But should say it was not a deal about "x509 v2 certificate", but about AttributeCertificateV1 type - this is a specific type of certificates and in fact such type of certificates was deprecated in RFC5662. Anyway PKI.js has support for AttributeCertificateV1 and now it handles better, thanks for your issue. Please check with your data.
