### ISSUE TITLE
key.usages problem on PKCS#12 example

### ISSUE THREAD

**Issue by variux** [PeculiarVentures/PKI.js#145]
I try to parse a .p12 file using the provided example in [PKCS#12 example](https://pkijs.org/examples/PKCS12SimpleExample.html) but when I try this function, I get this error.

![Screencapture PKCS#12](https://user-images.githubusercontent.com/2768245/34854407-29231f64-f6ff-11e7-8091-c4c78d5b04ec.png)

Thank you!

**Comment by YuryStrozhevsky** [comment]
@variux The problem was fixed long time ago in main PKI.js code but accidentally fix was not introduced on pkijs.org examples. Thanks for the issue, fixed.
