### ISSUE TITLE
How can I add subjectAltName to CSR (PKCS#10 complex example)

### ISSUE THREAD

**Issue by anindyasundar** [PeculiarVentures/PKI.js#146]
I am new to PKI JS. 

I was looking at the source code of [PKCS#10 complex example](https://pkijs.org/examples/PKCS10_complex_example.html) 

But can't figure out how to add subjectAltName to the CSR.

Please help.

Thank you.

**Comment by YuryStrozhevsky** [comment]
@anindyasundar Check [this issue](https://github.com/PeculiarVentures/PKI.js/issues/107) and all links from there for examples.
