### ISSUE TITLE
PKCS#12 online example not working on data parsing

### ISSUE THREAD

**Issue by variux** [PeculiarVentures/PKI.js#147]
Hi, I was trying to use the example given in the PKI.js webpage but when I write the password and then upload the .p12 the page doesn't do anything and doesn't give any errors (even at console), the function handlePKCS12 get triggered through a java script .change function with id  pkcs12_file so I deduce that I don't need any more to do.

Some info about the .p12 file:
Password protection
DEK-Info: DES-EDE3-CBC
3 certificates 
It's using AES-256 2048

Thank you!

**Comment by YuryStrozhevsky** [comment]
@variux The web version of PKIjs PKCS#12 example can not use DES algorithm, only the algorithms supported by WebCrypto API. But you could use [Node.js version of the example](https://github.com/PeculiarVentures/PKI.js/tree/master/examples/NodePKCS12Example) which has DES support.

**Comment by variux** [comment]
I don't know If i'm doing the things wrong but I'm trying to execute the file exported by rollem at the test folder and I getting a syntax error 

`ReferenceError: context is not defined`

**Comment by YuryStrozhevsky** [comment]
@variux This is only an example, you could not directly use it by exporting.

**Comment by variux** [comment]
Thank you @YuryStrozhevsky, I looked at the example that the certificate is variable called "x509CertificateBASE64", is possible with this library to extract that Certificate and private key from p12 file, I need to use it with xADESjs and I need to extract those before using xades

**Comment by YuryStrozhevsky** [comment]
@variux It is possible with this library to extract any data from PKCS#12 files. See examples.

**Comment by variux** [comment]
I found them thank you @YuryStrozhevsky, I'm sorry I didn't remember that test folder is for automatized test
