### ISSUE TITLE
Unable to create webcrypto object

### ISSUE THREAD

**Issue by variux** [PeculiarVentures/PKI.js#148]
I was trying to extract information from PKCS#12 using example codes 

[Here's the code in gist](https://gist.github.com/variux/6b8ccde8d71a80d2b1575469218a9ce6)

But I'm getting the error Unable to create webcrypto object

**Comment by YuryStrozhevsky** [comment]
@variux Please do not create a new PKIjs issue on any your new error.

@variux You forgot "setEngine" call:
```javascript
const WebCrypto = require("node-webcrypto-ossl");
const webcrypto = new WebCrypto();
setEngine("newEngine", webcrypto, new CryptoEngine({ name: "", crypto: webcrypto, subtle: webcrypto.subtle }));
```

**Comment by variux** [comment]
Thank you! @YuryStrozhevsky I'm sorry, you can close the other also.

**Comment by meadhbh-hamrick** [comment]
So now that node-webcrypto-ossl is deprecated, what's the alternative?  Is there documentation for this somewhere?
