### ISSUE TITLE
Performance degradation during P12 generation with PKI.js upgrade

### ISSUE THREAD

**Issue by jeromewagener** [PeculiarVentures/PKI.js#150]
Hello PKI.js Team,

After upgrading from PKI.js 2.0.66 to 2.1.13 we noticed a performance degradation during our P12 generation. After analyzing the issue we discovered that the following commit was in between our version jump: 7b953ee08ee342d085328ec02152c087dae74917

It seems that in between the two versions, the PFX/crypto engine integration changed. In particular we discovered that with the newer version, data within the container is stamped which was not done before.

```JavaScript
sequence = sequence.then(() =>
	engine.subtle.stampDataWithPassword({
		password: parameters.password,
		hashAlgorithm: parameters.hmacHashAlgorithm,
		salt: saltBuffer,
		iterationCount: parameters.iterations,
		contentToStamp: data
	})
);
```

After debugging through the code it seems normal that our P12 generation now takes longer than before due to the additional stamping. In fact, after adding some console logs we can see how the call to the engine takes quite some time.

```JavaScript
// with Chrome Version 61.0.3163.100 (But similar results with newer Chrome/Firefox versions)
Started stamping at:  1517406923599
Stopped stamping at:  1517406930440
```

However, we were surprised as the generation (depending on the Browser) now takes 6-12 seconds whereas it was instantaneous before that. At some point we also suspected external factors but we checked and we can see that with the older version (2.0.66), with the same browsers and test environment performance is good.

Could you please confirm our view / analysis on this?

Thank you in advance and thank you for this great library!

Kind regards,
Jérôme

**Comment by YuryStrozhevsky** [comment]
@jeromewagener In fact it is normal to have a kind of “degradation” here. It is all because from be beginning PKIjs has **invalid** algorithm for making MacData in P12. And now, after we fixed it, it takes a little bit longer because of complicated algorithm required for making such peace of P12. So, your degradation is normal, no need to worry about that.

**Comment by jeromewagener** [comment]
@YuryStrozhevsky after our analysis this is exactly what we thought had happened and we were waiting for your confirmation. Thanks a lot for the quick response!

Kind regards,
Jérôme
