### ISSUE TITLE
jsnext:main is being deprecated move to its replacement

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/PKI.js#153]
It seems jsnext:main has been [deprecated](https://github.com/jsforum/jsforum/issues/5).

This means we will need to switch to its replacement?

**Comment by rmhrisk** [comment]
Related link: https://github.com/rollup/rollup/wiki/pkg.module

**Comment by YuryStrozhevsky** [comment]
@rmhrisk I left `jsnext:main` in our `package.json` file. At the same time I append `module` information. So now all modern "NPM workers" could recognize our ES6 main module.
