### ISSUE TITLE
Not able to use CertificateComplexExample from PKIJS

### ISSUE THREAD

**Issue by abhinandanpatilInd** [PeculiarVentures/PKI.js#155]
Hi,
I've downloaded PKIJS library and I'm trying to use this for one of my feature development. I've to validate the X-509 certificate issued by third party CA's. For this I set up the CertificateComplexExample on my local laptop. I bundled the CertificateComplexExample  using "npm run build:examples" commands and able to "bundle.js" available in examples folder. 
I had also transpiled this bundle using babel and now I'm able to see the "bundle.js" is now compatible with ES5 standard. 
While running X509_cert_complex_example.html file, I'm getting errors like "handleFileBrowse is not defined" although this function is available in "bundle.js" and its already loaded in browser.

I'm bit surprised to see this behavior, why the browser is throwing this error even though such objects are already available in "bundle.js".

Please share your views on this. Some had experienced this before? Is any mistake I'm doing to setup the PKIJS locally?

Also any reference documentation on setting up PKIJS (with transpiling) is much appreciated.

**Comment by YuryStrozhevsky** [comment]
@abhinandanpatilInd The problem you had is because current PKIjs when "transpired" to ES5 requires `babel-polyfill` usage. I have updated all PKIjs example - now all examples include `babel-polyfill` script by default.

**Comment by abhinandanpatilInd** [comment]
Excellent!! Thanks for this.
