### ISSUE TITLE
Retrieve Public key from X-509 certificate

### ISSUE THREAD

**Issue by abhinandanpatilInd** [PeculiarVentures/PKI.js#158]
I need to retrieve **Public key** from X-509 certificate in order to encrypt my sensitive data using this public key.
I can see class "RSAPublicKey", but this class is not providing/exporting the public key. Is there any way to fetch the public key using PKIJS library?
I'm referring to ComplexCertificateExample where it creates and parse the certificate and shows some information about public key like Public key size (bits), but it is not printing Public key with below notion:
-----BEGIN PUBLIC KEY-----
-----END PUBLIC KEY-----

Any pointers on this are highly appreciated!!

**Comment by YuryStrozhevsky** [comment]
Seems you missed existing example “howtoencryptusingcertificate”.

**Comment by abhinandanpatilInd** [comment]
Thanks YuryStrozhevsky!
I tried to use "CMSEnvelopedExample". I'm getting encrypted data length as 684 for a data to be encrypted "23cdcde1e0a7a2b7dfdf2acdf12afdcd". At the same time when I encrypt same clear key data with the same certificate in Java crypto API's, I'm getting length of "344". 

I also observed that "Content encryption algorithm" PKI supports "AES-*", isn't it possible to use RSA as content encryption algorithm?

I'm using Payshield HSM's to decrypt my sensitive payloads. HSM only accepts 344 length encrypted data.

**Comment by rmhrisk** [comment]
Asymmetric encryption is only designed for encrypting data smaller than it's key size.

**Comment by rmhrisk** [comment]
As for your length issue, if your getting a different length in java that your issue is character encoding.

https://www.w3.org/International/questions/qa-what-is-encoding

**Comment by abhinandanpatilInd** [comment]
You mean to say base64 encoding output will differ from technology-to-technology? I was in impression that the base 64 encoding will remain same across any technology!!

I have sensitive information coming from browser and want to encrypt it (RSA encryption and Base 64 encoding) it at browser side, and this  same information will be decoded and decrypted at java side to give calls to Payshield HSM hardware boxes. 

In this case, will the encoded clean key at javascript will never be decoded at java side to form the original block to be decrypted  ?

**Comment by YuryStrozhevsky** [comment]
@abhinandanpatilInd You know, you are not the first person in the world using PKIjs encryption :) And please be 100% sure it was completely tested even before publishing the code at the very first time. All the data produced by PKIjs was tested against OpenSSL and Windows Crypto API - no issues.

If you have an issue please first of all check - probably you done something wrong with encryption in PKIjs or in decryption using Java. Crypto interfaces are pretty complicated and misunderstanding of details could lead to big problems.

If you still sure you done all right then we would need a test data to analyze. Without we could not help you with anything else.

**Comment by YuryStrozhevsky** [comment]
@abhinandanpatilInd Also probably you missed this [README](https://github.com/PeculiarVentures/PKI.js/blob/master/examples/HowToEncryptCMSviaCertificate/README.MD). Here you could see this:

> NOTE: CMS EnvelopedData supports a concept of recipient types when encrypting to a subject of an certificate. At this time you can not specify the "type" of recipient. Certificates with RSA signatures the recipient's type will be KeyTransRecipientInfo and certificates with ECC signatures it will be type KeyAgreeRecipientInfo. It is not possible to support this case with WebCrypto at this time because there are no good support for the DH algorithm in all browsers (FireFox has problems with exporting/importing keys and Google Chrome has no implementation for DH at all). When this changes it will be possible to add support for KeyAgreeRecipientInfo for both RSA and ECC certificates.

So, different key transfer schemes could lead to a different size of output data. Also in case if PKIjs could use only KeyTransRecipientInfo and Java code could accept only KeyAgreeRecipientInfo it will lead to an "issue" during decryption.

**Comment by abhinandanpatilInd** [comment]
Thanks YuryStrozhevsky for patients. Although I'm not the alone using PKIJS library, but I'm using it first time with having intermediate knowledge of Cryptography. I'm a Java Guy and not a Java script. :)

Here are some updates on the size. Gone through the README details. I've to use first type "addRecipientByCertificate" where post successful parsing of certificate, public key from it will be used to encrypt the payload. I also deep dive into HSM manual and got to know that there is a option to import the payload which is encrypted with RSA-OAEP algorithm. So, I'm now trying to import the encrypted payload which is the outcome of our PKIJS example "howtoencryptusingcertificate" into HSM. Hope I'd get success with that. 

Thanks again for your support!!

**Comment by abhinandanpatilInd** [comment]
Hi YuryStrozhevsky,

Is there any way to encrypt the Payload with RSA algorithm instead of using AES-CBC or AES-GCM.

In my case size of data to be encrypted will always be less than the size of RSA public key. 

Do PKIJS supports or have any provision for encrypting the payload with RSA algorithm?

**Comment by YuryStrozhevsky** [comment]
No pkijs has no support for such case. But you could make your own code based on pkijs.

**Comment by rmhrisk** [comment]
You should avoid that pattern, there are other cryptanalysis risks unless you know what your doing.
