### ISSUE TITLE
How to parse a Promise returned by verifyCertificate method

### ISSUE THREAD

**Issue by abhinandanpatilInd** [PeculiarVentures/PKI.js#161]
I have a requirement where verifyCertificate() should return the boolean true or false to the caller of this function (In my case call is a jsp file).

function verifyCertificate()
{
	return verifyCertificateInternal().then(result =>
	{
		alert(`Verification result: ${result.result}`);
	}, error =>
	{
		alert(`Error during verification: ${error.resultMessage}`);
	});
}
I tried with many combinations to return the value as true or false instead of alert in above code. None of those attempts succeed. Can we parse this promise returned by verifyCertificateInternal() ?

**Comment by YuryStrozhevsky** [comment]
We do not provide consultations regarding your own code-specific problems.

**Comment by rmhrisk** [comment]
StackOverflow is a good place to request help understanding how to use JavaScript. We are happy to help with issues relating to how to use PKIJs.
