### ISSUE TITLE
OpenSSL verify command fails to check CA signed certificate created with `pkijs` 

### ISSUE THREAD

**Issue by lejlabecirspahic** [PeculiarVentures/PKI.js#162]
Implementation mostly follows example given in https://github.com/PeculiarVentures/PKI.js/blob/master/examples/CertificateComplexExample/es6.js, except that certificate issuer is set to CARoot subject and that certificate is signed with CA private key:
`x509Certificate.issuer.typesAndValues = CARootCertificate.subject.typesAndValues;`
` await x509Certificate.sign(CAprivateKey, hashAlgorithm);`

Resulting certificate is saved as cert.crt.

*openssl verify -CAfile CAroot.crt  cert.crt* will result in 
`cert.crt: O = test + CN = test
error 20 at 0 depth lookup:unable to get local issuer certificate`
Interesting thing is that cert.crt passes *CertificateChainValidationEngine.verify* against CARootCertificate.

Have someone tried something similar before? I would really appreciate your help!
Thanks

**Comment by YuryStrozhevsky** [comment]
I need base64 encoded cert for testing. As for “have anyone tried it” - we know about number of real services successfully working on pkijs.

**Comment by lejlabecirspahic** [comment]
`-----BEGIN CERTIFICATE-----
MIIDDTCCAfegAwIBAQIBATALBgkqhkiG9w0BAQUwHDEaMAsGA1UECgwEdGVzdDAL
BgNVBAMMBHRlc3QwHhcNMTYwMTMxMjMwMDAwWhcNMTkwMTMxMjMwMDAwWjAaMRgw
CgYDVQQKEwMxMjMwCgYDVQQDEwM0NTYwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
ggEKAoIBAQCPi5Lepbz15dduE6d6sr4VTJaDN7/XcKT4KllOxoFuvl2w+b844W62
aAdH6s59dNmMSNozmlBPvDUMqMSjWvpJiPft0kWAMno9MeuGdDzmwjB5JY6aJIEj
4EC1cuYRGAw15/0vCltB+msTUTBUf09qHYy869HCzhqr2sC9jCCgYbo7uudPsgyC
cG6c4vH2beXg87u1uGdjgIml9xsKtwFjcMU7DWPf6HfDq17JTqJfCavny8NZem2C
mBpBdD8WxYgYvgvYxHSCGb0VVG/ukFQfKKClYQg0m1uaPgvFfISR9mgI0BN6ZYsA
2EbC7p30z5MtyeHnO2G22fAOtplFWRBLAgMBAAGjYDBeMAwGA1UdEwEB/wQCMAAw
HQYDVR0OBBYEFNlmD2X3CMR268SAdJrZ6MxMrK17MB8GA1UdIwQYMBaAFL6h60lQ
D939lJyl+h4BVuIFfMhRMA4GA1UdDwEB/wQEAwIA4DALBgkqhkiG9w0BAQUDggEB
AEQ2kTMzVLWRCo4gyD4ri34gliH0Mm7Tvi3XZTmW+7oVZFz+y9Fh+aM6Odw9ta+H
hvaq0O2hVaoLNWrLNUVgHZ7sDs/Mq7omHvUYkL6v1He3k0zuCTs8N02udsIUusSd
8fUOsVxCYDEecv0ozgGuHn8Q4+ILdrpzOzcMUSaM7cVnUHiDNL+dkkXrYthtVrd5
BaontBLPKqoAvDKAzZbOqW9huZJVB+8a10utONRhw60dMMaJCE2w4Jqt8XU65F06
ckYc5jjv0aQHSIQg1iC50P4Re1F8oXhsMuok/zEMehNDWfz35Ro/PvniKrsrRtGD
ELs2sCidKJk2ekEE6SeDbVk=
-----END CERTIFICATE-----`

ROOT
`-----BEGIN CERTIFICATE-----
MIICuDCCAaACCQD1yJgKJc/T9DANBgkqhkiG9w0BAQsFADAeMQ0wCwYDVQQKDAR0
ZXN0MQ0wCwYDVQQDDAR0ZXN0MB4XDTE4MDMyNzE5MjYwMVoXDTE5MDMyNzE5MjYw
MVowHjENMAsGA1UECgwEdGVzdDENMAsGA1UEAwwEdGVzdDCCASIwDQYJKoZIhvcN
AQEBBQADggEPADCCAQoCggEBAJ1ih86lLhNS8kQRUi9xOIEUN3kuaaikP/jZYu+7
g6qL8O70s04WiEsPOMx0TQiFVmO+XTvPwxAUabusWiZ7s5wrvkuLEHqDbL1rh5QK
P+58NcSl+XZpN+l9TA7y7Cn635WMeWUGB02MCpyT53qP9HoNVGU+swQK64OmhVgN
SQiV9jAvva9NoJBGGdUm6IEr61sV7YhKUpr5HANetg9gK2cJCa8AhfvoEEMsUvaX
SPk6qIqGADciTKrimXjkHfoSke911H3RmYFhxah2ZvXNZ5SqANN/Xm52RSqWbwoo
T67QB43riAG4I59qfiFQKqWjGVE4+qB2VmYZfXgo5SFxWEUCAwEAATANBgkqhkiG
9w0BAQsFAAOCAQEAjZFaR7jlo6baBIXADmy2JPiNXi7oKeWPn0X0jWojG61ZGA1i
p2AnLYDV5mzZylMnGqpRJQzfXN/84q+OkaMhL7MtM0E6m4nqTN/MA5aXEWIjbxnu
mmsl/Us+HSHG967QsrxiG7E+o16lMtBKu4pcfuzKHnONICwSgonr0JFg4DY5E9Cm
XEf+9ktCnJRbEvElpy7u7WYWwMgVSBUfK73C2Dvdr76YuSVPN7cbawzN1dRoUKu7
pohEyq8QWSHNtJ3MQNdZ+8G5jdfniQk54qIOZJvvUe/Go6AkIqDJn8rPRGAH6pqZ
tDvG1YMD7U2MPwrKiFDamTlWz6Xp+rOQmwHSyA==
-----END CERTIFICATE-----`

**Comment by YuryStrozhevsky** [comment]
I will check all within 12 hours

**Comment by YuryStrozhevsky** [comment]
@lejlabecirspahic Seems the problem with your certificates is that `Authority Key Identifier` inside `user certificate` does not match key identifier of `root certificate`. You need to re-create your `user certificate` with a correct data.
