### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by alphanso** [PeculiarVentures/PKI.js#163]
~/project/node_modules/pkijs/build/CertificateChainValidationEngine.js:160
                        var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee(certificate, validationEngine) {
                                                                   ^

ReferenceError: regeneratorRuntime is not defined

This is happening because latest babel has some issue and this repository is tagged to latest.

**Comment by YuryStrozhevsky** [comment]
Please read README carefully - there you will find example how to use pkijs in Node environment. Also check already closed issues for additional information.

**Comment by DanielRamosAcosta** [comment]
Requiring the user to install manually `babel-polyfill` and require it is very ugly. And it's extremely confusing when using XAdESjs.

**Comment by YuryStrozhevsky** [comment]
@DanielRamosAcosta Do you have a better solution, proposals?

**Comment by DanielRamosAcosta** [comment]
Maybe specifying a target in `babel-preset-env` could be a solution, as stated in babel/babel#5085. I've tried.

**Comment by YuryStrozhevsky** [comment]
@DanielRamosAcosta In fact PKIjs is a pure ES6 library and all the transpilation required only if you really need a ES5 code. And the ES5 code could be required not only under Node but also in a browser - we would like to have PKIjs as an universal library. But if the solution you proposed works for you (I did not checked it yet) then you have an option to integrate it in the secondary packages like XAdESjs etc. - these libs could use PKIjs ES6 code initially and then, if needed, transpile it into ES5 using your `.babelrc` modifications.

**Comment by l-ko** [comment]
maybe use babel transform-runtime plugin at the building stage

**Comment by YuryStrozhevsky** [comment]
@l-ko Then user would require to use `transform-runtime` during PKIjs usage - the same egg from another side :)

**Comment by DanielRamosAcosta** [comment]
Correct me if I'm wrong, but I think the way to proceed is transpiling just into node (6 for example) and users developing for the browser should use webpack transpiling into their ES target or use a pki.min.js.

You could also release an "*-es" version for webpack's tree shaking feature.

**Comment by YuryStrozhevsky** [comment]
@DanielRamosAcosta No, user could, for example, use Rollup and then create a ES5 code from result bundle. This is how PKIjs examples transpiled to pkijs.org. We do not care about any package-specific features and do not rely on only Webpack, for example.

**Comment by DanielRamosAcosta** [comment]
Ok, you are releasing the untraspiled version at `./src/index.js`, pointed by `module` and `jsnext:main` key at `package.json` for bundlers.

So why not transpiling the `main` (pointing at `./build/index.js)` targeting node?

**Comment by YuryStrozhevsky** [comment]
@DanielRamosAcosta As I said PKIjs should be using not only in Node but also in browser.

**Comment by YuryStrozhevsky** [comment]
@DanielRamosAcosta Why you think "they" would be using only code under `src`? What is a stopper from using code from `build`? For example when using `browserify` package.

Seems I need again pay attention on **PKIJs is a pure ES6 library**. And all the code from PKIjs is a pure ES6 code. Any secondary library has options:
1. Use `import { anything } from "pkijs"`;
2. Use `var pkijs = require("pkijs");`
3. Use `import { anything } from "pkijs/src/index"`;

In first two options you would use ES5 code from PKIjs. In the third option you would use ES6 code from PKIjs. All it up to you. Then you could transpile code to ES5 it you wish, or use it directly in Node, or use Rollup to make a big bundle - I do not care. But if you choose first two options then sorry - you would require to use the **NASTY-EVIL** `require("babel-polyfill")`. So, all is up to you, it is not a problem in PKIjs - all it up to secondary lib developers how to use PKIjs code.

**Comment by YuryStrozhevsky** [comment]
@DanielRamosAcosta Not sure I understood this sentence correctly:

>  In this transpilation, you could target a just slightly higher ES version that doesn't require babel-polyfill

Could you explain what did you mean here?

**Comment by DanielRamosAcosta** [comment]
`babel-polyfill` is only needed when you target very old browsers. If you specify, for example,  `chrome: 50` in babel-env-preset, `babel-polyfill` disappears in favour of [ES6 generators](https://caniuse.com/#feat=es6-generators) for simulating async/await.

**Comment by YuryStrozhevsky** [comment]
@DanielRamosAcosta Good proposal! I would experiment with it tomorrow. But in any cases we do not want to restrict usage of PKIjs to some limited number of browsers/node env. Put any `target` in `babel-env-preset` config file would lead to such limitations.

**Comment by DanielRamosAcosta** [comment]
Thanks @YuryStrozhevsky! There are not any restrictions as PKIjs relies on the Web Cryptography API and it already requires a relatively modern browser. Despite, the limitation would be only on the transpiled `src` directory. If a user needs to transpile even more to support very old browsers, they can use the code under `pkijs/src/index` and transpile it themselves using any code bundler.

**Comment by YuryStrozhevsky** [comment]
@DanielRamosAcosta In fact I can say the same to you (and I already said you that):  
if you need to have PKIjs code without `babel-polyfill` you could transpile it yourself using any code bundler.

**Comment by YuryStrozhevsky** [comment]
@DanielRamosAcosta At the time Node has no support for `import` directive and that is why especially for Node we definitely need to use bundles like Rollup. Or even a set of bundles like Rollup+Babel.

**Comment by DanielRamosAcosta** [comment]
Still today, `import` isn't well supported in node, only in v10 and that's not a LTS version.

Node users expect to use all ES6 features natively, excepting for `import`, when they use `require` or something like `@std/esm`.

As a library developer, you can write full ES6 code, but when releasing for node you only need to transpile the `import` statements.

**Comment by YuryStrozhevsky** [comment]
@DanielRamosAcosta The `transpilation of import statement` could be done on `user's side` by using a bundler like Rollup, as I said. All these is up to `users` of PKIjs, it is not an issue for our lib.

**Comment by DanielRamosAcosta** [comment]
But you are transpiling the `import`s for the `src` directory!

**Comment by DanielRamosAcosta** [comment]
In summary, targeting specific browsers/node versions on `babel-preset-env` for the transpilation of the `src` directory will affect in the following:

## Users developing for browsers

* They can still use the code under `src`. It might not be compatible with IE11. In that case...
* They can transpile to wherever ES version they want using a code bundler. In fact, **this will be the default** when using bundlers like `webpack` or `rollup`

## Users developing for node
* They can use PKIjs out of the box, without the need of any Babel dependency.

**Comment by YuryStrozhevsky** [comment]
Hm, seems we are rolling on the same circle. As I can see you want me to make Node users as a "first class" and leave browser users as a "second". But as I said many times we would not differ any users - all are at the same "class". If you do want something from PKIjs code - do it on the `user's side`, inside a products using PKIjs. It is **not an issue of PKIjs**  that you have a problems with `babel-polyfil`. You have many options how to fix it in a product which is using PKIjs.

**Comment by DanielRamosAcosta** [comment]
I want to make Node users a first class **and browsers too!**. Why do you think I'm leaving  browser users as a second?

**Comment by YuryStrozhevsky** [comment]
@DanielRamosAcosta After some discussion was decided to put "low limit" in PKIjs code compilation - from now on PKIjs would be compiled for not less than Node v6 version. So, now PKIjs has no "regeneratorRuntime", at least not by default. Also other our libs would be re-designed the same way soon (probably even today). Hope it will satisfy all your needs :)

**Comment by DanielRamosAcosta** [comment]
Thanks a lot @YuryStrozhevsky !!
