### ISSUE TITLE
Ed25519 Support

### ISSUE THREAD

**Issue by apowers313** [PeculiarVentures/PKI.js#164]
New applications (blockchain, DID, etc.) are emerging that require Ed25519 curve support. Would it be possible to add Ed25519 to pkijs?

**Comment by rmhrisk** [comment]
WebCrypto does not yet support this algorithm. First step would be to add it to WebCrypto, we have a project called WebCrypto-liner that is a polyfill for webcrypto based on JavaScript implementations.  We have added 256k1 to this even though WebCrypto does not support it; the same could be done here in theory. With that done support in PKIjs would be straight forward. Until that is done there is nothing we could do. PR welcome.

**Comment by apowers313** [comment]
I don't think it needs to be added to WebCrypto, just to the [IANA registry](https://www.w3.org/TR/WebCryptoAPI/#iana-section). And I think @selfissued is in the process of doing that for both Ed25519 and k curves. Is that right Mike?

@rmhrisk Is the correct place to make this request in [node-webcrypto-ossl](https://github.com/PeculiarVentures/node-webcrypto-ossl)?

**Comment by selfissued** [comment]
I am adding these and other curves to the IANA JOSE Algorithms registry and the IANA COSE Algorithms registry.

**Comment by rmhrisk** [comment]
@apowers 313 I think I would start with an issue in WebCrypto-liner @idutiny has added ed25519 to elyptic so you should be able to do a PR there easily.

For node node-WebCrypto-ossl would be the right place; this would require switching to either boring or the most recent OpenSSL; I think switching to boring would be best. An issue in that repository would be the best place to request that.

**Comment by rmhrisk** [comment]
@selfissued will you add 256k1 also? We have taken some liberties and added it to both of the afore mentioned libraries.

**Comment by selfissued** [comment]
Yes, I plan to add 256k1 for JOSE and COSE.  If you want to point me to what you've already done, I'll have a look at it.

**Comment by microshine** [comment]
@selfissued [webcrypto-liner](https://github.com/PeculiarVentures/webcrypto-liner), [node-webcrypto-p11](https://github.com/PeculiarVentures/node-webcrypto-p11), [node-webcrypto-ossl](https://github.com/PeculiarVentures/node-webcrypto-ossl) support scep256k1 named curve. It has `K-256` name for WebCrypto API
