### ISSUE TITLE
Text improvement for not yet valid

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/PKI.js#165]
Current text:
https://github.com/PeculiarVentures/PKI.js/blob/663d9552df07044b340e1a43cc08cd30a911157e/src/CertificateChainValidationEngine.js#L534

Should be:

The certificate is either not yet valid or expired. This can be a result of clock synchronization between the issuer and the client or the certificate is too old to be relied upon.

**Comment by YuryStrozhevsky** [comment]
Done
