### ISSUE TITLE
Tags for latest v1.x

### ISSUE THREAD

**Issue by coolaj86** [PeculiarVentures/PKI.js#167]
The latest tag on github is v1.2.1, but this has bugs that have since been fixed.

It looks like 1bc0ed371f377e12296f38cb76fe03c3217d03ac (Mon Nov 21 20:11:45 2016 -0800) is the latest of v1.3.x

I was able to find a few of the latest versions with git grep:

```
git rev-list --all | xargs git grep '1\.3\.33'
```

* v1.3.33 41b63af760cacb565dd850fb3466ada4ca163eff
* v1.3.32 25b84a0ef185e75e9e5ff6f8c759280fc5c98e62
* v1.3.31 0fe33c8fb799ad2773a0b1f7706aac5b73a55497
* v1.2.4 966c7181792bd5ae991e1074449f712f9809fefd
* v1.1.0 ebea506c341c086eb5915078dbbdda7af732e985

Will you add the latest of the v1.x versions as tags?

**Comment by YuryStrozhevsky** [comment]
@coolaj86 No, PKIjs V1 is not supported anymore.

**Comment by coolaj86** [comment]
I understand that you don't plan to continue support, however, most of the examples that exist are built around v1.x and most of the code that exists is built around v1.x, so it would be very helpful to have the tags in git.

**Comment by YuryStrozhevsky** [comment]
All examples and all codes are for V2 only.

**Comment by YuryStrozhevsky** [comment]
PKIjs V2 was released 6 Jun 2017, almost one year ago. Native ES6 support (even with `import` directives now) exists in Chrome (and many other browsers) for years. How to use it you could read, for example, [in our README](https://github.com/PeculiarVentures/PKI.js/blob/master/README.md#how-to-use-pkijs-es6-files-directly-in-browser). Also Node.js has native ES6 support `from the box`. If you do not want to use transpilers then fine - we ship already transpiled ES5 code in `build` directory. So, I see no real values using old PKIjs V1 now, frankly speaking.

**Comment by coolaj86** [comment]
But why replace the JavaScript version in the first place?

And why not create `PKI.es` (just like there's es-git and js-git) instead of writing v2 in a fundamentally different language than v1?

ES20xx is slower, it has far less support, it's got a completely different syntax from JavaScript (it looks more like Swift and was designed by a committee of C# and Ruby developers, not JavaScript developers).

And sure, there's a big crowd that wants a Swift / C# style language for the web, and a lot of buzz around it at the moment.

However, there's also a lot of us out here that aren't into ES and React and Webpack and TypeScript and all that and we just want to use things that are simpler and more familiar and more stable and that we trust.

**Comment by rmhrisk** [comment]
Like it or not ES6 is JS. It was a major version change so it got a major version update. The new version is FAR superior code wise, has test coverage, more features, etc.

I appriciate that some would prefer not to have to adopt ES6 and don’t want to transpire but we can not support the older version. It is a security library and the maintenance of two parallel versions, one we know is concretely inferior, is not something we we can do.
