### ISSUE TITLE
SignedData.verify uses incorrect digest algorithm

### ISSUE THREAD

**Issue by killerstorm** [PeculiarVentures/PKI.js#170]
Within PKCS#7 message three different digest algorithms might be used:

1. SignedData.digestAlgorithms is applied to ContentInfo.content
2. Certificate.signatureAlgorithm "The signatureAlgorithm field contains the identifier for the
   cryptographic algorithm used by the CA to sign this certificate."
3. SignerInfo.digestAlgorithm is applied to SignerInfo.authenticatedAttributes (if present).

PKI.js confuses all three:

1. It applies  SignerInfo.digestAlgorithm to ContentInfo.content (this is kept in variable shaAlgorithm in code)
2. It applies Certificate.signatureAlgorithm to SignerInfo.authenticatedAttributes (by passing `signerCertificate.signatureAlgorithm` to `engine.subtle.verifyWithPublicKey`.

I have a particular PKCS#7 message it fails on, let me know if you need it.

**Comment by YuryStrozhevsky** [comment]
@killerstorm Seems you missed some details from standard. 

So, what we have in PKCS#7 (aka RFC2315) for `SignedData.digestAlgorithms`:
```text
        o    digestAlgorithms is a collection of message-digest
             algorithm identifiers. There may be any number of
             elements in the collection, including zero. Each
             element identifies the message-digest algorithm
             (and any associated parameters) under which the
             content is digested for a some signer. The
             collection is intended to list the message-digest
             algorithms employed by all of the signers, in any
             order, to facilitate one-pass signature
             verification. The message-digesting process is
             described in Section 9.3.
```
```text
9.3 Message-digesting process

   The message-digesting process computes a message digest on either the
   content being signed or the content together with the signer's
   authenticated attributes. In either case, the initial input to the
   message-digesting process is the "value" of the content being signed.
   Specifically, the initial input is the contents octets of the DER
   encoding of the content field of the ContentInfo value to which the
   signing process is applied. Only the contents octets of the DER
   encoding of that field are digested, not the identifier octets or the
   length octets.
```
First of all you need to understand that **it is a collection** of all algorithms from all nested `SignerInfo.digestAlgorithm` values, nothing else. These algorithms do not apply directly to any data in `SignedData` type.

As for `SignerInfo.digestAlgorithm` we have this information in RFC2315:
```text
        o    digestAlgorithm identifies the message-digest
             algorithm (and any associated parameters) under which the
             content and authenticated attributes (if present) are
             digested. It should be among those in the digestAlgorithms
             field of the superior SignerInfo value. The message-
             digesting process is described in Section 9.3.
```
Here you should pay attention on **digestAlgorithm identifies the message-digest algorithm (and any associated parameters) under which the content and authenticated attributes (if present) are digested**. So, the `SignerInfo.digestAlgorithm` applies to `content` if `authenticatedAttributes` are absent and apply to `authenticatedAttributes` only in other case. This is how all designed in PKIjs.

Now let's discuss a most tricky part: usage of `Certificate.signatureAlgorithm`. The reason why we using `Certificate.signatureAlgorithm` as a source for verification is because during signing we need to use private key for specific signer. And the private key for signer need to be aligned with public key from signer certificate and there is no option to have different parameters for public and private keys. The `Certificate.signatureAlgorithm` has all information about algorithm together with used hash function. And it is no way to use hash function different from initial hash function in certificate - cryptographic engines would generate error when would try to avoid the rule. That is why we are using `Certificate.signatureAlgorithm` as a source for verification.

Anyway, if you have a real `SignedData` which violates existing PKIjs rules please paste it here. If it is a private information feel free to mail me directly yury@strozhevsky.com

**Comment by YuryStrozhevsky** [comment]
@killerstorm Probably you would argue that better here would be to use `Certificate.subjectPublicKeyInfo` data, but it is not 100% correct - it is possible to get all information about public key algorithms from `Certificate.subjectPublicKeyInfo`, but only for simple RSA-SSA algorithm. For algorithms like RSA-PSS and ECDSA information about has is encoded in `Certificate.signatureAlgorithm`.

**Comment by killerstorm** [comment]
> So, the SignerInfo.digestAlgorithm applies to content if authenticatedAttributes are absent and apply to authenticatedAttributes only in other case. This is how all designed in PKIjs.

No, it's not applied to authenticatedAttributes. This is the problem.

E.g. SignerInfo.digestAlgorithm=SHA256, Certificate.signatureAlgorithm is sha1WithRSAEncryption.

In that case PKI.js applies SHA256 to ContentInfo and passes SHA1 to verifyWithPublicKey. SHA256 is not used on authenticatedAttributes.

> Now let's discuss a most tricky part: usage of Certificate.signatureAlgorithm.

That's a signature algorithm which was used by CA to sign the certificate. Are you saying that if **CA** used SHA1 to sign my certificate then I can only sign data with SHA1 with my key? This is clearly bullshit.

**Comment by YuryStrozhevsky** [comment]
> Are you saying that if CA used SHA1 to sign my certificate then I can only sign data with SHA1 with my key?

Yes, `SignerInfo.digestAlgorithm` and `Certificate.signatureAlgorithm` has must be the same. If you have any real data violating the rule please post it here.

**Comment by killerstorm** [comment]
I found no way to attach file to a github issue, so I sent it by email. It is a signature produced by 
Telia e-identification https://cve.trust.telia.com/TeliaElegNG/

**Comment by YuryStrozhevsky** [comment]
@killerstorm The file you sent me failed during verification using even OpenSSL:
```command
openssl cms -verify -inform DER -in fnewtelia.p7b
```

**Comment by YuryStrozhevsky** [comment]
Just for a reference I would put BASE-64 encoded `fnewtelia.p7b` file here:
```
MIIIZQYJKoZIhvcNAQcCoIIIVjCCCFICAQExDzANBglghkgBZQMEAgEFADCBigYJ
KoZIhvcNAQcBoH0Ee0RUOGxPTTNwQjE4PVRlc3QgRm9ybGl0YW5kZWNlcnRpZmlr
YXQwMzczNTk5YTYxY2M2YjNiYzAyYTc4YzM0MzEzZTE3MzdhZTljZmQ1NmI5YmIy
NDM2MGI0MzdkNDY5ZWZkZjNiMTVTaWduIHlvdXIgZXNwbGl4IGtleaCCBTUwggUx
MIIDGaADAgECAg8BYZ2jWZQuegs0UmKVSWkwDQYJKoZIhvcNAQEFBQAwTzELMAkG
A1UEBhMCU0UxEzARBgNVBAoMClRlbGlhIFRlc3QxKzApBgNVBAMMIlRlbGlhIGUt
bGVnaXRpbWF0aW9uIFRlc3QgUFAgQ0EgdjMwHhcNMTgwMjE2MDgwMjUyWhcNMjAw
MjE3MDgwMjUyWjBeMQswCQYDVQQGEwJTRTEWMBQGA1UEAwwNRWJiZSBUZXN0c3Nv
bjERMA8GA1UEBAwIVGVzdHNzb24xDTALBgNVBCoMBEViYmUxFTATBgNVBAUTDDE5
MDEwNDIyNjM3ODCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAM3NNdLp
fEJphjXNJ3/bK7TM56wDc/7IXCSvgl5fNirG1CnPjGmSTdno3NNXfqb2PRtwfEXR
FPVw8jUsa7KhO8ND2o8Unmgo+tgrKklLZFwrQYQZ9oE3AhM1FX0luTmwFWZKJtL1
y80SRaxjLTcWpYpFYniA+xPxcOMJPWK4PoA/KoFtvi1+6yUpvSc+ITPWrDJLDOZt
BhWKXjqFehWiCSFSAR8JipyM2BgxawttH8AcMGj5fkbzLPC7n9/F4YRTVcGpX9vm
y+o8XbQku4GMV23n2q+ykhC0XjiRyN7NhfFReBBmgjHgR81ZMsZ6MS0qboQs/OTB
/YNTkY7dBLtvF9MCAwEAAaOB+jCB9zAfBgNVHSMEGDAWgBR9vkdBjANmExSqmDAQ
1KwK7c/t9jAdBgNVHQ4EFgQU/ieVlJtDgp/4VU/4xxmJDd3l2pAwDgYDVR0PAQH/
BAQDAgZAMEUGA1UdIAQ+MDwwOgYGKoVwI2MCMDAwLgYIKwYBBQUHAgEWImh0dHBz
Oi8vcmVwb3NpdG9yeS50cnVzdC50ZWxpYS5jb20wHQYDVR0lBBYwFAYIKwYBBQUH
AwQGCCsGAQUFBwMCMD8GCCsGAQUFBwEBBDMwMTAvBggrBgEFBQcwAYYjaHR0cDov
L29jc3AucHJlcHJvZC50cnVzdC50ZWxpYS5jb20wDQYJKoZIhvcNAQEFBQADggIB
AF/s4mtDzIjJns5b3YI2j9CKcbNOpVjCV9jUqZ+w5vSEsiOwZhNw6VXEnOVfANRZ
t+IDIyS5Ce9rWXqT5aUB5GDduOQL4jClLdMGPW1caOwD8f5QoBEeQCXnYvBefwYi
iCw+aa7XGpgmQD+qhWZWB4Xv4wOSilyvT40CPQAHYPlJhawtoOo7JOdSxSkaoeqQ
3XvNuCIH0xiuqJmWQGSzslIsWhv3hEYRxsD/6u1NxxOTCIJ19tXDy/IG7utxX7bb
aj3AHG+56IbvWuWODxS+KwzAvSub0vT9Uxy9hJOIPGe82DH/08Spk7FM/Q9ELlYd
wFHet7xFMyirj5kTpVwYp+qB+cN/H6y4DlrKut2j7qi859GWSMAX1a5+/UckuGHT
XwA2IvzazQws+hp8fv33eg8Oof7STepV6EYCw+Fw0xveg3OQaFip5lSpawcKnhWd
A4T2z8OvV1oR6CuokSwnFXN0bHeM4QbP6yjIQSi7J0Pmzi0DE7vU7OtenHaM3B6t
Z9ZtNyCOx6iAAOkUsVHz/O/tsVw8QEodg/OnCHwNsAPF0876ZF0nMQVYmcKYsxNj
7im9oTZFc/3VxJh4TMjJQc2H6qiM3LZHuSu309i5fkJy9CPtw8ebB5pjFvuU77Zf
yB/oqFoA/pM1/Bi/ARFBWAWVIGCo6Yp7sIQ8EkM6Of4gMYICdDCCAnACAQEwYjBP
MQswCQYDVQQGEwJTRTETMBEGA1UECgwKVGVsaWEgVGVzdDErMCkGA1UEAwwiVGVs
aWEgZS1sZWdpdGltYXRpb24gVGVzdCBQUCBDQSB2MwIPAWGdo1mULnoLNFJilUlp
MA0GCWCGSAFlAwQCAQUAoIHkMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJ
KoZIhvcNAQkFMQ8XDTE4MDQxOTEyNDQ0MlowLwYJKoZIhvcNAQkEMSIEIKHFvPWi
9uCq04rLzVviJjdfUuCni4uxivw1n7jBr3eXMHkGCSqGSIb3DQEJDzFsMGowCwYJ
YIZIAWUDBAEqMAsGCWCGSAFlAwQBFjALBglghkgBZQMEAQIwCgYIKoZIhvcNAwcw
DgYIKoZIhvcNAwICAgCAMA0GCCqGSIb3DQMCAgFAMAcGBSsOAwIHMA0GCCqGSIb3
DQMCAgEoMA0GCSqGSIb3DQEBAQUABIIBAAga2QlXM4ba8LxA9pD51cFfN8VZcSgM
BQwxNpy0y7vDWazE1M/IXPEEUUMsk6OVMLgS/Q/LCQ8nxYpZXRAkIMtnl1/L93LE
I/xa35gYFXrVp352b7evA3iDvE9O0aN4lufLGCxOiT5bJISmaaCVSVe8QFrSVSmF
SW/MkJKaFiFBWsXJJ3vQGnULlH0WIc5QnC2rpkAeEswsxgCA9VnQNclktv7gwS3G
NH2lLUbRl+tMMrrQ8Il4lEOnRG7W22tVdypVndLbeEoZe71u7bumJCc/U754SCCi
uX8CEZd55uzNPOPUPgXvWbSybh36oeMsWd21g57ZFU6FV6CNh3hGkp8=
```

**Comment by killerstorm** [comment]
$ openssl cms -verify -inform DER -in fnewtelia.p7b -noverify
     Verification failure
     140497264617112:error:0407006A:rsa routines:RSA_padding_check_PKCS1_type_1:block type is not 01:rsa_pk1.c:103:
     140497264617112:error:04067072:rsa routines:RSA_EAY_PUBLIC_DECRYPT:padding check failed:rsa_eay.c:705:
      140497264617112:error:2E09809E:CMS routines:CMS_SignerInfo_verify:verification failure:cms_sd.c:775:

It seems it fails in RSA processing, before it compares the digest.

We had no problem with RSA processing with this message using PKI.js, Forge or lower-level OpenSSL commands.

As far as I can tell from OpenSSL code, it would have applied digest algorithm from SignerInfo to authenticatedAttributes https://github.com/openssl/openssl/blob/master/crypto/pkcs7/pk7_doit.c#L957

**Comment by YuryStrozhevsky** [comment]
> As far as I can tell from OpenSSL code, it would have applied digest algorithm from SignerInfo

Yes, but in any case the digest algorithm must be equal with hash function used in signer's certificate. Thus in fact no difference here between OpenSSL and PKIjs code. As I said if you would find any real SignedData violating the rule please put it here or send to me. If you do not have such a data then I consider the issue as solved for now.

**Comment by killerstorm** [comment]
Sorry for confusion, I sent a signeddata which was intentionally corrupt.

Here's a real signeddata, let's call it newtelia.pem

`
-----BEGIN PKCS7-----
MIIIZQYJKoZIhvcNAQcCoIIIVjCCCFICAQExDzANBglghkgBZQMEAgEFADCBigYJ
KoZIhvcNAQcBoH0Ee0RUOGxPTTNwQjE4PVRlc3QgRm9ybGl0YW5kZWNlcnRpZmlr
YXQwMzczNTk5YTYxY2M2YjNiYzAyYTc4YzM0MzEzZTE3MzdhZTljZmQ1NmI5YmIy
NDM2MGI0MzdkNDY5ZWZkZjNiMTVTaWduIHlvdXIgZXNwbGl4IGtleaCCBTUwggUx
MIIDGaADAgECAg8BYZ2jWZQuegs0UmKVSWkwDQYJKoZIhvcNAQEFBQAwTzELMAkG
A1UEBhMCU0UxEzARBgNVBAoMClRlbGlhIFRlc3QxKzApBgNVBAMMIlRlbGlhIGUt
bGVnaXRpbWF0aW9uIFRlc3QgUFAgQ0EgdjMwHhcNMTgwMjE2MDgwMjUyWhcNMjAw
MjE3MDgwMjUyWjBeMQswCQYDVQQGEwJTRTEWMBQGA1UEAwwNRWJiZSBUZXN0c3Nv
bjERMA8GA1UEBAwIVGVzdHNzb24xDTALBgNVBCoMBEViYmUxFTATBgNVBAUTDDE5
MDEwNDIyNjM3ODCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAM3NNdLp
fEJphjXNJ3/bK7TM56wDc/7IXCSvgl5fNirG1CnPjGmSTdno3NNXfqb2PRtwfEXR
FPVw8jUsa7KhO8ND2o8Unmgo+tgrKklLZFwrQYQZ9oE3AhM1FX0luTmwFWZKJtL1
y80SRaxjLTcWpYpFYniA+xPxcOMJPWK4PoA/KoFtvi1+6yUpvSc+ITPWrDJLDOZt
BhWKXjqFehWiCSFSAR8JipyM2BgxawttH8AcMGj5fkbzLPC7n9/F4YRTVcGpX9vm
y+o8XbQku4GMV23n2q+ykhC0XjiRyN7NhfFReBBmgjHgR81ZMsZ6MS0qboQs/OTB
/YNTkY7dBLtvF9MCAwEAAaOB+jCB9zAfBgNVHSMEGDAWgBR9vkdBjANmExSqmDAQ
1KwK7c/t9jAdBgNVHQ4EFgQU/ieVlJtDgp/4VU/4xxmJDd3l2pAwDgYDVR0PAQH/
BAQDAgZAMEUGA1UdIAQ+MDwwOgYGKoVwI2MCMDAwLgYIKwYBBQUHAgEWImh0dHBz
Oi8vcmVwb3NpdG9yeS50cnVzdC50ZWxpYS5jb20wHQYDVR0lBBYwFAYIKwYBBQUH
AwQGCCsGAQUFBwMCMD8GCCsGAQUFBwEBBDMwMTAvBggrBgEFBQcwAYYjaHR0cDov
L29jc3AucHJlcHJvZC50cnVzdC50ZWxpYS5jb20wDQYJKoZIhvcNAQEFBQADggIB
AF/s4mtDzIjJns5b3YI2j9CKcbNOpVjCV9jUqZ+w5vSEsiOwZhNw6VXEnOVfANRZ
t+IDIyS5Ce9rWXqT5aUB5GDduOQL4jClLdMGPW1caOwD8f5QoBEeQCXnYvBefwYi
iCw+aa7XGpgmQD+qhWZWB4Xv4wOSilyvT40CPQAHYPlJhawtoOo7JOdSxSkaoeqQ
3XvNuCIH0xiuqJmWQGSzslIsWhv3hEYRxsD/6u1NxxOTCIJ19tXDy/IG7utxX7bb
aj3AHG+56IbvWuWODxS+KwzAvSub0vT9Uxy9hJOIPGe82DH/08Spk7FM/Q9ELlYd
wFHet7xFMyirj5kTpVwYp+qB+cN/H6y4DlrKut2j7qi859GWSMAX1a5+/UckuGHT
XwA2IvzazQws+hp8fv33eg8Oof7STepV6EYCw+Fw0xveg3OQaFip5lSpawcKnhWd
A4T2z8OvV1oR6CuokSwnFXN0bHeM4QbP6yjIQSi7J0Pmzi0DE7vU7OtenHaM3B6t
Z9ZtNyCOx6iAAOkUsVHz/O/tsVw8QEodg/OnCHwNsAPF0876ZF0nMQVYmcKYsxNj
7im9oTZFc/3VxJh4TMjJQc2H6qiM3LZHuSu309i5fkJy9CPtw8ebB5pjFvuU77Zf
yB/oqFoA/pM1/Bi/ARFBWAWVIGCo6Yp7sIQ8EkM6Of4gMYICdDCCAnACAQEwYjBP
MQswCQYDVQQGEwJTRTETMBEGA1UECgwKVGVsaWEgVGVzdDErMCkGA1UEAwwiVGVs
aWEgZS1sZWdpdGltYXRpb24gVGVzdCBQUCBDQSB2MwIPAWGdo1mULnoLNFJilUlp
MA0GCWCGSAFlAwQCAQUAoIHkMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJ
KoZIhvcNAQkFMQ8XDTE4MDQxOTEyNDQ0MlowLwYJKoZIhvcNAQkEMSIEIKHFvPWi
9uCq04rLzVviJjdfUuCni4uxivw1n7jBr3eXMHkGCSqGSIb3DQEJDzFsMGowCwYJ
YIZIAWUDBAEqMAsGCWCGSAFlAwQBFjALBglghkgBZQMEAQIwCgYIKoZIhvcNAwcw
DgYIKoZIhvcNAwICAgCAMA0GCCqGSIb3DQMCAgFAMAcGBSsOAwIHMA0GCCqGSIb3
DQMCAgEoMA0GCSqGSIb3DQEBAQUABIIBAAga2QlXM4ba8LxA9pD51cFfN8VZcSgM
BQwxNpy0y7vDWazE1M/IXPEEUUMsk6OVMLgS/Q/LCQ8nxYpZXRAkIMtnl1/L93LE
I/xa35gYFXrVp352b7evA3iDvE9O0aN4lufLGCxOiT5bJISmaaCVSVe8QFrSVSmF
SW/MkJKaFiFBWsXJJ3vQGnULlH0WIc5QnC2rpkAeEswsxgCA9VnQNclktv7gwS3G
NH2lLUbRl+tMMrrQ8Il4lEOnRG7W22tVdypVndLbeEoZe71u7bumJCc/U754SCCi
uX8CEZd55uzNPOPUPgTvWbSybh36oeMsWd21g57ZFU6FV6CNh3hGkp8=
-----END PKCS7-----
`

It verifies in OpenSSL:

`
$ openssl cms -verify -inform pem -in newtelia.pem -noverify
Verification successful
DT8lOM3pB18=Test Forlitandecertifikat0373599a61cc6b3bc02a78c34313e1737ae9cfd56b9bb24360b437d469efdf3b15Sign your esplix key
`

It fails verification in PKI.js, but verifies correctly if I change this line of code: https://github.com/PeculiarVentures/PKI.js/blob/master/src/SignedData.js#L893

**Comment by YuryStrozhevsky** [comment]
```command
openssl cms -verify -inform DER -in newtelia.p7b

Verification failure
17552:error:2E099064:CMS routines:cms_signerinfo_verify_cert:certificate verify error:crypto\cms\cms_smime.c:253:Verify error:unable to get local issuer certificate
```
Just removed `-noverify` option and decoded from BASE-64 to DER representation.

**Comment by killerstorm** [comment]
WIthout `-noverify` option it verifies not just message signature, but the whole certificate chain. For that you need Telia Test certificate. Here's it, let's call it `telia-test.pem`:

```
-----BEGIN CERTIFICATE-----
MIIFbTCCA1WgAwIBAgIQPDW4a37kVS3Qdy5I/fvbSzANBgkqhkiG9w0BAQUFADBP
MQswCQYDVQQGEwJTRTETMBEGA1UECgwKVGVsaWEgVGVzdDErMCkGA1UEAwwiVGVs
aWEgZS1sZWdpdGltYXRpb24gVGVzdCBQUCBDQSB2MzAeFw0xNDAyMjUxNDExMzFa
Fw0yNDAyMjUxNDExMzJaME8xCzAJBgNVBAYTAlNFMRMwEQYDVQQKDApUZWxpYSBU
ZXN0MSswKQYDVQQDDCJUZWxpYSBlLWxlZ2l0aW1hdGlvbiBUZXN0IFBQIENBIHYz
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA1304TUWlcSY2M0/ogtQV
GN4PT91Sz9Fr5lx/CK9rw4/sbJxVkbjhFtu/4Pd8zT1k25jSHYuEowkzJsdjLn/Z
ZEOwvyfWA8BrCord59f9DovmHSbrS7vOXSJO+//jodMyDW1XuFMDTeo+qDVLz4RX
7I3YDMZySnLHD9+kQUfG0yDnoLwi8z7YfKvsB1hv5OegJRXic60T8+koglFvKL/L
JwhG/h+sUvVLNcwDH7YCN3/Lf2VcedaSE61UUErrTcPmUKvPm790yeNei5Iumbkn
P7ssK5xDjgMhXBRLI9qOnN1gpxwUgn/il5FQrLnSgFhW0RFmC5JuFyhqbzVAdHvY
woJK87MawNvgWLvqbH3Ly2JJ5nuLb7L3i03e044seytGya+2KL6bC0186koGSpHd
RB+Q8zdsecZtMK4VnHUaLu0i7SM4IPIqE7QLT+Hjt6zvyHS81FpBtov0B8OLS8Lx
VTXoKTfrTaQMsMjB/skMMsvzCRZ007J1qD7nM1+sBJ9idJ5ucGv7WwOuspbX89vh
gOuq7rfHjXJA6mMkELMApRjtzbEtvwbcEsWewECsqhTXurXPK54PrXzONI2TXneV
xVaKg7hxrM4V5YmN8RUXC31Jcwdvi1I9kCcU/HCvCLEHlCGqR++ejK4F7dk5+O7r
MWKthYq1NBg4si0FBOM3Cw8CAwEAAaNFMEMwEgYDVR0TAQH/BAgwBgEB/wIBADAO
BgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYEFH2+R0GMA2YTFKqYMBDUrArtz+32MA0G
CSqGSIb3DQEBBQUAA4ICAQAeX06xymEaI/sWtRwDVe1kRr9bEk1lJodLQW3RxUtW
A6qjtxoLrKLlPbNzsUa6TRk0tHz2XTKbv0eYRNGtuDak5MIgCGIzSt3jHO0pbF3+
8R2PHCqtw1iRhv+zbYBsMOK+ZITN+TIw11+ZVWYI71JeGimiDyCvRZeugnpsjRly
CLbyKTWq6/jY2bShOgoFH9O0LDwXBotV+PLmKZYBgx16hhS/DXGiYLObGsQDfgnc
VGomTGDRXf8CFiPk67K+nnhd1BdKo3mXqMzPfoLIgskKPv9GHaz2MzeVHur8DNKg
ngYPVA42mDzWpF5zo8Pjn0tn8eAlo6oZcMBQTeXs0vtJYIyf2bmTi7Z2GuqPjTR1
cHCsX/QOLyZio0s0O9H5s9mRM1NrKZhxmXGG3lHSMhNkSGGgFjLeYXZXlB/eO/Iv
MwkB7U5SagHHT70303jK00m4cq936uiwFQX3tcZGaYGgYgi6m0gZg+kLwX0WrrGL
Tm05IG174sWNQue+Yu2DmPoOk3HfMwWWFSnGNBdw0HXDeHgxB5Oj/QCGy741b1Jr
nUtOQbf/7OhOezzFxE6E4xOmHbUObyWT+iYgFUmUiUdB7On6MtqSXL05wXAsxM6j
c0EekGmPIpT+luUN6aD38uEJyLx5ZTr8NHG/52GnTmAQGYGqy70PPRnYhOuYkMmJ
2Q==
-----END CERTIFICATE-----
```

Now OpenSSL can verify the entire chain:

```
$ openssl cms -verify -CAfile telia-test.pem -inform DER -in newtelia.p7b
Verification successful
DT8lOM3pB18=Test Forlitandecertifikat0373599a61cc6b3bc02a78c34313e1737ae9cfd56b9bb24360b437d469efdf3b15Sign your esplix key
```

**Comment by killerstorm** [comment]
Thanks for the fix!

**Comment by YuryStrozhevsky** [comment]
Seems the problem was introduced recently - I made a unification in signing process and removed correct algorithm usage: [https://github.com/PeculiarVentures/PKI.js/blob/5b9c35c154c48b232b45cc2a908c88e2f56a8447/src/SignedData.js#L904](https://github.com/PeculiarVentures/PKI.js/blob/5b9c35c154c48b232b45cc2a908c88e2f56a8447/src/SignedData.js#L904) and [https://github.com/PeculiarVentures/PKI.js/blob/5b9c35c154c48b232b45cc2a908c88e2f56a8447/src/SignedData.js#L976](https://github.com/PeculiarVentures/PKI.js/blob/5b9c35c154c48b232b45cc2a908c88e2f56a8447/src/SignedData.js#L976)

**Comment by YuryStrozhevsky** [comment]
This is correct - the problem was introduced recently. The [existing live example](https://pkijs.org/examples/CMSSigned_complex_example.html) verifies test data correctly. And the example uses more or less old version of PKIjs code.
