### ISSUE TITLE
SignaturAlgorithm, SignaturHashAlgorithm is always sha-1

### ISSUE THREAD

**Issue by hendrik-weiler** [PeculiarVentures/PKI.js#173]
Hello,
im trying to create a certificate which with a sha-512 hash. In the attachment below is the generated certificate. 
[example (58).zip](https://github.com/PeculiarVentures/PKI.js/files/2003877/example.58.zip)

Heres the code im using:
[pki-es6.txt](https://github.com/PeculiarVentures/PKI.js/files/2003903/pki-es6.txt)

Ive tried it with this code and it didnt work:
certificate.signature = new AlgorithmIdentifier({
    algorithmId: '1.2.840.113549.1.1.13' // SHA-512 RSA
 });
certificate.signatureAlgorithm = new AlgorithmIdentifier({
    algorithmId: '2.16.840.1.101.3.4.2.3' // SHA-512
});

With this example it works but i dont know what im doing wrong.
https://pkijs.org/examples/X509_cert_complex_example.html

**Comment by YuryStrozhevsky** [comment]
@hendrik-weiler Sorry, I do not have a time to find your errors in your code. Please do it yourself. And I do suggest you to use [this example](https://github.com/PeculiarVentures/PKI.js/tree/master/examples/CertificateComplexExample) as a template.

**Comment by rmhrisk** [comment]
My guess is that you are not changing which signature operation your using in WebCrypto and are just setting the signature OID. I’ve not tried to debug your code, just guessing based on what you have stated here.
