### ISSUE TITLE
Error after run `toJSON` method

### ISSUE THREAD

**Issue by donskov** [PeculiarVentures/PKI.js#176]
Certificate - https://crt.sh/?q=602d13a00e1970a84a5cb333a7523a8a0a46778d
Version - 2.1.53

Example:
```javascript
  const asn1 = asn1js.fromBER(raw);
  const x509 = new Certificate({ schema: asn1.result });
  const json = x509.toJSON();
```

After this I have error:
![image](https://user-images.githubusercontent.com/9417251/40299458-faaca226-5cee-11e8-8c7f-73e4578d3197.png)

I think trouble in `1.3.6.1.4.1.11129.2.4.2` extension parse

**Comment by YuryStrozhevsky** [comment]
Fixed.
