### ISSUE TITLE
Strange use of const within PKIJS EnvelopedData.js

### ISSUE THREAD

**Issue by jk89** [PeculiarVentures/PKI.js#181]
[This is the file in question, the function I am interest in is the encrypt method on the default exported class](https://github.com/PeculiarVentures/PKI.js/blob/master/src/EnvelopedData.js)

So on line 661 it defines a variable ivView which is a Uint8Array from a buffer 16 bytes long. On line 662 it calls getRandomValues with the ivView. Now I presume the intention was to populate the ivView with random data, however with it being defined as a constant means it does not change after invoking getRandomValues on **NodeJS** (works fine chrome using webcrypto api) I can confirm this by stepping through breakpoints in the code all bytes have 0 value which is the same as when the ivView was initialised. I realise const is not really to do with immutability but in fact about creating an immutable binding, however stepping through the code demonstraights that the iv remains all zeros and hence has no entropy.

Is this a bug? Or is there intended behaviour which I have not understood?

The nodejs getRandomValues is defined like in the examples:
`const crypto = require("crypto");
const WebCrypto = require('node-webcrypto-ossl');

module.exports = {};

module.exports.getRandomValues = function(length) {
    return (new Uint8Array(crypto.randomBytes(length)));
}`

However this did not work, I was getting errors like "Uncaught TypeError: size must be a number >= 0"

So I changed it to the following:
`const crypto = require("crypto");
const WebCrypto = require('node-webcrypto-ossl');

module.exports = {};

module.exports.getRandomValues = function(length) {
    length = (new Uint8Array(crypto.randomBytes(length.length)));
}`

I then changed the const to a let

**Comment by YuryStrozhevsky** [comment]
Smart enough to close, congratulations :)
