### ISSUE TITLE
Should a root certificate authority be able to publish a CRL?

### ISSUE THREAD

**Issue by jk89** [PeculiarVentures/PKI.js#182]
Here is my procedure:

I create a root pair, create a self signed cert. I then create a new key pair, and get the root to create a certificate for it. I then create a CRL with the new pairs cert and then try to verify the new certificate like in the examples: verifyCertificate(newPairCertificate,[rootCertificate,newPairCertificate],[rootCertificate],[crl])

[Looking at the CertificateChainValidationEngine file line 572](https://github.com/PeculiarVentures/PKI.js/blob/master/src/CertificateChainValidationEngine.js)

With the path length being 2 in this case, the escape condition is reached immediately therefore it does not proceed with validating the given roots crl. If i modify line from this:

`for(let i = 0; i < (path.length - 2); i++)` 

to this:

`for(let i = 0; i <= (path.length - 2); i++)`

then it does validate the certificate being on the crl and rejects the certificate.

So my question is, is this deliberate (am I abusing the notion of crl and maybe a root should never publish a crl)?

**Comment by YuryStrozhevsky** [comment]
@jk89 In fact what you saw is not because "root can not issue CRL". It is because check for your `end-user certifciate` was omitted. I checked - it is a bug exists since very first version of PKIjs. So, thanks for the bug report, that one was useful ;) Fixed in 2.1.61.
