### ISSUE TITLE
SMIMEEncryptionExample not working

### ISSUE THREAD

**Issue by msdev15** [PeculiarVentures/PKI.js#187]
There are References to non exiting files in SMIMEEncryptionExample.html:

    <script type="application/javascript" src="../../node_modules/babel-polyfill/dist/polyfill.js"></script>
    <script type="text/javascript" src="bundle.js"></script>

**Comment by rmhrisk** [comment]
Did you install dependencies and compile the sample?

**Comment by YuryStrozhevsky** [comment]
Run this inside PKIjs root folder in order to build all examples:
```console
npm run build:examples
```

Run this in order to build only specific example:
```console
cd examples/SMIMEEncryptionExample
npm run build
```
