### ISSUE TITLE
npm run test:node fails as ` test/s_*.js` is missing

### ISSUE THREAD

**Issue by mikemaccana** [PeculiarVentures/PKI.js#189]
$ npm run test:node

    > pkijs@2.1.67 test:node C:\Users\mikem\OneDrive\Documents\PKI.js
    > cross-env NODE_ENV=test nyc mocha --timeout 40000 --require babel-register test/s_*.js && cross-env NODE_ENV=test nyc --clean=false mocha --timeout 40000 --require babel-register test/n_*.js

    Warning: Could not find any test files matching pattern: test/s_*.js
    No test files found

**Comment by YuryStrozhevsky** [comment]
```console
npn run build:tests
```

**Comment by YuryStrozhevsky** [comment]
Checked - maybe I missed the info in README? [**NO, I DID NOT**](https://github.com/PeculiarVentures/PKI.js#tests-using-node-environment).

**Comment by mikemaccana** [comment]
Instructions to run `npm run test:node` come from PKIJS when running `npm run test`., 
    $ npm run test

    > pkijs@2.1.67 test C:\Users\mikem\OneDrive\Documents\PKI.js
    > node -e "console.log('\nWARNING: !!! in order to test PKIjs in Node environment you\nwould need to install additional package node-webcrypto-ossl !!!\n\nThe node-webcrypto-ossl is not referenced in PKIjs dependencies\nanymore because we were noticed users have a problems with\nthe package installation, especially on Windows platform.\n\nThe node-webcrypto-ossl is NOT a mandatory for testing PKIjs -\nyou could visit test/browser subdir and run all the same tests\nin your favorite browser.\n\nAlso you could check CircleCI - for each build the service runs\nall tests and results could be easily observed.\n\nIf you do need to run PKIjs tests locally using Node please use\nnpm run test:node')"

    WARNING: !!! in order to test PKIjs in Node environment you
    would need to install additional package node-webcrypto-ossl !!!

    The node-webcrypto-ossl is not referenced in PKIjs dependencies
    anymore because we were noticed users have a problems with
    the package installation, especially on Windows platform.

    The node-webcrypto-ossl is NOT a mandatory for testing PKIjs -
    you could visit test/browser subdir and run all the same tests
    in your favorite browser.

    Also you could check CircleCI - for each build the service runs
    all tests and results could be easily observed.

    If you do need to run PKIjs tests locally using Node please use
    npm run test:node


There is no mention of `npn run build:tests`. It would be good to add one.

**Comment by YuryStrozhevsky** [comment]
Please read README (at least) before any further steps. I do not like to prevent from any "monkey testing" user could try on PKIjs.

**Comment by mikemaccana** [comment]
You could just make the message `npm run test` clearer. Most packages on npm have `npm run test` do something, whereas very few have specific instructions to make the tests work. 🙂

**Comment by YuryStrozhevsky** [comment]
Cause you do not want to learn PKI.js I decided to explain some details.

So, in PKI.js there are **no tests, at all**. Instead there are only examples written using pure ES6 code. The same code under `examples` is using for these purposes:
* Examples for both ES5 and pure ES6 (examples work in browser only);
* Tests using Node.js + Mocha;
* Tests using browser + Mocha;

At the moment Node.js has no ability to use `import` directive. Thus in order to make any tests for Node.js + Mocha user need to build test code first.

**Comment by mikemaccana** [comment]
I want to learn, I just think you could make it clearer. I'm sure there will be other users to try `npm run test`. Yury I appreciate your work, I'm making a small suggestion that might be useful for other people and save you explaining this in future, out of good intentions, nothing more.
