### ISSUE TITLE
Security vulnerabilities from dependent packages (via npm audit)

### ISSUE THREAD

**Issue by mikemaccana** [PeculiarVentures/PKI.js#190]
Would update and send a PR but I can't see if it breaks anything due to #189

    $ npm audit

                        === npm audit security report ===

    # Run  npm install --save-dev mocha@5.2.0  to resolve 2 vulnerabilities
    SEMVER WARNING: Recommended action is a potentially breaking change

    Low             Regular Expression Denial of Service

    Package         debug

    Dependency of   mocha [dev]

    Path            mocha > debug

    More info       https://nodesecurity.io/advisories/534

    Critical        Command Injection

    Package         growl

    Dependency of   mocha [dev]

    Path            mocha > growl

    More info       https://nodesecurity.io/advisories/146

                                    Manual Review
                Some vulnerabilities require your attention to resolve

            Visit https://go.npm.me/audit-guide for additional guidance

    Moderate        Regular Expression Denial of Service

    Package         semver

    Patched in      >=4.3.2

    Dependency of   rollup-plugin-node-builtins [dev]

    Path            rollup-plugin-node-builtins > browserify-fs > levelup >
                    semver

    More info       https://nodesecurity.io/advisories/31

    Moderate        Memory Exposure

    Package         bl

    Patched in      >=0.9.5 <1.0.0 || >=1.0.1

    Dependency of   rollup-plugin-node-builtins [dev]

    Path            rollup-plugin-node-builtins > browserify-fs > levelup > bl

    More info       https://nodesecurity.io/advisories/596

    found 4 vulnerabilities (1 low, 2 moderate, 1 critical) in 6467 scanned packages
    2 vulnerabilities require semver-major dependency updates.
    2 vulnerabilities require manual review. See the full report for details.    $ npm audit

                        === npm audit security report ===

    # Run  npm install --save-dev mocha@5.2.0  to resolve 2 vulnerabilities
    SEMVER WARNING: Recommended action is a potentially breaking change

    Low             Regular Expression Denial of Service

    Package         debug

    Dependency of   mocha [dev]

    Path            mocha > debug

    More info       https://nodesecurity.io/advisories/534

    Critical        Command Injection

    Package         growl

    Dependency of   mocha [dev]

    Path            mocha > growl

    More info       https://nodesecurity.io/advisories/146

                                    Manual Review
                Some vulnerabilities require your attention to resolve

            Visit https://go.npm.me/audit-guide for additional guidance

    Moderate        Regular Expression Denial of Service

    Package         semver

    Patched in      >=4.3.2

    Dependency of   rollup-plugin-node-builtins [dev]

    Path            rollup-plugin-node-builtins > browserify-fs > levelup >
                    semver

    More info       https://nodesecurity.io/advisories/31

    Moderate        Memory Exposure

    Package         bl

    Patched in      >=0.9.5 <1.0.0 || >=1.0.1

    Dependency of   rollup-plugin-node-builtins [dev]

    Path            rollup-plugin-node-builtins > browserify-fs > levelup > bl

    More info       https://nodesecurity.io/advisories/596

    found 4 vulnerabilities (1 low, 2 moderate, 1 critical) in 6467 scanned packages
    2 vulnerabilities require semver-major dependency updates.
    2 vulnerabilities require manual review. See the full report for details.

**Comment by mikemaccana** [comment]
Did you fix it? The issue is just closed without comments.

**Comment by YuryStrozhevsky** [comment]
No, I just close your issue I I used to do (you know that, Mike).

**Comment by mikemaccana** [comment]
No, I don't know why - have you worked on OSS projects before? Normally if you've fixed something you'd commit it with `Update dependencies for npm audit (fixes #190)` or if there's a reason to leave it vulnerable, mention it in the issue.
