### ISSUE TITLE
Move to ES8 / remove unnecessary Promise.resolve().then()s?

### ISSUE THREAD

**Issue by mikemaccana** [PeculiarVentures/PKI.js#191]
This code has a lot of a `Promise.resolve().then()`. This is basically a [longer way of running `setImmediate`](https://stackoverflow.com/questions/27647742/promise-resolve-then-vs-setimmediate-vs-nexttick) - which [runs the code on the next run of the event loop](https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate).

However I'm don't actually see anywhere where this is required. So rather than refactor to setImmediate, it might be simpler to remove 

 - All the `Promise.resolve().then()`s
 - All other `then()`s

In favour of direct style, ie async/await. That way async functions return Promises, and the code waits (asynchronously) until the Promise has a value.

ie

    (async function(){
        var result = await doThing() 
        var otherResult = await doOtherThing() 
    })

This will raise the minimum required version of node to node version 8, but as the project already requires node version 6, this isn't a huge leap.

**Comment by YuryStrozhevsky** [comment]
The code has a very long story, as well as JavaScript standard. So, even when PKIjs V2 was in development Babel had no support for `async`. That is why we have "old-school" Promises in code. In any new code we have `async`.

**Comment by mikemaccana** [comment]
I don't understand. If you're happy with having `async`  and removing the `Promise.resolve().then()` - I'm happy to submit PRs here - then why close the issue?

**Comment by YuryStrozhevsky** [comment]
Because it would be a huge changes and those changes do not necessary at all - I would not accept it.

**Comment by mikemaccana** [comment]
So any new code you said will have async - but you won't accept PRs for old code? Is that correct?

**Comment by YuryStrozhevsky** [comment]
Yes.

**Comment by mikemaccana** [comment]
Why?

**Comment by mikemaccana** [comment]
Shrug, I cleaned https://github.com/PeculiarVentures/PKI.js/blob/master/examples/PKCS10ComplexExample/es6.js and it wasn't a big deal. But you're yelling and it doesn't look like this is a productive conversation so let's leave it for now.

**Comment by YuryStrozhevsky** [comment]
Also I should notice that PKIjs is the project having possibility to run in any envirinment, without any limitations. In any case your `async` would be transpiled into Promise.
