### ISSUE TITLE
pkijs.getCrypto() fails when node-webcrypto-ossl used to add global.crypto

### ISSUE THREAD

**Issue by mikemaccana** [PeculiarVentures/PKI.js#192]
Simple reproduction:

    const WebCrypto = require("node-webcrypto-ossl")
    global.crypto = new WebCrypto()
    const pkijs = require("pkijs")
    var result = pkijs.getCrypto()
    console.log(global.crypto.subtle)
    console.log(result)

`result` is undefined and shouldn't be. Currently we work around this by monkey patching `pkijs.getCrypto()`

**Comment by YuryStrozhevsky** [comment]
You forgot to call `setEngine` function. See examples for PKIjs.

**Comment by mikemaccana** [comment]
@YuryStrozhevsky where's an example for node? https://github.com/PeculiarVentures/PKI.js/tree/master/examples just seem to contain ES6 modules rather than showing NPM. I can't see anything in the README. I know of `setEngine` but currently I have to monkey patch `global.self = global` because `getEngine()` fails otherwise.

**Comment by YuryStrozhevsky** [comment]
Just a simple steps:
1) Go to `examples` folder;
2) Check folder starting from "Node.."

Do you see any? :)

**Comment by YuryStrozhevsky** [comment]
Also please aware that all PKIjs tests runs udner `mocha` and it requires all test to be "Node-related".

**Comment by YuryStrozhevsky** [comment]
PKIjs V2 contains only ES6 code. All other "adoptations" (from browsers or Node) are producing using external packages like Babel and Rollup.

**Comment by mikemaccana** [comment]
As mentioned, `examples\NodePKCS12Example` just seems to contain ES6 modules rather than showing NPM. The example also adds another thousand lines of code via `NodeEngine.js` and `NodeEngineNodeSpecific.js`, which seem to duplicate things that already in the `pkijs` npm package. It would be better to include a node example using `require` like node uses and the `pkijs` package you've published on npm.

**Comment by YuryStrozhevsky** [comment]
Run npm build:tests and then check tests folder. There you will get all the magic from pkijs :)
