### ISSUE TITLE
Make something like pkijs.OIDS instead of magic numbers 

### ISSUE THREAD

**Issue by mikemaccana** [PeculiarVentures/PKI.js#194]
Currently there's a lot of magic numbers with comments:

    // subjectAltNames
    "2.5.29.17"

It will make the code shorter and more readable to make a reusable set of named OIDs:

    pkijs.OIDS = {
      rsadsi: "1.2.840.113549", 
      subjectKeyIdentifier: "2.5.29.14",
      subjectAltNames: "2.5.29.17",
      organizationName: "2.5.4.10", 
      country: "2.5.4.6", 
      state: "2.5.4.8",
      locality: "2.5.4.7", 
      extensionRequest: "1.2.840.113549.1.9.14",
      commonName: "2.5.4.3" 
    }

**Comment by YuryStrozhevsky** [comment]
PKIjs is a library with a support for PKI. And anyone using PKIjs would need to know PKI :) Also your proposal would not change anything - users very rare need to use OIDs and with your proposal it would be necessary not to know OIDs, but your "simplified names" :) I do not agree to have this additional "obfucation level".

**Comment by YuryStrozhevsky** [comment]
Sure, you could have your own opinion.
