### ISSUE TITLE
create csr using pkcs#11

### ISSUE THREAD

**Issue by PouriaN** [PeculiarVentures/PKI.js#198]
Hi
I want to create CSR using crypto token(pkcs#11)
Do you implement a solution to accomplish this task?  or I must customize library to achieve this

**Comment by YuryStrozhevsky** [comment]
There are a number of libs made in scope of PeculiarVentures repository working with PKCS#11 tokens: [link](https://github.com/PeculiarVentures/graphene), [link](https://github.com/PeculiarVentures/pkcs11js), [link](https://github.com/PeculiarVentures/node-webcrypto-p11), [link](https://github.com/PeculiarVentures/pvpkcs11), [link](https://github.com/PeculiarVentures/graphene-cli), [link](https://github.com/PeculiarVentures/pkcs11test), [link](https://github.com/PeculiarVentures/webcrypto-local).

As for a kind of "already prepared example" - no, we do not provide it.

**Comment by rmhrisk** [comment]
If you want to do this within the browser see fortifyapp.com
