### ISSUE TITLE
Ocsp request

### ISSUE THREAD

**Issue by osecall** [PeculiarVentures/PKI.js#202]
Im trying to do a ocsp request but im not sure what paremeters are required.

Serial number has to be passed as hex or sha1 of the hex value?

Thank you very much 

The key identifier and name of issuer in sha1 of the hex value?

**Comment by rmhrisk** [comment]
https://pkijs.org/examples/OCSP_req_complex_example.html

**Comment by osecall** [comment]
var ocspRequest = new pkijs.OCSPRequest();
			

			//region Put static variables
			ocspRequest.tbsRequest.requestorName = new GeneralName({
				type: 4,
				value: new RelativeDistinguishedNames({
					typesAndValues: [
						new AttributeTypeAndValue({
							type: "2.5.4.6", // Country name
							value: new asn1js.PrintableString({ value: "ES" })
						}),
						new AttributeTypeAndValue({
							type: "2.5.4.3", // Common name
							value: new asn1js.BmpString({ value: "Test" })
						})
					]
				})
			});
	


			ocspRequest.tbsRequest.requestList = [new pkijs.Request({
			  reqCert: new pkijs.CertID({
				hashAlgorithm: new pkijs.AlgorithmIdentifier({
				  algorithmId: '1.3.14.3.2.26' // SHA-1
				}),
				issuerNameHash: new asn1js.OctetString({ valueHex: issuerNameHash }),
				issuerKeyHash: new asn1js.OctetString({ valueHex: authorityKeyIdentifier }),
				serialNumber: new asn1js.Integer({ valueHex: serialNumberValue })
			  })
			})]
			

			
			const fictionBuffer = new ArrayBuffer(4);		
			ocspRequest.tbsRequest.requestExtensions = [
				new Extension({
					extnID: "1.3.6.1.5.5.7.48.1.2", // ocspNonce
					extnValue: (new asn1js.OctetString({ valueHex: fictionBuffer })).toBER(false)
				})
			];

			const ocspRequestData = ocspRequest.toSchema(true).toBER(false);
			console.log('ocspRequestData', Buffer.from(new Uint8Array(ocspRequestData)).toString('base64')) ; 
			console.log(ocspRequestData);	







I get this error:
Error: invalid array length

**Comment by YuryStrozhevsky** [comment]
Why in your code for some variables you have namespace pkijs but for some not?

**Comment by osecall** [comment]
Thank you very much. The last question is if you implement any class or method to do the OCSPrequest to the server. I see it's created the request but not send it to the OCSP server (URL).

Thank you very much.

**Comment by YuryStrozhevsky** [comment]
Pkijs is only about making and parsing data, nothing more. Sending data is up to a higher application.
