### ISSUE TITLE
getCrypto Test in Examples Does Not Prevent Associated Errors

### ISSUE THREAD

**Issue by koolsys** [PeculiarVentures/PKI.js#204]
Within the examples calls to getCrypto in a browser environment where window.crypto.subtle is undefined, getCrypto does not return undefined. Since all functions and methods in the examples which use crypto depend on a functioning subtle I think this may be a bug.

One solution is to add a call to `setEngine` near the beginning of es6.js files which looks like this:

```javascript
if ((window === undefined)
        || (window.crypto === undefined)
        || (window.crypto.subtle === undefined)) {
    
    let loccrypto = null;
    
    setEngine("NullEngine", loccrypto, null);
} 
```

The other is to add a test after calls to `getCrypto` which tests for a working subtle method of the returned object.

Finally it would be possible to change `getCrypto` in common.js to this:

```javascript
export function getCrypto()^M
{^M
        const _engine = getEngine();^M
^M
        if((_engine.subtle === null)^M
        || (_engine.subtle === undefined))^M
                return undefined;^M
        if((_engine.subtle.subtle === null)^M
        || (_engine.subtle.subtle === undefined))^M
                return undefined;^M
^M
        return _engine.subtle;^M
}^M
```

**Comment by koolsys** [comment]
For the ladder example code I removed the carriage return that's printed to the terminal I work on.

```javascript
export function getCrypto()
{
        const _engine = getEngine();

        if((_engine.subtle === null)
        || (_engine.subtle === undefined))
                return undefined;
        if((_engine.subtle.subtle === null)
        || (_engine.subtle.subtle === undefined))
                return undefined;

        return _engine.subtle;
}
```

**Comment by YuryStrozhevsky** [comment]
@koolsys Thanks for the notice, the problem fixed in latest commit.
