### ISSUE TITLE
Example Test for Type Certificate or Key After ASN.1 decode.

### ISSUE THREAD

**Issue by koolsys** [PeculiarVentures/PKI.js#205]
I currently don't know of any code to test if an ASN.1 parsed structure for a type before calling the appropriate function to decode it. This combined with the calls to create PrivateKey or Certificate objects hault the script if there's a decoding error make unlikely to prevent misuse of the code, or to warn users if they've provided invalid Keys, Certificates, or wrong types.

This is an enhancement request.

**Comment by rmhrisk** [comment]
@koolsys It also sounds like this is a question, specifically:

`Is there a way for me to tell what type of ASN.1 object something is without decoding it?"

If so, usually you know this because of the application context, e.g. this is an S/MIME message and I know that when there is a p7s it is a CMS SignedData.

If this is not the question/problem can you elaborate on a specific use case?

**Comment by koolsys** [comment]
Yes, exactly your example question at the end there. It would also make a side benefit of being able to receive an ASN.1 ArrayBuffer from an unknown source and be able to process it. An other reason for it is to prevent unintentional contamination form user supplied data.

A good example would be, lets say a SMIME client is used, and someone receives an email with the right headers, and a valid ASN.1 part, but the part is actually a private key, or something that isn't what the context claims it is at all.

I'd like to see if there's a way to prevent calling an invalid class on the ASN.1 in a case like this. Or, if there's a way to prevent the javascript code from failing and handle it as an error instead.

**Comment by koolsys** [comment]
It does make sense, and if someone were to parse the object it might as well be decoded in the process. My apologies. I just realized I can wrap calls like `new Certificate({schema: asn1.result})` into something like this:

```javascript
try {
   certtoadd = new Certificate({schema: asn1.result});
}
catch (e) {
    alert (e.name + " " + e.message);
    return null;
}
```
try-catch doesn't exist in the examples for these classes so I didn't realize it was possible to do. Sorry to bother you on this one.

**Comment by rmhrisk** [comment]
No problem we are here to help.

**Comment by YuryStrozhevsky** [comment]
@koolsys Also you could use this "exotic" way without an exception:
```javascript
switch(true)
{
	case (asn1js.compareSchema(asn1.result, asn1.result, Certificate.schema()).verified):
		console.log("It is a certificate");
		break;
	case (asn1js.compareSchema(asn1.result, asn1.result, CertificateRevocationList.schema()).verified):
		console.log("It is a CRL");
		break;
	default:
		console.log("It is something else");
}
```
