### ISSUE TITLE
Can i generate a p7s file?

### ISSUE THREAD

**Issue by Megale** [PeculiarVentures/PKI.js#207]
Hi!

Given that i can access the certificate from a smart card, and that i can sign a document, is there anyway i can generate a p7s file with this library?

Cheers!

**Comment by YuryStrozhevsky** [comment]
@Megale All examples are under [**examples**](https://github.com/PeculiarVentures/PKI.js/tree/master/examples) folder. Also there are [**live examples**](http://pkijs.org/#examples). 

You could be interested in [**CMSSignedComplexExample**](https://github.com/PeculiarVentures/PKI.js/tree/master/examples/CMSSignedComplexExample) - this is an example on how to sign a document. As for smart card you need to use other libs - PKIjs works only with WebCrypto API which has no access to physical equipment like smartcards.

**Comment by rmhrisk** [comment]
To use a smart card see fortifyapp.com
