### ISSUE TITLE
Cannot setEngine from NodeJS

### ISSUE THREAD

**Issue by microshine** [PeculiarVentures/PKI.js#210]
I'm using PKIjs with node-webcrypto-ossl and got error on PKIjs crypto usage after setEngine

```
Please call "setEngine" before call to "getEngine"

      18 |     }
      19 | 
    > 20 |     return this.cert.getPublicKey({
         |                      ^
      21 |       algorithm: {
      22 |         algorithm,
      23 |         usages: keyUsages,

      at getEngine (node_modules/pkijs/src/common.js:86:10)
      at Certificate.getPublicKey (node_modules/pkijs/src/Certificate.js:533:10)
```

I found that `setEngine` from PKIjs cannot detect that NodeJS is running, because `window` object is not empty.

https://github.com/PeculiarVentures/PKI.js/blob/master/src/common.js#L17

Here is example of how UMD module checks for NodeJs

```js
if (typeof module === "object" && typeof module.exports === "object") {
```

**Comment by rmhrisk** [comment]
Please do a PR for this change.

**Comment by YuryStrozhevsky** [comment]
There is a long-long story on checking "Node or browser". And, in fact, there is not best solution here. But since you claims on having `window` object I do suggest you to test [**solution in this answer**](https://stackoverflow.com/a/31090240/4974178). In short here it is:
```javascript
var isBrowser=new Function("try {return this===window;}catch(e){ return false;}");

// tests if global scope is binded to window
if(isBrowser()) console.log("running under browser");
```
If it would work for you I can append it into PKI.js internal functions.

**Comment by microshine** [comment]
@YuryStrozhevsky I've added `isBrowser` code to my project. It prints `running under browser` message on app running

**Comment by YuryStrozhevsky** [comment]
I made a fix for your particular problem: if fact it was because of inconsistent conditiona between `setEngine` and `getEngine`. But, as I said, there are no best solution here (yet, at least). I will continue think on the problem.

**Comment by microshine** [comment]
@YuryStrozhevsky thank you. It works
