### ISSUE TITLE
extracting signer information from pdf

### ISSUE THREAD

**Issue by tau1974** [PeculiarVentures/PKI.js#215]
Hi,
I’m desperately searching a method to verify a signed pdf in nodej. As far as I understand pkijs seems to do it, but I really dom’t understand how to get signer infos (name, surname ...) out of the pdf.

Can someone please point me to the right direction?

thanks a lot.

best regards

**Comment by YuryStrozhevsky** [comment]
[Working with PDF example (browser only)](https://github.com/PeculiarVentures/PKI.js/tree/master/examples/PDFExample), [Working with signed data example](https://github.com/PeculiarVentures/PKI.js/tree/master/examples/CMSSignedComplexExample)
