### ISSUE TITLE
Compute Public Key Fingerprint of a Certificate

### ISSUE THREAD

**Issue by FabianHenneke** [PeculiarVentures/PKI.js#218]
In various contexts the fingerprint of the public key in a certificate is needed, which is defined as a suitable hash function applied to the BER encoded `subjectPublicKeyInfo` in a certificate. Is it possible to access these raw bytes from an instance of `Certificate`? I have found a way, but it (ab)uses the internal fields generated by pkijs on an asn1js data structure when parsing a certificate and I would much rather have a clean and stable solution.

**Comment by YuryStrozhevsky** [comment]
In short the answer is:
```javascript
const fingerprint = await crypto.digest("SHA-1", certificate.subjectPublicKeyInfo.toSchema().toBER(false));
```
But if you wish to understand PKI.js then you do need to read [**this information**](https://github.com/PeculiarVentures/PKI.js#information-about-pkijs-internal-structure). Any PKI.js class could be deducted from related binary data, and also downgraded to binary data. Any PKI.js class.

**Comment by FabianHenneke** [comment]
Thanks!
