### ISSUE TITLE
pkcs10 import sign base64

### ISSUE THREAD

**Issue by choupachupss** [PeculiarVentures/PKI.js#222]
hi,

i try to setup a `pkcs10` (`CRS`).
`PublicKey`  are from an hardware device
`PrivateKey` are from the same hardware device, but can't be exported.

I import `publicKey` from `base64` format to `webcrypto` with `spki` format for `webcrypto` API, 
`webcrypto` object obtained import on `pkcs10` field.

So i fill all filed link to `publicKey` and `attributes`.
I can sign a `buffer`, i saw that `tbs` are buffer `pkcs10` without sign ready to be sign (tbs).

I sign tbs with the `PrivateKey` from my device.
Sign are `SHA-256` `RSASSA-PKCS1-V1_5`.

I need to import the signature to `pkcs10` field of your lib.

That my problem.

I try this

```JS
pkcs10.signatureAlgorithm =  pkijs.CertificationRequest.defaultValues("signatureAlgorithm");
pkcs10.signatureValue        =  pkijs.CertificationRequest.defaultValues("signatureValue");
				
pkcs10.signatureAlgorithm.algorithmId     =  "1.2.840.113549.1.1.11";
				
let te  = base64toDer(_signed)
pkcs10.signatureValue = new asn1js.BitString({ valueHex: te });
console.log("signature OK")
```

`signed` are the signature buffer obtained on `base64`.

`signed` have this value on `der` format `0382010100`+`XXXX`
`XXXXX` are the raw buffer, without `asn1` definition.

I export `pkcs10` on `base64` format + PEM header/footer.

But on online `pkcs10` verifier, my sign will be invalid.

I make some diff comparaison with an example on cpp.

and i notice some difference on json format

````JSON
    "signatureValue": {
        "blockName": "BitString",
        "blockLength": 261,
        "error": "",
        "warnings": [],
        "valueBeforeDecode": "0382010100XX",
        "idBlock": {
            "blockName": "identificationBlock",
            "blockLength": 1,
            "error": "",
            "warnings": [],
            "valueBeforeDecode": "",
            "isHexOnly": false,
            "valueHex": "",
            "tagClass": 1,
            "tagNumber": 3,
            "isConstructed": false
        },
        "lenBlock": {
            "blockName": "lengthBlock",
            "blockLength": 3,
            "error": "",
            "warnings": [],
            "valueBeforeDecode": "",
            "isIndefiniteForm": false,
            "longFormUsed": true,
            "length": 257
        },
        "valueBlock": {
            "blockName": "BitStringValueBlock",
            "blockLength": 257,
            "error": "",
            "warnings": [],
            "valueBeforeDecode": "",
            "isIndefiniteForm": false,
            "value": [],
            "isHexOnly": false,
            "valueHex": "XX",
            "unusedBits": 0,
            "isConstructed": false
        }
````

I try to add field on raw approach

```JS
pkcs10.signatureValue.blockLength         = 261
pkcs10.signatureValue.valueBeforeDecode   = te
					
pkcs10.signatureValue.idblock.blockLength = 1

pkcs10.signatureValue.lenBlock.blockLength  = 3
pkcs10.signatureValue.lenBlock.longFormUsed = true
pkcs10.signatureValue.lenBlock.Length       = 257
					
pkcs10.signatureValue.valueBlock.blockLength = 257
pkcs10.signatureValue.valueBlock.valueHex    = tee
```

`tee` are `let tee = base64toDer(_signed.slice(10))` avoid `0382010100`
`te` are `let te  = base64toDer(_signed)`

For the moment,i have this error
```
ca_pki.js:565 JS -- createPKCS10 :JS -- pkcs10 Error signing PKCS#10: TypeError: Cannot set property 'blockLength' of undefined
```

I make a `pcks10` export without real sign.
I make a `pkcs10` with your sample, generate `RSA` + import on `pkcs10` + sign.

I made the two case below with the same code, and it's OK.

I don't know if i use the rigth method for import on signature on `base64` format on `pkcs10`.

Best regards.

**Comment by YuryStrozhevsky** [comment]
@choupachupss Not sure I understood all you said correctly, but have you seen [**this example**](https://github.com/PeculiarVentures/PKI.js/tree/master/examples/PKCS10ComplexExample)?

**Comment by YuryStrozhevsky** [comment]
> I make some diff comparaison with an example on cpp and i notice some difference on json format

Would be better if you will post here BASE-64 data from both cases (from what you got in PKI.js plus BASE-64 data from "CPP example").

**Comment by choupachupss** [comment]
i deep dive on the [pkcs10Sample](https://github.com/PeculiarVentures/PKI.js/tree/master/examples/PKCS10ComplexExample)
 i try to [create asn1 bitstring](https://github.com/PeculiarVentures/PKI.js/blob/e659ab3e1e02e7bf54411ff9c33be6c10478d45f/examples/P7BSimpleExample/es6.js#L95)

I was inspired by the pkcs10Complexe sample, for
- generate RSA + import on pkcs10 + sign.
- create a pcks10 export without real sign, use tbs or sign with Rsa private key of hardware

i can't provide sample of base64

Same data on input

A4IBAQAM7vqXXX

The diff are from JSON conversion

```JSON
    "signatureValue": {
        "blockName": "BitString",
        "blockLength": 261,
        "error": "",
        "warnings": [],
        "valueBeforeDecode": "0382010100XX",
        "idBlock": {
            "blockName": "identificationBlock",
            "blockLength": 1,
            "error": "",
            "warnings": [],
            "valueBeforeDecode": "",
            "isHexOnly": false,
            "valueHex": "",
            "tagClass": 1,
            "tagNumber": 3,
            "isConstructed": false
        },
        "lenBlock": {
            "blockName": "lengthBlock",
            "blockLength": 3,
            "error": "",
            "warnings": [],
            "valueBeforeDecode": "",
            "isIndefiniteForm": false,
            "longFormUsed": true,
            "length": 257
        },
        "valueBlock": {
            "blockName": "BitStringValueBlock",
            "blockLength": 257,
            "error": "",
            "warnings": [],
            "valueBeforeDecode": "",
            "isIndefiniteForm": false,
            "value": [],
            "isHexOnly": false,
            "valueHex": "XX",
            "unusedBits": 0,
            "isConstructed": false
        }
```

can be resume with that difference 

pkcs10.signatureValue.blockLength         = 261
pkcs10.signatureValue.valueBeforeDecode   = te
					
pkcs10.signatureValue.idblock.blockLength = 1

pkcs10.signatureValue.lenBlock.blockLength  = 3
pkcs10.signatureValue.lenBlock.longFormUsed = true
pkcs10.signatureValue.lenBlock.Length       = 257
					
pkcs10.signatureValue.valueBlock.blockLength = 257
pkcs10.signatureValue.valueBlock.valueHex    = tee

and on base64

js crs sign part
````
Cw
YJKoZIhvcNAQEL
A4IBBg
ADggEBXX
-----END CERTIFICATE REQUEST-----
````

cpp sign part
```
DQ
YJKoZIhvcNAQEL
BQ
ADggEBXX
-----END CERTIFICATE REQUEST-----
```

The rest of the CRS is same.
part diff 
```
Cw js  / DQ cpp
same YJKoZIhvcNAQEL
A4IBBg js  / BQ cpp
same ADggEBXX 
```

hope that can help.

My question is just :

how can i import base64 signature on  pkcs10.signatureValue ?

**Comment by YuryStrozhevsky** [comment]
@choupachupss 

> The diff are from JSON conversion

So, you do not have `signatureValue` key at all?

**Comment by YuryStrozhevsky** [comment]
@choupachupss As for "how to import base64 signature": in [**this line of code**](https://github.com/PeculiarVentures/PKI.js/blob/master/src/CertificationRequest.js#L358) you can see that the signature is a BitString value and you need to pass `valueHex` having type `ArrayBuffer`. Something like this code, using [**pvutils**](https://github.com/PeculiarVentures/pvutils):
```javascript
pkcs10.signatureValue = new asn1js.BitString({ valueHex: pvutils.stringToArrayBuffer(pvutils.fromBase64(yourBase64Data))});
```

**Comment by YuryStrozhevsky** [comment]
@choupachupss But wait: seems you have already encoded `BitString` in `signed` variable - as you said it is encoded as `03820101...`. In this case you need this:
```javascript
pkcs10.signatureValue = new asn1js.RawData({ data: decodedArrayBuffer });
```

**Comment by choupachupss** [comment]
@YuryStrozhevsky 

> 
> 
> @choupachupss
> 
> > The diff are from JSON conversion
> 
> So, you do not have `signatureValue` key at all?

i have a not complete signature value, some structure are empty.

pkcs10.signatureValue.blockLength = 0
pkcs10.signatureValue.valueBeforeDecode = ""

pkcs10.signatureValue.idblock.blockLength = 0

pkcs10.signatureValue.lenBlock.blockLength = 0
pkcs10.signatureValue.lenBlock.longFormUsed = false
pkcs10.signatureValue.lenBlock.Length = 0

pkcs10.signatureValue.valueBlock.blockLength = 0
pkcs10.signatureValue.valueBlock.valueHex = tee

> ```js
> pkcs10.signatureValue = new asn1js.BitString({ valueHex: pvutils.stringToArrayBuffer(pvutils.fromBase64(yourBase64Data))});
> ```

pvutils.stringToArrayBuffer(pvutils.fromBase64(yourBase64Data))})

on 
base64toDer
```
function base64toDer(_public)
{
  const binaryDerString = window.atob(_public);
  const binaryDer = str2ab(binaryDerString);
  return binaryDer
}
```

it's not ventures library, maybe that can be a problem.


i try
```
let te  = base64toDer(_signed)
pkcs10.signatureValue = new asn1js.RawData({ data: te });
```


error 
```
JS -- createPKCS10 :TypeError: this.signatureValue.toJSON is not a function
```

When i try

```
console.log("pcks10 OK ? \n" + JSON.stringify(pkcs10.toJSON()) + "\n")
console.log("pcks10 OK toschema ? \n" + JSON.stringify(pkcs10.toSchema()) + "\n")
console.log("pcks10 OK toschema toBER? \n" + pkcs10.toSchema().toBER(false) + "\n")
```

 i will test with only venture lib

**Comment by YuryStrozhevsky** [comment]
@choupachupss 

> JS -- createPKCS10 :TypeError: this.signatureValue.toJSON is not a function

Yes, the `RawData` type has no `toJSON` function. Probably it will implement it in a future. But in fact you do not need it on practice: the JSON convertion is mostly for debug purposes. Just remove calls to `JSON.stringify` and `pkcs10.toJSON()` - then all would be fine.

**Comment by choupachupss** [comment]
yes, that work fine !
Thanks @YuryStrozhevsky 
```
Check | Result
-- | --
Debian Weak Key | PASSED - Does not use a key on our blacklist - this is good
Key Size | PASSED (2048 bits)
Signature | PASSED - CSR has a valid signature
MD5 | PASSED - Not using the MD5 algorithm
```

```
Cw
YJKoZIhvcNAQEL
A4IBAQ
AM7vqWwE4trkMrTWUPpmeu2SgkRtMzQTZx
YyESU9Nbk3MgUFq7qIV15QL5u98qiD4WQ+9
```

but the base64 have no common for CW and A4IBAQ
and the store of the signature are not the same of CPP part.


For `RawData` , no json conversion.
i think, you could just make an `toJSON` with an empty field or just the raw on hex string, like `tbs`.

**Comment by YuryStrozhevsky** [comment]
@choupachupss 

> but the base64 have no common for CW and A4IBAQ and the store of the signature are not the same of CPP part

You have a specific English and I can not really understand what you do worry about here. But anyway glad to see signature passed your major tests.

**Comment by choupachupss** [comment]
arf maybe, sorry,

I just mean, pkcs10 from CPP with the same param on
- pkcs10 attributs
- rsa public key
- signature of the buffer tbs

Don't make the same pkcs10 on final.

and i notice the change.

The cpp part use openssl, so maybe some function don't do the same as asn1 RawData.

**Comment by YuryStrozhevsky** [comment]
@choupachupss There are many different ways how to encode in ASN.1 the same data. So, without the raw data I can not say where exactly the difference is.

**Comment by choupachupss** [comment]
CPP and JS have the same data in input
buffer is the same.

i use this function on cpp from openssl
```
    OpenSSL_add_all_algorithms();
       // set as public key in X509_REQ
    ret = X509_REQ_set_pubkey(req, pkey);
req->signature = d2i_ASN1_BIT_STRING(NULL, (const unsigned char **)&pp, PublicKeydata22Length);


    //I check here both NID_sha256WithRSAEncryption NID_sha1WithRSAEncryption no problem
    req->sig_alg->algorithm = OBJ_nid2obj(NID_sha256WithRSAEncryption);   //OBJ_nid2obj(NID_sha1WithRSAEncryption);
    req->sig_alg->parameter = ASN1_TYPE_new();
    req->sig_alg->parameter->type = 0x05;
```
PublicKeydata22Length = 261
pp are "0382010100XXX"
XXX is the buffer of the signature.

**Comment by YuryStrozhevsky** [comment]
@choupachupss No, I mean I need to have BASE-64 encoded data for both cases: PKI.js and OpenSSL. I will not make the data myself :)

**Comment by choupachupss** [comment]
base64 is

```
A4IBAQAM7vqWwE4trkMrTWU...
```
... because it was the same

**Comment by YuryStrozhevsky** [comment]
But anyway, it is does not matter where the difference is. Most important that signature verified.

**Comment by choupachupss** [comment]
have you an idea of definition of bytes from 03820101?

03 is for bitstring
82 don't know
0101 = 257

**Comment by YuryStrozhevsky** [comment]
[**ASN.1 By Simple Words**](https://www.strozhevsky.com/free_docs/asn1_by_simple_words.pdf)

82 is a special encoding of length - it designate that next two bytes are the true length of value
Thus the 257 is the length of value block.
