### ISSUE TITLE
Add support (parsedValue) for Microsoft cryptography extensions

### ISSUE THREAD

**Issue by april** [PeculiarVentures/PKI.js#223]
These include the following OIDs:

[1.3.6.1.4.1.311.20.2](http://oid-info.com/get/1.3.6.1.4.1.311.20.2)
[1.3.6.1.4.1.311.21.1 ](http://oid-info.com/get/1.3.6.1.4.1.311.21.1)
[1.3.6.1.4.1.311.21.2](http://oid-info.com/get/1.3.6.1.4.1.311.21.2)
[1.3.6.1.4.1.311.21.7](http://oid-info.com/get/1.3.6.1.4.1.311.21.7)
[1.3.6.1.4.1.311.21.10](http://oid-info.com/get/1.3.6.1.4.1.311.21.10)

Although these aren't seen frequently online, they are used a ton inside large organizations and are a frequent request for support inside Certainly Something.

Thanks!

**Comment by noahwalugembe** [comment]
Can I try out this

**Comment by april** [comment]
@noahwalugembe, this requires an intimate knowledge of BER/DER encoding, as well as knowing a lot about PKI and Microsoft cryptography.

**Comment by noahwalugembe** [comment]
Can I work out it with your guidance this time . I believe I might not be the best prospect for this issue but if you give a chance I can learn quickly with out westing your time

**Comment by rmhrisk** [comment]
@april can we get example certificates with these extensions.

**Comment by april** [comment]
Sure, no problem. I’ll get you them tomorrow.

**Comment by YuryStrozhevsky** [comment]
@april Done. Also append these extension to [**Certificate Complex Example**](https://github.com/PeculiarVentures/PKI.js/tree/master/examples/CertificateComplexExample).

**Comment by april** [comment]
Wow, you're fast! Would you still like the sample certificates?

**Comment by YuryStrozhevsky** [comment]
@april Next time in such requests please add ASN1 schemes for all OIDs. Or put reference to docs/RFCs. In such case I will spend not hour but only 30 mins :) As for certs - no I don’t need any.

**Comment by april** [comment]
Can do! Thanks again for your quick work on this!

**Comment by april** [comment]
@YuryStrozhevsky, I'm getting some strange results or `1.3.6.1.4.1.311.21.1`. Regardless of which certificate I look at, it always returns `{certificateIndex: 0, keyIndex: 0}`. It does this even if the certificates clearly have different values in them.

For example, this cert:
https://censys.io/certificates/b19fa9bfdd63fbc821d9af8b36562487d7a449d61782dc2b420ba43ddd74bcf8/asn.1#308206C2308205AAA0030201020213620000002B33D24265A3DBD94300010000002B300D06092A864886F70D01010505003052310B3009060355040613025553311A3018060355040A1311496E74656C20436F72706F726174696F6E312730250603550403131E496E74656C2045787465726E616C20426173696320506F6C696379204341301E170D3138303131383136303730345A170D3230303533303130343833385A3079310B3009060355040613025553310B3009060355040813024341311430120603550407130B53616E746120436C617261311A3018060355040A1311496E74656C20436F72706F726174696F6E312B302906035504031322496E74656C2045787465726E616C2042617369632049737375696E6720434120334230820122300D06092A864886F70D01010105000382010F003082010A0282010100A5A67C18A06F7DADE742EBEBB20EA0DECFC829D38D2D3ABD6E232F95E06FF7DFF378FE08AA86D0DCFD06569246668E3ED689F3F8F2F265B2FF141F7C082CFA33601689BA8DFAC2CB9E4CBB1038EE98C9DA3A0FED3601C21186871A830FDD56431143BD497A71EDC02AD271C898BDF8A01C0C84FBCC43944B11D7B40A6B59ED9C7B784101C8D0064859E256520EDBDFBB461AE41BAE6D94D6D07ECF1F5911FC16283177885D8E4E348F980C7296785D27ED2A17CE6A17536DF62A02A6F91ABF874BEC7067F3504EBC3188FFF30731B0874751AED5AB242C9F661E51A3B30713D8AF82B24A6EED711995A378A735221088485B6AAC3EDA9A394E1EB6533E230ED70203010001A382036830820364301206092B060104018237150104050203030003302306092B060104018237150204160414478BCB7431BF91FAB995F8A6DDF5A9EFA817A892301D0603551D0E04160414639756B399F86C2D643D416AAFFFFA17889B76213081FA0603551D200481F23081EF3081EC060A2A864886F84D010501693081DD30819C06082B0601050507020230818F1E818C0049006E00740065006C00200043006F00720070006F0072006100740069006F006E002000450078007400650072006E0061006C00200042006100730069006300200050006F006C006900630079002000430065007200740069006600690063006100740065002000500072006100630074006900630065002000530074006100740065006D0065006E0074303C06082B060105050702011630687474703A2F2F7777772E696E74656C2E636F6D2F7265706F7369746F72792F706B696370732F696E6465782E68746D301906092B0601040182371402040C1E0A00530075006200430041300B0603551D0F04040302018630120603551D130101FF040830060101FF020100301F0603551D23041830168014563A6F17AB240CE5B73164B011EDDBEA23BE5EBC3081C30603551D1F0481BB3081B83081B5A081B2A081AF8651687474703A2F2F7777772E696E74656C2E636F6D2F7265706F7369746F72792F43524C2F496E74656C25323045787465726E616C2532304261736963253230506F6C69637925323043412831292E63726C865A687474703A2F2F6365727469666963617465732E696E74656C2E636F6D2F7265706F7369746F72792F43524C2F496E74656C25323045787465726E616C2532304261736963253230506F6C69637925323043412831292E63726C3081E906082B060105050701010481DC3081D9306606082B06010505073002865A687474703A2F2F7777772E696E74656C2E636F6D2F7265706F7369746F72792F6365727469666963617465732F496E74656C25323045787465726E616C2532304261736963253230506F6C69637925323043412831292E637274306F06082B060105050730028663687474703A2F2F6365727469666963617465732E696E74656C2E636F6D2F7265706F7369746F72792F6365727469666963617465732F496E74656C25323045787465726E616C2532304261736963253230506F6C69637925323043412831292E637274300D06092A864886F70D010105050003820101009DE2F5C0780BCE81E03CE5FF6CA82CAE79AD92A6F608D48A4390D3B3960674E90E81AC8E209047BD7F01774B8AA6D95644998123DA850E2D5D68997D54CF4097196731B21C25B69E14965398771AD74F6AAED4C25039053912429B5EE207425D9C9459E9662DC1F393C0D3C0B48FB5513424518B06D90A6B5B5B1151FABE8C8C63816F7E61B4A0E2E8EF0571EBD27AA0E547E654A82A07EDF4E1C1B9718792638664BA15F32EABA1AA1BCA568C4E8102C776BAF1C0055A9506AED4C07CEA3E4D0FB32917E03D174707E28187718E6A2615056DCAB15DC29BC74A4E64062F8A30BF91C7776A0DC5643D0F11475A5683D1545AD7E170F8C20E26CCA8B2BAF7BDC2

Has an integer value of 196611, and this cert:

https://censys.io/certificates/007182136c03682d9b05d699ed6ed4fb78208b98f416fde2aa03f59421998ef5/asn.1#308205E6308204CEA003020102020A6106B36600010000000C300D06092A864886F70D01010505003071310B3009060355040613025553311C301A060355040A13134265636874656C20436F72706F726174696F6E311D301B060355040B1314496E666F726D6174696F6E205365637572697479312530230603550403131C4265636874656C2045787465726E616C20506F6C6963792043412032301E170D3135303432323131353932385A170D3231303231323139303935345A308186310B3009060355040613025553311630140603550407130D53616E204672616E636973636F311C301A060355040A13134265636874656C20436F72706F726174696F6E311D301B060355040B1314496E666F726D6174696F6E20536563757269747931223020060355040313194945585443412D534D494D452E696265636874656C2E636F6D30820122300D06092A864886F70D01010105000382010F003082010A0282010100DF329347232BC0787D76633A126AE01AD800FB37BFD2F080A4D90DEF1FFCC9A0DA02F0EE307F66554AB1E269E8CB2C970920B6B094AF236F7CDFEDFB5EC309FDF48D7AFCAA8A17C4AA760490671EDAECBD76EB7B64802D2EA494CD8ECABD10FC5992D233C42C185B957240BF5CF02FA730BC68E12E69E7DD6B0C4F5876091E8D2C057BEC92B9ECD2B4D0905348AC47454F5292DBF9DDF80F5105A084A2589B55AD5F5756FBDA23F0E460D0043D96B513A5D700B442C49F0221D9CCC9A72C7491AFFD1E929F1AD2E38870BE7A533A075DC21B53DF67668997AF1CB3059958B262D7BE1E9CDDDDB37AF40A5735AD871CD604E5BB4E24E43F1A3E2A57FE6C93FA310203010001A382026830820264300B0603551D0F040403020186301206092B060104018237150104050203020002302306092B060104018237150204160414ACC6C4061C8990C6A82B1C06FE83541F9C27A082301D0603551D0E04160414F6613C315F6296902DE4886C6879D0EC948F525A30250603551D20041E301C300C060A2B06010401FD52020501300C060A2B06010401FD52020502301906092B0601040182371402040C1E0A0053007500620043004130120603551D130101FF040830060101FF020100301F0603551D230418301680143AF9A5A0BFF863926EAEC49677C151665E06BD0930610603551D1F045A30583056A054A0528650687474703A2F2F63657274617574682E6265636874656C2E636F6D2F43657274446174612F4265636874656C25323045787465726E616C253230506F6C6963792532304341253230322831292E63726C307706082B06010505070101046B3069306706082B06010505073002865B687474703A2F2F63657274617574682E6265636874656C2E636F6D2F43657274446174612F706F6C657874636130325F4265636874656C25323045787465726E616C253230506F6C6963792532304341253230322831292E637274305D06092B060104018237150A0450304E300A06082B06010505070304300A06082B06010505070309300B06092B0601040182371505300B06092B0601040182371506300C060A2B06010401FD52020305300C060A2B06010401FD52020306304B0603551D250444304206082B0601050507030406082B0601050507030906092B060104018237150506092B0601040182371506060A2B06010401FD52020305060A2B06010401FD52020306300D06092A864886F70D01010505000382010100808060FFD2828ED7711DADDC99828B1793F40DF98464136343DBE4934E711BEB7850EDCA3F67EDCC70F666AE355B4034C730C3BD82AF25BCB6A9C66DBFA91DBE750AD474F700FFD1DB94155B1A1BD0CBDB36E15F51747C4FAA1C558632B3755FC94F87952966CC494C45754164636252553A8C3743D91D1E4AC882ACF549E6A2ABF85121B33C1EBC79E0A1EA00F5327A8D0612631D09AE3C68BDB62B47EDB69D43BD363156822CAB30C01620F050D458D4EB0EF901994889C65BE783C3BAA575DC19B3F2F9C45F2127CC028ABD1A37E3661C7A9C6F5DA33D8CF4523F292BCA5E26BC4F8AB73C0229CDFBD57A5676CAA4D67ECEA468F7146F1EDDBF423633D2D5

Has an integer value of 131074.

But they both return the same output in the JSON of 0 and 0. Lemme know if you'd like me to open up a separate bug for this. Thanks!

**Comment by YuryStrozhevsky** [comment]
@april It is because in these certificate there is incorrectly formatted `caVersion` extension: in [**this document**](https://docs.microsoft.com/en-us/windows/desktop/seccrypto/certification-authority-renewal) it is clearlt stated that there should be 32 bits (4 bytes), but in the specified certificates only 24 bits (3 bytes). Anyway, since Windows shows these certificate correctly I made a "hack/fix" for the new issue - now these certificates would be parsed correctly.
