### ISSUE TITLE
Convert certificate to PEM OR verify certificate chain help

### ISSUE THREAD

**Issue by kate1012** [PeculiarVentures/PKI.js#225]
I had some code done verifying a certificate chain from certificates in PEM format. I would like to keep that piece of code if possible, and use the certificates retrieved from the SignedData and convert them to PKCS7 PEM format. Is that possible? If not, can someone please give me a simple example on how I could take those certificates and verify them against the root certificate? I'm looking through the examples but am having some difficulty understanding. Thanks!

**Comment by rmhrisk** [comment]
SignedData a message type in actually [PKCS7](https://tools.ietf.org/html/rfc2315) or [CMS](https://tools.ietf.org/html/rfc5652).

It sounds like you want to create a .p7b (application/x-pkcs7-certificates). e.g. a PKCS7/CMS that contains just certs.

The ASN.1 for this looks like:
```
   SignedData ::= SEQUENCE {
     version Version,
     digestAlgorithms DigestAlgorithmIdentifiers,
     contentInfo ContentInfo,
     certificates
        [0] IMPLICIT ExtendedCertificatesAndCertificates
          OPTIONAL,
     crls
       [1] IMPLICIT CertificateRevocationLists OPTIONAL,
     signerInfos SignerInfos }
```

Where the `certificates` contains the certs and nothing else is set.

You would base64 this and then add the appropriate PEM armor:

```
----BEGIN PKCS7-----
-----END PKCS7-----
 ```

This process is more-or-less what the following openssl command would do:

`openssl crl2pkcs7 -nocrl -certfile certificate.cer -out certificate.p7b`

Here is a [link that shows what such a file would look like](https://lapo.it/asn1js/#MIIFnAYJKoZIhvcNAQcCoIIFjTCCBYkCAQExADALBgkqhkiG9w0BBwGgggVvMIIFazCCA1OgAwIBAgIRAIIQz7DSQONZRGPgu2OCiwAwDQYJKoZIhvcNAQELBQAwTzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2VhcmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMTUwNjA0MTEwNDM4WhcNMzUwNjA0MTEwNDM4WjBPMQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJuZXQgU2VjdXJpdHkgUmVzZWFyY2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBYMTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAK3oJHP0FDfzm54rVygch77ct984kIxuPOZXoHj3dcKi_vVqbvYATyjb3miGbESTtrFj_RQSa78f0uoxmyF-0TM8ukj13Xnfs7j_EvEhmkvBioZxaUpmZmyPfjxwv60pIgbz5MDmgK7iS4-3mX6UA5_TR5d8mUgjU-g4rk8Kb4Mu0UlXjIB0ttov0DiNewNwIRt18jA8-o-u3dpjq-sWT8KOEUt-zwvo_7V3LvSye0rgTBIlDHCNAymg4VMk7BPZ7hm_ELNKjD-Jo2FR3qyHB5T0Y3HsLuJvW5iB4YlcNHlsdu87kGJ55tukmi8mxdAQ4Q7e2RCOFvu396j3x-UCB5iPNgiV5-I3lg02dZ77DnKxHZu8A_lJBdiB3QW0KtZB6awBdpUKD9jf1b0SHzUvKBds0pjBqAlkd25HN7rOrFleaJ1_ctaJxQZBKT5ZPt0m9STJEadao0xAH0ahmbWnOlFuhjuefXKnEgV4We0-UXgVCwOPjdAvBbI-e0ocS3MFEvzG6uBQE3xDk3SzynTnjh8BCNAw1FtxNrQHusEwMFxIt4I7mKZ9YIqioymCzLq9gwQbooMDQaHWBfEbwrbwqHyGO0aoSCqI3Haadr8faqU9GY_rOPNk3sgrDQoo__fb4hVC1CLQJ13hef4Y53CIrU7m2Ys6xt0nUW7_vGT1M0NPAgMBAAGjQjBAMA4GA1UdDwEB_wQEAwIBBjAPBgNVHRMBAf8EBTADAQH_MB0GA1UdDgQWBBR5tFnme7bl5AFzgAiIyBpY9umbbjANBgkqhkiG9w0BAQsFAAOCAgEAVR9YqbyyqFDQDLHYGmkgJykIrGF1XIpu-ILlaS_V9lZLubhzEFnTIZd-50xx-7LSYK05qAvqFyFWhfFQDlnrzuBZ6brJFe-GnY-EgPbk6ZGQ3BebYhtF8GaV0nxvwuo77x_Py9auJ_GpsMiu_X1-mvoiBOv_2X_qkSsisRcOj_KKNFtY2PwByVS5uCbMiogziUwthDyC3-6WVwW6LLv3xLfHTjuCvjHIInNzktHCgKQ5ORAzI4JMPJ-GslWYHb4phowim57iaztXOoJwTdwJx4nLCgdNbOhdjsnvzqvHu7UrTkXWStAmzOVyyghqpZXjFaH3pO3JLF-l-_-sKAIuvtd7u-Nxe5AW0wdeRlN8NwdCjNPElpzVmbUq4JUagEiuTDkHzsxHpFKVK7q4-63SM1N95R1NbdWhscdCb-ZAJzVcoyi3B43njTOQ5yOf-1CceWxG1bQVs5ZufpsMljq4Ui0_1lvh-wjChP4kqKOJ2qxq4RgqsahDYVvTH9w7jXbyLeiNdd8XM2w9U_t7y0Ff_9yi0GE44Za4rF2LN9d11TPAmRGunUHBcnWEvgJBQl9nJEiU0Zsnvgc_ubhPgXRR4Xq37Z0j4r7g1SgEEzwxA57demyPxgcYxn_eR44_KJ4EBs-lVDR3veyJm-kXQ99b21_-jh5Xos1AnX5iItreGCehADEA).

You can see an example of working with this sample: https://pkijs.org/examples/P7BSimpleExample.html

The source of which is here: https://github.com/PeculiarVentures/PKI.js/tree/master/examples/P7BSimpleExample

**Comment by YuryStrozhevsky** [comment]
@kate1012 In order to convert to PEM from SignedData `certificates` you need something like this:
```javascript
if("certificates" in signedData)
{
	for(const element of signedData.certificates)
	{
		let pem = formatPEM(toBase64(arrayBufferToString(element.toSchema().toBER(false))));
		pem = `-----BEGIN CERTIFICATE-----\n${pem}\n-----END CERTIFICATE-----`
	}
}
```
The `formatPEM` function you can get [**here**](https://github.com/PeculiarVentures/PKI.js/blob/master/examples/CMSSignedComplexExample/es6.js#L31), the `toBase64` and `arrayBufferToString` functions are from [**pvutils**](https://github.com/PeculiarVentures/pvutils) package.

**Comment by kate1012** [comment]
@YuryStrozhevsky  thanks that was exactly what I needed :)
