### ISSUE TITLE
Verifying intermediate and root certs

### ISSUE THREAD

**Issue by kate1012** [PeculiarVentures/PKI.js#226]
I'm trying to create a CertificateChainValidationEngine with my trustedCert as my root cert, and certs as my leaf and intermediate cert. All are in the format of pkijs.Certificate class. When I run verify on the certificate chain however, I get the error 'No valid certificate paths found' with error code -1. I cannot for the life of me figure out why, any thoughts?

**Comment by rmhrisk** [comment]
@kate1012 Have you taken a look at the https://pkijs.org/examples/X509_cert_complex_example.html?

You can find the source here: https://github.com/PeculiarVentures/PKI.js/tree/master/examples/CertificateComplexExample

You can see the calling pattern here: https://github.com/PeculiarVentures/PKI.js/blob/master/examples/CertificateComplexExample/es6.js#L479

**Comment by YuryStrozhevsky** [comment]
@kate1012 I can not say anything about your problem without having all the certificates from your chain. Certificate chaing revocation engine is very complex and has many point where your certificate path could be considered as invalid. 

Also for a correct examples of using `CertificateChainValidationEngine` you can check examples which Ryan mentioned. As for advanced usage of the class you can check [**NIST PKITS example**](https://github.com/PeculiarVentures/PKI.js/tree/master/examples/NISTPKITS) - there I implemented all tests in scope of NIST PKITS suite.

**Comment by kate1012** [comment]
Thanks, I figured out a different way to verify the chain so I'm closing this thread.
