### ISSUE TITLE
PFX - contentEncryptionAlgorithm

### ISSUE THREAD

**Issue by carcamano** [PeculiarVentures/PKI.js#227]
Hello,

Before anything, thank you all for this amazing lib :)

I'm trying parse a P12 certificate on browser before upload it to my server, but I'm getting this error:

```
Unknown "contentEncryptionAlgorithm": 1.2.840.113549.1.12.1.3
```

I have no problem until this part
```javascript
	sequence = sequence.then(
		() => pkcs12.parseInternalValues({
			password: passwordConverted,
			checkIntegrity: true,
		}),
	);
```

But when I call the code below, the error throws
```javascript
	sequence = sequence.then(
		() => pkcs12.parsedValue.authenticatedSafe.parseInternalValues({
			safeContents: [
				{
					// Empty parameters since for first "SafeContent" OpenSSL uses "no privacy" protection mode
				},
				{
					password: passwordConverted,
				},
			],
		}),
	);
```

Am I missing something? PKI.js hasn't support to 1.2.840.113549.1.12.1.3 algorithm?

Can you please point me a direction?

Thank you!

**Comment by rmhrisk** [comment]
PKIjs is based on webcrypto, that OID is for pbeWithSHAAnd3-KeyTripleDES-CBC. Webcrypto does not support 3DES.

Node doesn’t have WebCrypto so using PKIjs there requires a poly full; we did a PKCS12 sample that uses a polyfill for webcrypto that supports 3DES. You can find it here: https://github.com/PeculiarVentures/PKI.js/tree/master/examples/NodePKCS12Example

You can do the same thing in the browser using a software implementation of 3DES.

Here is a web crypto polyfill we created that  works in the browser that supports 3DES. You can use this and the node sample To make this work.

**Comment by YuryStrozhevsky** [comment]
[webcrypto-liner](https://github.com/PeculiarVentures/webcrypto-liner) and [webcrypto](https://github.com/PeculiarVentures/webcrypto)

**Comment by carcamano** [comment]
I will try to make it works :)

Thank you!
