### ISSUE TITLE
Validate signature of PDF in Nodejs

### ISSUE THREAD

**Issue by Djalmar** [PeculiarVentures/PKI.js#236]
Can you help me with an really simple example of how make the signature validation in node js, I am having problems using PDF.js in nodejs, maybe is a silly question but i need some help

**Comment by rmhrisk** [comment]
Have you seen the sample?

**Comment by Djalmar** [comment]
Yeah 
I have problems with this part, on PDFExample/es6.js

```
const view = new Uint8Array(buffer);
const pdf = new window.PDFDocument(null, view, null);
pdf.parseStartXRef();
pdf.parse();
```

It's supposed that I should use the file pdf.js included in the sample for my project or install it using npm ?
Because there is where I found the problem i have downloaded [pkijs-dist](https://github.com/mozilla/pdfjs-dist) but that library doesn't exposes those methods, there is any way you can give me an example for doing that ?

Sorry for the poor english

**Comment by rmhrisk** [comment]
If your building your own application and not using the sample then you can use whatever version of PDF.js you like but if the interfaces have changed with what the sample was written against.

The other thing is the code is ES6 so if you're using an old version of node that doesn't support ES6 that is your issue? If so you can transpile the code to ES5 but I would just upgrade.

To run the samples you want to do this:

```
npm install
npm run build:examples
```

**Comment by Djalmar** [comment]
Well I'm using ES6 in my project, but I think the main problem is PDF.js versión, really appreciate your quick answer.
