### ISSUE TITLE
how do we add key usage as an attribute in CSR

### ISSUE THREAD

**Issue by joydeeprony89** [PeculiarVentures/PKI.js#242]
I am trying to add the key usage value for below flags

```
public enum X509KeyUsageFlags
    {
        //
        // Summary:
        //     No key usage parameters.
        None = 0,
        //
        // Summary:
        //     The key can be used for encryption only.
        EncipherOnly = 1,
        //
        // Summary:
        //     The key can be used to sign a certificate revocation list (CRL).
        CrlSign = 2,
        //
        // Summary:
        //     The key can be used to sign certificates.
        KeyCertSign = 4,
        //
        // Summary:
        //     The key can be used to determine key agreement, such as a key created using the
        //     Diffie-Hellman key agreement algorithm.
        KeyAgreement = 8,
        //
        // Summary:
        //     The key can be used for data encryption.
        DataEncipherment = 16,
        //
        // Summary:
        //     The key can be used for key encryption.
        KeyEncipherment = 32,
        //
        // Summary:
        //     The key can be used for authentication.
        NonRepudiation = 64,
        //
        // Summary:
        //     The key can be used as a digital signature.
        DigitalSignature = 128,
        //
        // Summary:
        //     The key can be used for decryption only.
        DecipherOnly = 32768
    }
```

I have referred the example of https://github.com/PeculiarVentures/PKI.js/blob/master/examples/PKCS10ComplexExample/es6.js but in this example it is not adding the key usage.

I am trying something like below. Could you please guide me or is there any documentation to this.
I am trying like below code snippet for **KeyEncipherment** flag :
```
const bitArray = new ArrayBuffer(1);
const bitView = new Uint8Array(bitArray);
bitView[0] |= 0x0020; // Key usage "KeyEncipherment" flag
 extList.extensions.push( new Extension({
                extnID: '2.5.29.15',
                critical: false,
                extnValue: (new asn1js.BitString({ valueHex: bitArray })).toBER(false),
            }));
```
let me know is this the right way to add key usage.

**Comment by YuryStrozhevsky** [comment]
Yes, it is a correct way. But I bet your next question will be:
* Why I do not see it in a "CSR Decoder"?
or even
* Why I do not see it in a end-user certificate after I sent it to a CA?

So, here are my "predictive answers":
* Have no idea why any CSR decoder does not show it. Contact the CSR decoder develpers.
* Each CA has a different policies and only a small subset of extensions could be in any CSR (and then in a end-user certificate). In most case you would not be even able to put **any** extensions in your CSR - all necessary extensions would be generated directly by CA while making certificate.
