### ISSUE TITLE
`instanceof asn1js.ObjectIdentifier` returns false via browserify

### ISSUE THREAD

**Issue by april** [PeculiarVentures/PKI.js#243]
In:

https://github.com/PeculiarVentures/PKI.js/blob/master/src/PublicKeyInfo.js#L141

The check for:
`if(this.algorithm.algorithmParams instanceof asn1js.ObjectIdentifier)`

Returns true when run bare, but returns false when munged through tools like browserify. I'm still working through things with the debugger, but it's confusing as heck.

**Comment by YuryStrozhevsky** [comment]
@april I published possible fix. The issue is because you are using different ASN1js instances. Also April - please close your issues after fix confirmed.
