### ISSUE TITLE
CertificateChainValidationEngine.verify doesn't verify a chain with self-signed CA

### ISSUE THREAD

**Issue by myxious** [PeculiarVentures/PKI.js#244]
I believe that `CertificateChainValidationEngine` doesn't verify the chain correctly.
I made a simple example to demonstrate it:

[https://codesandbox.io/s/boring-ride-qngkc?fontsize=14](https://codesandbox.io/s/boring-ride-qngkc?fontsize=14)

I compared it to chain verification in `node-forge` library and in the Chrome and Mozilla browsers (with the added self-signed CA).

--------------------------------

Self-signed CA:

> -----BEGIN CERTIFICATE-----
> MIIFPjCCAyYCEQCAg3cVkborc1uVSHst5SPSMA0GCSqGSIb3DQEBCwUAMF0xHjAc
> BgkqhkiG9w0BCQEWD2luZm9AbmJjLm9yZy5raDELMAkGA1UEBhMCS0gxDDAKBgNV
> BAoTA05CQzEPMA0GA1UECxMGQmFrb25nMQ8wDQYDVQQDEwZCYWtvbmcwHhcNMTkw
> ODAyMDMzMjUxWhcNMzEwODAyMDMzMDAwWjBdMR4wHAYJKoZIhvcNAQkBFg9pbmZv
> QG5iYy5vcmcua2gxCzAJBgNVBAYTAktIMQwwCgYDVQQKEwNOQkMxDzANBgNVBAsT
> BkJha29uZzEPMA0GA1UEAxMGQmFrb25nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8A
> MIICCgKCAgEAySo1JB50OexP3iyqovXliVsoUjZrKv0vUvFcqZnPvu3ygcYn87Wf
> wYanJuebsd4/7szVjAjibsKzKs2NSlrv3Bokb3JFDTtBM5KhkcX7o7c91K8KM1L7
> befub5Kb2S3QPrj0ft7NUJdw3Xbo2fdAylotrhx4J1L+Ig3AlmbfU5LbFEbm5wb5
> VM3l5mmK7f1wwf6h3etcQNtfaSZIpIF3GhCsUfhIfLyDzcLnO43xyQaaPEywaPLa
> KoeSVc6LmCeriDd+7Ea3jdEI5zPgo5zgwYtogvWrKcQP03kNysr97v/Jr9VXlhIc
> Rn0y/OA9BTJ2ouT2yvlDUH0ObWz8iwnr1XU1bFL9FKqIUzbqO850KO8cGNyQ+26X
> SJovSJifgRor8VIdRLsWU3IT/NOCKLRsgxXjor6oHTuksp20+68CH4kgK46yBJYt
> E1SjLuB1ww0xM9mEFtMEiFdhJ9OEaItU9osFoWI/QoU4KYOiQRyJsEYkQiEFBebV
> psWVJq+QeMfQyngY43ZKDySTYSvoGTYotYlf+er4yq+A1XEVWiObybnTNLo6F5BZ
> tmD1wg1hn4MuJ2OLR8uckmXDrMXshjiMc8s41bP3tYZ3Ky8RRxxiAvo/X+0yfcwM
> yAr5ZEMZNz9iTzHBq3pGV/oP8JZ39Reo9TJYSDDWAnZhBEAM9msVOR0CAwEAATAN
> BgkqhkiG9w0BAQsFAAOCAgEAyJUc1SslEhclhHybTvaaMVX4eJ74l3l+i9KZzkCz
> EGtn2nBnENsbLu1GuUoVoEAWYfKGRCZYnaLrBzgdZ/zZYMNiP3cWmkVMHIfvs0HY
> 6NYjdA0CWfunfaw8KEjC6BaWjluNTMyqZueoOfEHyQZECqJDp39mt49q8OSaaEJG
> oAxxmP/x5i87J9+h28brfFfLtn3Tdj6ksNApjIolseMt46wvMzXapP3qPFW8zbuT
> cizdysChEn5arKtYz8E6SYlyyKbZzImBZHuqmyPkpkpKrdmnPIgAhO73j9R503uH
> +4MmoEtbhms+/K4rAc6k1UJE++TaRww4CroDUZBuiLL2UXa51ExDGQCGPAv4f8ul
> Q3coalgwtk+FQNGyjFZryJHCMz0ZfMJFrUS8UHNuggGH2F01o8fmN4/OjLxfVqVs
> tx7DBopdWnn4R4vc7Msg9j5Pm8EAdlrfFCyczjYqh7XQ/1773apfPJw0NUYOfEVR
> a14Wm0WygySbRF6sSI0x9sC8cJa08nrEMECOwVzHVl/QAKbNWv+5ZJNHWkZm/G6m
> bapKr7MDRDqHalvS9WC/WyCk/I5la+77LajIkOY4GyHbR54NIwZTjHlKrH0Pny6V
> yjEM7unQE+j5WuDU9YuqklRQuFXAOkByNOVASACApoFB1pBGdnwpLpi+mDcBex/7
> i4A=
> -----END CERTIFICATE-----

Leaf cert signed by the CA cert above:

> -----BEGIN CERTIFICATE-----
> MIIEzDCCArSgAwIBAgIRALV/+OnFeXgB3WiDB5ONoVswDQYJKoZIhvcNAQELBQAw
> XTEeMBwGCSqGSIb3DQEJARYPaW5mb0BuYmMub3JnLmtoMQswCQYDVQQGEwJLSDEM
> MAoGA1UEChMDTkJDMQ8wDQYDVQQLEwZCYWtvbmcxDzANBgNVBAMTBkJha29uZzAe
> Fw0xOTA4MDIwODI1MDFaFw0zMTA3MzEwMzMxMDFaMIGFMQswCQYDVQQGEwJLSDET
> MBEGA1UECBMKUGhub20gUGVuaDETMBEGA1UEBxMKUGhub20gUGVuaDEiMCAGA1UE
> ChMZTmF0aW9uYWwgQmFuayBvZiBDYW1ib2RpYTEUMBIGA1UECxMLRGV2ZWxvcG1l
> bnQxEjAQBgNVBAMTCTEyNy4wLjAuMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
> AQoCggEBAMUp8IJ4j8yJyrCpN18tTB7bMgu6uzyi/PLmdDvZOz9qIQoGVDtNPvKn
> GF3vTVySN9EwfHbDo4XchyBKIG5esjbaTPQOnkr4Dv1A2qvD7mZECRfoW/nG0qHc
> M128NT2Js4KJBZDJq/cYanGsp3Xz62yvdzCWJovjwbDbPq7WnDQRPlEY2TZ6j4ui
> xPetzjkuziDxOMF1EJSUhM4cw6VdVgqNiQuQXnsQ3ZK8SoSt/oiU4OLqXpp5PiEa
> mUm/KcKHnFk88VpGOyYXylK1Ktx9c1oUnbzx+giW07/vyjG7qpLnJEUL4fh84Mtb
> yCocH2+XEQvr3Duxb5a52IbEDYbSGEMCAwEAAaNeMFwwGgYDVR0RBBMwEYIJbG9j
> YWxob3N0hwR/AAABMB8GA1UdIwQYMBaAFNA5fBB0h/3gPs6Al2jJq/Tj1hvEMB0G
> A1UdDgQWBBQH8CbiMLaAicyEQ8unE5FK/SuTQzANBgkqhkiG9w0BAQsFAAOCAgEA
> sSZaS9S4gGiThvsC2rU1BR5PZMMMH64Cbsps9ok/DbnmRQ6xeYEjpI87t3e7l+b5
> UGUPL+rnpBm41u7GFAvqK+gtjpJgmwERZyF/FkeSh+VKN2ghNdojuuuVW2+KeP00
> MEUXKIwUrVbrLeXKokfYuu3g1Y4AS7MlGN6yWsETpfN16pGE282uHryxFEmt1Jdc
> Bvnq4H/GHGKURAjD54Bq69vh4bqRxnXxJp2OpNAbYLsX9Pt/wBa1BpJxmXeViVx7
> Mt402Ec4Xu1lE1ulsolq0Z6vH4GbiYu0nCw9WL2//Z8hMPKyC/FHXN0u1zImeKpd
> utS9wvL/iaAUMASGQE7BVnY6Br8wnJaVjQh72jab8bGBRvE46aQmoTsncY+hq85K
> k8TTWiFRjMIoaEM6eIG1S+7m7xE6pMiMD1rzhSzeFOPWTHKC3e5VpxRd3sSNBho6
> KBBaBwoei7FK33jpStjzfp50lZzWOvuwAALTAqjrs3xjpabcdjB+qJUiJXURkjJM
> Lg4Q2I7g2MlCCY83tHmJWrAp1WSh4ttu+MLTmLcsdNy56EQMq1Wn7BOscbgYwY+D
> g+sEfmjHQz7xSoS4hv1Cin0d+J8sJpzHBKtqYxLWorvpImzsgObCIAjX7eeE4Wkf
> 60nP6k2OTaY9V6n5EfBYC3hFFCDDaf3naPtcs3dRH3I=
> -----END CERTIFICATE-----

This certs works correctly in Google Chrome and Mozilla Firefox (with the added root CA) and also works correctly in `node-forge` library, but verification by `pkijs` tell us that it's an invalid chain.

![self-signed ca](https://user-images.githubusercontent.com/30907093/63518627-1eda4580-c4fa-11e9-8692-1a83df6e6339.jpg)

Can you help me: is this the library bug or am I using it incorrectly?

**Comment by myxious** [comment]
If it's a bug, I assume that it happens because of incorrect determining root cert by signed one.
As I understand from the code, your algorithm determine root CA by not mandatory `extentions` and inner `key identifier` field in the root certificate. (OID `2.5.29.35`).

**Comment by YuryStrozhevsky** [comment]
@myxious The PKIjs library is fully-conformant with NIST PKITS (PKI Test Suite) and RFC5280. So, from RFC5280:
```text
4.2.1.9.  Basic Constraints
...
   Conforming CAs MUST include this extension in all CA certificates
   that contain public keys used to validate digital signatures on
   certificates and MUST mark the extension as critical in such
   certificates.
...
```
I should say that any clone of `forge` has no even close support for comformant certificate chain engine. As for Chrome and Mozilla - probably they do not check certificate on `localhost` using full-featured certificate validation engine. Most probably in case of `localhost` they need only signature verification of the certificate, it is enough for them.

**Comment by myxious** [comment]
Sounds valid. I'm going to close the issue.
