### ISSUE TITLE
Question: Is there any way to verify SignedData using external certificate?

### ISSUE THREAD

**Issue by microshine** [PeculiarVentures/PKI.js#245]
I've got CMS with an empty certificate list. I've got a certificate to verify a signature.

I can't find the way to do it. 

Params for verification https://github.com/PeculiarVentures/PKI.js/blob/master/src/SignedData.js#L378-L387

**Comment by YuryStrozhevsky** [comment]
Append the certificate to SignedData “certificates” array before verification.

**Comment by microshine** [comment]
Thanks
