### ISSUE TITLE
There are a lot of warnings when opening with VS Code

### ISSUE THREAD

**Issue by xybei** [PeculiarVentures/PKI.js#248]
When I opened the PKI.js project with VS Code, eslint reported a lot of warnings.
I want to know what IDE the author is using. Is there no such problem?
Is it wrong with my configuration?
I noticed that the ASN1.js project has no warnings because there is no “eslint” in its “devDependencies”

![image](https://user-images.githubusercontent.com/21050980/64171312-f00e8880-ce84-11e9-9ff7-2af8ae3103ec.png)

**Comment by YuryStrozhevsky** [comment]
Pkijs has eslintrc.js in root dir. I am using WebStorm for development.

**Comment by xybei** [comment]
I checked these warnings and they did break some rules of eslint. Since eslint is used, are you considering eliminating these warnings? Or disable these rules in .eslintrc.js?
Thanks very much!

Here is some information about webstrom not reporting eslint warnings.
[https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000045179-ES-Lint-in-Webstorm-is-not-applying-rules-from-the-config-files](url)

**Comment by YuryStrozhevsky** [comment]
No, I don’t really care about these “warnings”. I will not fix this fictional problem.

**Comment by xybei** [comment]
It‘s a bad news!
It's a great thing to open the project without problems in the mainstream IDE. Moreover, it is not difficult to automatically fix these warnings.
:(

**Comment by xybei** [comment]
Sorry, I have solved this problem, the reason for the warning is that I put PKI.js as a subfolder under another project using ESLint.
