### ISSUE TITLE
Not able to parse Base64 certificates

### ISSUE THREAD

**Issue by binylkumar** [PeculiarVentures/PKI.js#249]
I am unable to parse Base64 encoded certificate using the example - 'https://pkijs.org/examples/X509_cert_complex_example.html'. It's throwing error

bundle.js:22943 Uncaught Error: Object's schema was not verified against input data for Certificate
    at Certificate.fromSchema (bundle.js:22943)
    at new Certificate (bundle.js:22815)
    at parseCertificate (bundle.js:25902)
    at FileReader.tempReader.onload (bundle.js:26474)

If I want to convert to specific format before parsing what are all methods are available. Not able to find any documentation where I can convert to specific format. 

Can you provide an example to convert a uploaded certificate to .DER format?

**Comment by YuryStrozhevsky** [comment]
https://github.com/PeculiarVentures/PKI.js/issues/208 - most probably you have the same

DER is a subset of ASN.1 BER rules. In order to convert to any binary format use `certificate.toSchema().toBER(false)`
