### ISSUE TITLE
Using `latest` as dependency version results in yarn warnings.

### ISSUE THREAD

**Issue by cameronhunter** [PeculiarVentures/PKI.js#250]
Depending on `latest` version results in [`yarn`](https://yarnpkg.com) warnings when installing:

```
warning Pattern ["asn1js@latest"] is trying to unpack in the same destination "/Users/cameronhunter/Library/Caches/Yarn/v4/npm-asn1js-2.0.22-add7ab817372da160bd5c51aa19247d749c3288c/node_modules/asn1js" as pattern ["asn1js@^2.0.22"]. This could result in non-deterministic behavior, skipping.
```

Could `package.json` be changed to use a semver range instead?

**Comment by YuryStrozhevsky** [comment]
@cameronhunter Not sure I understood your issue correctly. So, I assume you have a soft where you are using both ASN1js and PKIjs. And in a `package.json` you stated `asn1js: ^2.0.22`, right? And where `npm` installs PKIjs it skips `asn1js` installation because it is installed already. Is it the issue what you have?

**Comment by cameronhunter** [comment]
Yes, although they're transient dependencies of mine rather than those I depend on directly. I'm unsure if `npm` shows the warning, but in my case it's `yarn` that is showing the warning.

**Comment by YuryStrozhevsky** [comment]
So, what if you stated asn1js: latest in your package.json? Would it satisfy yarn?

**Comment by cameronhunter** [comment]
No, because the dependency on `asn1js` is transient (i.e. a dependency of a dependency).

I'm confused on the reluctance of specifying a version range in your package.json. Any of your dependencies could push a major breaking change and all users of your package would be broken on their next installation.

**Comment by YuryStrozhevsky** [comment]
Both packages are under my control thus it would not be a case.

**Comment by cameronhunter** [comment]
Are `bytestreamjs` and `pvutils` under your control too? The same issue exists with those dependencies because you're depending on `latest` too.

**Comment by YuryStrozhevsky** [comment]
Yes, those packages are under my control too. I don’t see an issue using latest. Also using version ranges didn’t prevent me from problems: previously I had issues with pkijs from a side package like Rollup even if using version range. Critical changes could be introduced in any package version, people used to made a mistakes :)

**Comment by cameronhunter** [comment]
So you're saying that your package using `latest` isn't an issue, despite me showing you that yarn warns that it could result in non-deterministic behavior.

You also completely ignored the situation of any other package depending on any of your dependencies.

This has been my worst experience with an open-source package. I'll fork to resolve this issue instead of discussing further.

**Comment by YuryStrozhevsky** [comment]
I really was trying to understand what is an issue in having latest instead of version tag. All you said that it COULD lead to problems when changes in ASN1js would affect pkijs code somehow. I said both packages are under my control and also said that using version tag is not a real solution for a POSSIBLE problems. It is only a “good practice” not to introduce major changes in minor releases, but anyone could ignore the rule.

**Comment by sachaw** [comment]
I too believe this should be fixed, what if somebody was explicitly using an old version of PKI.js and the latest release of ASN1js was incompatible, specifying the latest release compatible with the library would prevent any potential mis-configurations and the aforementioned nag, and requires little work on your behalf.

**Comment by YuryStrozhevsky** [comment]
@sachaw If you do believe that having latest is a mistake then please provide a real showcase of the error. At the moment I think there is only a “feelings” that something wrong with latest.

**Comment by derek-miller** [comment]
There are no feelings involved here. Using `latest` results in non-deterministic behavior when breaking changes are introduced to the dependencies. Yarn correctly warns about this issue, and as most of us try to heed warnings presented by our package managers, it makes sense to attempt to get this issue addressed. I am interested in your exact reasons for not addressing this (i.e why do you have to use `latest`). Of the thousands of packages we inherently depend on, the ones you control are the *only* ones with this issue.

**Comment by derek-miller** [comment]
@cameronhunter, is your fork public and available on npm?

**Comment by cameronhunter** [comment]
@derek-miller The easiest way to work around this is to use a [selective dependency resolution](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) to force a particular version.

Your `package.json` would include something like this to force all transient dependencies to use a specific version range rather than `latest`:

```json
"resolutions": {
  "**/asn1js": "^2.0.26"
}
```

**Comment by cameronhunter** [comment]
👀 https://github.com/PeculiarVentures/PKI.js/commit/e5fccb96210877abac730c542c730cd70a612a2c

**Comment by rmhrisk** [comment]
?

**Comment by cameronhunter** [comment]
I'm very happy that this issue has been fixed by https://github.com/PeculiarVentures/PKI.js/commit/e5fccb96210877abac730c542c730cd70a612a2c. Thanks to @YuryStrozhevsky for doing it.
