### ISSUE TITLE
Ensure we can decode, verify and create ed25519 certificates

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/PKI.js#257]
We can use Liner to get support for this algorithm
```
-----BEGIN CERTIFICATE-----
MIIBSDCB+6ADAgECAhR80ghysUdFKr7NLBSdOVVsEuPPuTAFBgMrZXAwEjEQMA4G
A1UEAwwHRWQyNTUxOTAeFw0yMDAxMTYwODUxNThaFw0yMTAxMTUwODUxNThaMBIx
EDAOBgNVBAMMB0VkMjU1MTkwKjAFBgMrZXADIQBziZ13v3Oqd6jsIR9j/KVOqzCP
VmlbLtfYEYNjL5p426NjMGEwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBQ0
W/US4CSVWokQkBn1+zd6SWS4qzAdBgNVHQ4EFgQUNFv1EuAklVqJEJAZ9fs3eklk
uKswDgYDVR0PAQH/BAQDAgGGMAUGAytlcANBAAvaeVIzGyXU7xH0GEg6Ru2/qJ0j
86JPBFLAHofCLqX99gVdE9GAPhP++NqQhn6KeQTQSFtnXC3DL3Zz63U6sgE=
-----END CERTIFICATE-----
```

**Comment by TJKoury** [comment]
I finally released that side project [here](https://github.com/DigitalArsenal/keymaster) that enables ed25519 certs.

**Comment by rmhrisk** [comment]
We also now support this:
https://understandingwebpki.com/?cert=MIIBSDCB%2B6ADAgECAhR80ghysUdFKr7NLBSdOVVsEuPPuTAFBgMrZXAwEjEQMA4GA1UEAwwHRWQyNTUxOTAeFw0yMDAxMTYwODUxNThaFw0yMTAxMTUwODUxNThaMBIxEDAOBgNVBAMMB0VkMjU1MTkwKjAFBgMrZXADIQBziZ13v3Oqd6jsIR9j%2FKVOqzCPVmlbLtfYEYNjL5p426NjMGEwDwYDVR0TAQH%2FBAUwAwEB%2FzAfBgNVHSMEGDAWgBQ0W%2FUS4CSVWokQkBn1%2Bzd6SWS4qzAdBgNVHQ4EFgQUNFv1EuAklVqJEJAZ9fs3eklkuKswDgYDVR0PAQH%2FBAQDAgGGMAUGAytlcANBAAvaeVIzGyXU7xH0GEg6Ru2%2FqJ0j86JPBFLAHofCLqX99gVdE9GAPhP%2B%2BNqQhn6KeQTQSFtnXC3DL3Zz63U6sgE%3D

**Comment by TJKoury** [comment]
Very nice.  Does it support secp256k1 as well?

**Comment by rmhrisk** [comment]
Yes. 

https://understandingwebpki.com/?cert=MIIBfDCCASKgAwIBAgIJAOlLpHqkoFZOMAoGCCqGSM49BAMCMBwxDDAKBgNVBAoMA0JhcjEMMAoGA1UEAwwDRm9vMB4XDTE4MDgwOTAyNTIxN1oXDTI4MDgwNjAyNTIxN1owHDEMMAoGA1UECgwDQmFyMQwwCgYDVQQDDANGb28wVjAQBgcqhkjOPQIBBgUrgQQACgNCAAQWvVJ%2BHOjfOvb14bN1O3iWUl2vXVk9WWg77TC6FGiuXkKU6%2F1URakDoTfR%2FPXU87%2BU7VozOYA4%2FSW0yQKu9W4Uo1AwTjAdBgNVHQ4EFgQUFSBA%2Bz4N%2B%2F02OMZqIUKSwi9mBCUwHwYDVR0jBBgwFoAUFSBA%2Bz4N%2B%2F02OMZqIUKSwi9mBCUwDAYDVR0TBAUwAwEB%2FzAKBggqhkjOPQQDAgNIADBFAiBr11aPIg93TJN%2Fmjv%2BWlvygFcFMMlsUlWNHSbaXQB6SAIhAKA%2BIrhEeXJe6KQQqpTPp3mnNL2icaxSHp%2FAH5Jx7L1B

@microshine can comment on if the whole chain can be in these curves or just the leaf.

**Comment by TJKoury** [comment]
That’s awesome.  I will definitely try it out.

**Comment by TJKoury** [comment]
How did you generate the certificate above?  I keep getting errors:

[link](https://understandingwebpki.com/?cert=MIICJjCCAcygAwIBAgIBATAKBggqhkjOPQQDAjAeMRwwCQYDVQQGEwJSVTAPBgNVBAMeCABUAGUAcwB0MB4XDTE5MDIwMTA1MDAwMFoXDTIyMDIwMTA1MDAwMFowHjEcMAkGA1UEBhMCUlUwDwYDVQQDHggAVABlAHMAdDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABM%2Ft5xXa6iAL8CVxEgn4FDSzSmx0TM5%2FqlrFjA0R0fGzHpEndOW0V7D0VEDnPxdd8KukGIHB8sN8X9nVK35bZ8yjgfowgfcwEgYDVR0TAQH%2FBAgwBgEB%2FwIBAzALBgNVHQ8EBAMCAAYwYwYDVR0lBFwwWgYEVR0lAAYIKwYBBQUHAwEGCCsGAQUFBwMCBggrBgEFBQcDAwYIKwYBBQUHAwQGCCsGAQUFBwMIBggrBgEFBQcDCQYKKwYBBAGCNwoDAQYKKwYBBAGCNwoDBDAXBgkrBgEEAYI3FAIECgwIY2VydFR5cGUwIwYJKwYBBAGCNxUCBBYEFAEBAQEBAQEBAQEBAQEBAQEBAQEBMBwGCSsGAQQBgjcVBwQPMA0GBSkBAQEBAgEKAgEUMBMGCSsGAQQBgjcVAQQGAgQAFAAKMAoGCCqGSM49BAMCA0gAMEUCIG1I4UBLxyZCVIxMi2%2BpU9C1kIxwuRRRFFu859Id%2B5pMAiEA%2BHlGQQTld5sYUvb9OTPa8aRS88pc6al9%2BpgKIdju9Ok%3D)

**Comment by rmhrisk** [comment]
That was a cert I found on the internet that was supposedly created with OpenSSL..

You cert, at least according to the exception, has a ASN.1 encoding issue:
![image](https://user-images.githubusercontent.com/1619279/109556209-5fb9ff80-7a8b-11eb-8c27-d7e7a513d3f0.png)

I took a quick look : https://lapo.it/asn1js/#MIICJjCCAcygAwIBAgIBATAKBggqhkjOPQQDAjAeMRwwCQYDVQQGEwJSVTAPBgNVBAMeCABUAGUAcwB0MB4XDTE5MDIwMTA1MDAwMFoXDTIyMDIwMTA1MDAwMFowHjEcMAkGA1UEBhMCUlUwDwYDVQQDHggAVABlAHMAdDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABM_t5xXa6iAL8CVxEgn4FDSzSmx0TM5_qlrFjA0R0fGzHpEndOW0V7D0VEDnPxdd8KukGIHB8sN8X9nVK35bZ8yjgfowgfcwEgYDVR0TAQH_BAgwBgEB_wIBAzALBgNVHQ8EBAMCAAYwYwYDVR0lBFwwWgYEVR0lAAYIKwYBBQUHAwEGCCsGAQUFBwMCBggrBgEFBQcDAwYIKwYBBQUHAwQGCCsGAQUFBwMIBggrBgEFBQcDCQYKKwYBBAGCNwoDAQYKKwYBBAGCNwoDBDAXBgkrBgEEAYI3FAIECgwIY2VydFR5cGUwIwYJKwYBBAGCNxUCBBYEFAEBAQEBAQEBAQEBAQEBAQEBAQEBMBwGCSsGAQQBgjcVBwQPMA0GBSkBAQEBAgEKAgEUMBMGCSsGAQQBgjcVAQQGAgQAFAAKMAoGCCqGSM49BAMCA0gAMEUCIG1I4UBLxyZCVIxMi2-pU9C1kIxwuRRRFFu859Id-5pMAiEA-HlGQQTld5sYUvb9OTPa8aRS88pc6al9-pgKIdju9Ok

And I don't see why, though this cert has a lot of MSFT proprietary things; what issued it?

@microshine

**Comment by rmhrisk** [comment]
@microshine looked at your certificate and it appears the certificate template extension is not formed correctly:

We expect the certificate template to be:

```
CertificateTemplateName ::= UTF8String
```

But yours is:
```
CertificateTemplateName ::= SEQUENCE {
  Name            UTF8String
}
```

Our current interpretation seems to match https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-wcce/3aec3e50-511a-42f9-a5d5-240af503e470
But yours is:
CertificateTemplateName ::= UTF8String

**Comment by TJKoury** [comment]
I just generated it using the [pki.js complex cert example](https://pkijs.org/examples/X509_cert_complex_example.html), and it seems to work in OpenSSL.

I'll generate another one using OpenSSL and try it, sb.

**Comment by TJKoury** [comment]
Ok, I generated another one using my library (which uses OpenSSL directly), and it seems to work fine.

[link](https://understandingwebpki.com/?cert=MIICaDCCAg%2BgAwIBAgIBATAKBggqhkjOPQQDAjBPMRIwEAYDVQQKDAlzZWNwMjU2azExDDAKBgNVBAsMA0JUQzErMCkGA1UEAwwiMURDeU1oYXdWWUs0cjhlYUVmaGlrY3cyWlY0Rng5WGs1VjAeFw0xMTAzMDIwOTQ3MjlaFw0yMTAzMDEyMTQ3MjlaME8xEjAQBgNVBAoMCXNlY3AyNTZrMTEMMAoGA1UECwwDQlRDMSswKQYDVQQDDCIxREN5TWhhd1ZZSzRyOGVhRWZoaWtjdzJaVjRGeDlYazVWMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEpH0Za%2Fj0e71c2RRRFvHXgxN9XlXO70Bqk53YhZTVRUNiAgAV%2FyEsRAkKuwykCzAXsHlDbqi59ZtcOAadhGarxqOB3jCB2zASBgNVHRMBAf8ECDAGAQH%2FAgEKMAsGA1UdDwQEAwIBhjAdBgNVHSUEFjAUBggrBgEFBQcDAwYIKwYBBQUHAwgwHQYDVR0OBBYEFNo5o%2B5ea0sNMlW%2F75VgGJCv2AcJMB8GA1UdIwQYMBaAFNo5o%2B5ea0sNMlW%2F75VgGJCv2AcJMFkGA1UdEQRSMFCGGWh0dHBzOi8vZGlnaXRhbGFyc2VuYWwuaW%2BCD2RpZ2l0YXJzZW5hbC5pb4cECgoKAYcEwKgBAYEWaW5mb0BkaWdpdGFsYXJzZW5hbC5pbzAKBggqhkjOPQQDAgNHADBEAiAwoDEoGj4X8yUczlQqw0tC7M6mE6XoULIrW1uyp%2B2diAIgecCmZARL%2BuXO%2F6q0df%2FGPwgkOmBjxi%2FnKSelw4A4D%2F4%3D).

Can you point me to an example using pki.js programmatically creating an ec cert?  Things seem to have changed a bit since I submitted a pull request, my old examples aren't working.

**Comment by rmhrisk** [comment]
It is probably easier to create the certs using our higher-level library - https://github.com/PeculiarVentures/x509/

**Comment by microshine** [comment]
@TJKoury see example https://codesandbox.io/s/generate-cert-fjwfh

**Comment by TJKoury** [comment]
@microshine I did check that out.  I'm still not able to generate a certificate with secp256k1, it does not seem to be supported [here](https://github.com/PeculiarVentures/x509/blob/master/src/ec_algorithm.ts).

So it's able to read only, or is there something else I'm missing?  Thanks for the help.

**Comment by donskov** [comment]
> How did you generate the certificate above? I keep getting errors:
> 
> [link](https://understandingwebpki.com/?cert=MIICJjCCAcygAwIBAgIBATAKBggqhkjOPQQDAjAeMRwwCQYDVQQGEwJSVTAPBgNVBAMeCABUAGUAcwB0MB4XDTE5MDIwMTA1MDAwMFoXDTIyMDIwMTA1MDAwMFowHjEcMAkGA1UEBhMCUlUwDwYDVQQDHggAVABlAHMAdDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABM%2Ft5xXa6iAL8CVxEgn4FDSzSmx0TM5%2FqlrFjA0R0fGzHpEndOW0V7D0VEDnPxdd8KukGIHB8sN8X9nVK35bZ8yjgfowgfcwEgYDVR0TAQH%2FBAgwBgEB%2FwIBAzALBgNVHQ8EBAMCAAYwYwYDVR0lBFwwWgYEVR0lAAYIKwYBBQUHAwEGCCsGAQUFBwMCBggrBgEFBQcDAwYIKwYBBQUHAwQGCCsGAQUFBwMIBggrBgEFBQcDCQYKKwYBBAGCNwoDAQYKKwYBBAGCNwoDBDAXBgkrBgEEAYI3FAIECgwIY2VydFR5cGUwIwYJKwYBBAGCNxUCBBYEFAEBAQEBAQEBAQEBAQEBAQEBAQEBMBwGCSsGAQQBgjcVBwQPMA0GBSkBAQEBAgEKAgEUMBMGCSsGAQQBgjcVAQQGAgQAFAAKMAoGCCqGSM49BAMCA0gAMEUCIG1I4UBLxyZCVIxMi2%2BpU9C1kIxwuRRRFFu859Id%2B5pMAiEA%2BHlGQQTld5sYUvb9OTPa8aRS88pc6al9%2BpgKIdju9Ok%3D)

Error fixed. Please check again.

**Comment by microshine** [comment]
@TJKoury I'm working on it. I'll publish the new version of `@peculiar/x509` in 30 minutes

**Comment by TJKoury** [comment]
@microshine You are a beast!    Works like a charm.

**Comment by TJKoury** [comment]
@microshine In my quest to replace my library with this one, any easy method to import an EC private key and generate a public key from it?  All the machinery is there in [webcrypto](https://github.com/PeculiarVentures/webcrypto), but the functionality does not seem to be exposed.

**Comment by rmhrisk** [comment]
@TJKoury would be best to file an issue with this question in the X509 repo.

**Comment by TJKoury** [comment]
@rmhrisk It's not really a certificate issue, perhaps one of the other crypto repos?  Basically this code here:

```
import elliptic from "elliptic";

const getPublicFromPrivateHex = (privateHex, curve = "secp256k1", compressed = true) => {
  let ec = new elliptic.ec(curve);
  let key = ec.keyFromPrivate(privateHex, "hex");
  return key.getPublic(compressed, "hex");
};
```

**Comment by rmhrisk** [comment]
Just want to keep this repo for things related to PKI.js
