### ISSUE TITLE
can this library be used to read certs from Windows Certificate store?

### ISSUE THREAD

**Issue by sumantfordev** [PeculiarVentures/PKI.js#270]
can this library be used to read certs from Windows Certificate store?
Running an application from browser if teh application embedded with pki.js can be used to access certs from the device certificate store?

**Comment by YuryStrozhevsky** [comment]
@sumantfordev The library works with ArrayBuffer input data only. So, it is not important, from the library's perspective, where you would get the ArrayBuffer. Thus if you would find a way how to get certificate from Widnows Store, encode it into ArrayBuffer the PKIjs would parse the data. How to get certificate from Windows Store - out of scope for the PKIjs.

**Comment by rmhrisk** [comment]
@sumantfordev look at fortifyapp.com we built it to do just that.
