### ISSUE TITLE
Example for adding custom extensions in x509 certificate

### ISSUE THREAD

**Issue by jefjos** [PeculiarVentures/PKI.js#273]
Hello

Could you provide an example of adding custom extension to x509 certificate?
So that the extensions section in certificate would look something like this
```
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature
            X509v3 Basic Constraints: critical
                CA:FALSE
            1.2.3.4.5.6.7.8:
                {"a": {"b":"c"}}
```
Thanks!

**Comment by rmhrisk** [comment]
We don’t write code on demand for other people applications.


Do you have an issue with the library trying to do something we can help with?

Have you see: https://pkijs.org/examples/X509_cert_complex_example.html

**Comment by YuryStrozhevsky** [comment]
[**this link better**](https://github.com/PeculiarVentures/PKI.js/tree/master/examples/CertificateComplexExample)

**Comment by jefjos** [comment]
Thank you for the pointers. Here is what I have tried.

    const attr= "{\"a\":\"b\"}";
   ON.stringify(hlfAttributesObj);
    cert.extensions.push(new Extension({
      extnID: "1.2.3.4.5.6.7.8",
      critical: false,
      extnValue: (new asn1js.OctetString({ valueHex: toArrayBuffer(Buffer.from(hlfAttributes)) })).toBER(false)
    }));

The resulting certificate shows the following

        X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:FALSE
            1.2.3.4.5.6.7.8:
                ..{"a":"b"}

The ".." before the {"a";"b"} is unexpected.

**Comment by YuryStrozhevsky** [comment]
@jefjos Please search closed issues for “extension” tag. I remember I had such question before. Also check issue #166 - probably it would help.

**Comment by jefjos** [comment]
Thanks for the pointer. I figured it out!
The Extension constructor wraps the octetstring under another octetstring, which is the reason why the decoded certificate does not show the string as is.

For my scenario, I got the schema of extension and set the extension value, then called the constructor with schema.

    ```
const attrSchema = Extension.schema();
    attrSchema.valueBlock.value[0] = new asn1js.ObjectIdentifier({value: "1.2.3.4.5.6.7.8"});
    attrSchema.valueBlock.value[1] = new asn1js.Boolean({value: false});
    attrSchema.valueBlock.value[2] = new asn1js.OctetString({valueHex: stringToArrayBuffer(attr)});

    cert.extensions.push(new Extension({
      schema: attrSchema
    }));
```
Closing this issue now.
