### ISSUE TITLE
Is it possible to convert an x509 certificate object back to a file.

### ISSUE THREAD

**Issue by jegan019** [PeculiarVentures/PKI.js#282]
I am trying to convert an x509 certificate object back into a PEM string that can be written to a file. The certificate object was generated by using PKI.js to parse a DER encoded certificate retrieved through Firefox's API (WebRequest.CertificateInfo). Is there a way to do this through PKI.js?

**Comment by rmhrisk** [comment]
I think you are asking how you can convert DER to PEM?

**Comment by jegan019** [comment]
> I think you are asking how you can convert DER to PEM?

Not really. So WebRequest.CertificateInfo contains an attribute called rawDER which is an array of numbers and represents the DER encoding for the certificate. I used PKI.js to parse this using the following code:
`const asn1 = asn1js.fromBER(certificate);`
` let x509 = new Certificate({ schema: asn1.result });`
I had to play around with the rawDER before I parsed it. But now I have a x509 certificate object. Now I am trying to write the certificate to a file. Either convert the x509 to PEM and then write it or any other way. All the examples I have seen are to convert PEM, DER to the x509 object but no examples to do the opposite.

**Comment by rmhrisk** [comment]
You can look at the “complex certificate example” for how to encode to PEM.

**Comment by YuryStrozhevsky** [comment]
@jegan019 Please aware that “examples “ folder exists only in development version of PKIJS. I mean on GitHub repo only. You will not have it after “npm I pkijs”.

**Comment by jegan019** [comment]
> You can look at the “complex certificate example” for how to encode to PEM.

Thank you very much. I think I have found it.

**Comment by jegan019** [comment]
> @jegan019 Please aware that “examples “ folder exists only in development version of PKIJS. I mean on GitHub repo only. You will not have it after “npm I pkijs”.

Yes I am aware of that. My usage of pkijs is through npm but I did download the repo to took through the code.

**Comment by themighty1** [comment]
Here's what it takes to convert a Certificate back to ArrayBuffer

cert.toSchema(true).toBER(false)
