### ISSUE TITLE
Unable to inject IP address into CSR

### ISSUE THREAD

**Issue by sureshreddygovindu** [PeculiarVentures/PKI.js#286]
Thank for your help!!! 
I'm using PKI.js to generate CSR, I able to generate CSR successfully but unable to inject SAN IPV4 address into it.  I able to inject SAN domainname, URI, email but not IP address. 

below are the code snippet I'm using to inject IP. 

```
keyPurposes.push(new GeneralName({
		type: 7, 
		value: "10.10.43.444"
	})
```

Exception 

```
vendor.js:73463 ERROR TypeError: Cannot set property 'tagClass' of undefined
    at GeneralName.toSchema (vendor.js:330997)
```

**Comment by YuryStrozhevsky** [comment]
@sureshreddygovindu Seems you did not check [**this example**](https://github.com/PeculiarVentures/PKI.js/tree/master/examples/PKCS10ComplexExample) and especially [**this line of code**](https://github.com/PeculiarVentures/PKI.js/blob/master/examples/PKCS10ComplexExample/es6.js#L65).

**Comment by sureshreddygovindu** [comment]
Thanks!
