### ISSUE TITLE
live example cert chain validation doesn't work

### ISSUE THREAD

**Issue by themighty1** [PeculiarVentures/PKI.js#289]
I tried the steps below both in Firefox and Chriome. I went to 
https://pkijs.org/examples/X509_cert_complex_example.html

Then I opened reddit.com  and exported each cert in DER format, I got 3 certificates
_.reddit.com
DigiCert SHA2 Secure Server CA
Builtin Object Token_DigiCert Global Root CA

Then on the live example page I feed to 

Select trusted certs (binary):
Builtin Object Token_DigiCert Global Root CA

 Load intermediate certificates (binary): 
_.reddit.com
DigiCert SHA2 Secure Server CA

Press verify, 
Verification result: false

I repeated the same steps for youtube.com, also got
Verification result: false

Also tried to verify in nodejs, got 'No valid certificate paths found'

**Comment by rmhrisk** [comment]
Include intermediate in the bAg of CA certa also.

Ryan Hurst

Sent from my iPhone

On Oct 3, 2020, at 8:28 AM, themighty1 <notifications@github.com> wrote:

﻿

I tried the steps below both in Firefox and Chriome. I went to
https://pkijs.org/examples/X509_cert_complex_example.html<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpkijs.org%2Fexamples%2FX509_cert_complex_example.html&data=02%7C01%7C%7Cad90d47e244b42c0b35708d867b0f7ff%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637373357050251579&sdata=JoETu2uHxG%2FAfAlDso351UwBbOqL36zk17SVGvZm5kU%3D&reserved=0>

Then I opened reddit.com and exported each cert in DER format, I got 3 certificates
_.reddit.com
DigiCert SHA2 Secure Server CA
Builtin Object Token_DigiCert Global Root CA

Then on the live example page I feed to

Select trusted certs (binary):
Builtin Object Token_DigiCert Global Root CA

Load intermediate certificates (binary):
_.reddit.com
DigiCert SHA2 Secure Server CA

Press verify,
Verification result: false

I repeated the same steps for youtube.com, also got
Verification result: false

Also tried to verify in nodejs, got 'No valid certificate paths found'

**Comment by themighty1** [comment]
Do you mean

Select trusted certs (binary):
Builtin Object Token_DigiCert Global Root CA
DigiCert SHA2 Secure Server CA

Load intermediate certificates (binary):
_.reddit.com

? I get Verification result: false
I also tried every possible combination, none worked.

**Comment by YuryStrozhevsky** [comment]
@themighty1 You forgot about one detail - CRLs for intermediate certificates. Without it verification engine would consider the certificates as invalid and thus the verification result would be "false". 

As soon as you worry about verification engine in PKI.js I need to assure you that this part of code was tested against NIST PKITS (PKI Test Suite). This test you could find [**here**](https://github.com/PeculiarVentures/PKI.js/tree/master/examples/NISTPKITS). Moreover, this test run on every build on [**CircleCI**](https://circleci.com/gh/PeculiarVentures/PKI.js/tree/master).

**Comment by themighty1** [comment]
@YuryStrozhevsky, in this particular case there has been no certificate revokation. 
What kind of file do I need to provide at  "Load CRLs (binary):" to show that the CRL is empty?

**Comment by YuryStrozhevsky** [comment]
@themighty1 You need to provide a real CRL file from trusted authority.

**Comment by YuryStrozhevsky** [comment]
Just for referense: even if a CRL is empty it must be signed by trusted authority.

**Comment by YuryStrozhevsky** [comment]
@themighty1 Also do not forget CRLs for all intermediate certificates.

**Comment by themighty1** [comment]
@YuryStrozhevsky , thanks, but if CRLs are mandatory, please help me understand why I was getting a correct verification in my code (running in browser environment ) when supplying crls: []  


    const ccve = new CertificateChainValidationEngine({
          trustedCerts: trustedCertificates,
          certs: chain,
          crls: [],
        });
    
    let pr = await ccve.verify()
    return pr.result

would return true.

**Comment by YuryStrozhevsky** [comment]
@themighty1 Have you tried to run the live example with all necessary CRLs? If so and you got the correct result then please close the issue.

**Comment by themighty1** [comment]
Unfortunately, one of the CRL files from http://crl3.digicert.com/ssca-sha2-g6.crl
is 17MB in size and when I feed it to the live example page's field "Load CRLs (binary):"  my browser consumes 2-3GB of RAM and the tab hangs for 1 minute.

Should I open a separate issue for that or is this expected because the CRL file is so large?

**Comment by rmhrisk** [comment]
Please create a bug for your new issue.

**Comment by themighty1** [comment]
After I used the CRL files, I still got Verification result: false

The site is google.com
In Chrome's Certificate Viewer I exported leaf,intermediate and root certs as DER
also downloaded CRLs from the URL in the cert's "CRL Distribution Points"
http://crl.pki.goog/GTS1O1core.crl
http://crl.pki.goog/gsr2/gsr2.crl

Select trusted certs (binary): root (also tried root + intermediate)
Load intermediate certificates (binary): leaf + intermediate
Load CRLs (binary): CRL for leaf and CRL for intermediate

**Comment by rmhrisk** [comment]
@YuryStrozhevsky please advise

**Comment by YuryStrozhevsky** [comment]
Please attach all user certificates here

**Comment by themighty1** [comment]
leaf cert:

[_.google.com.txt](https://github.com/PeculiarVentures/PKI.js/files/5333455/_.google.com.txt)

intermediate:

[GTS CA 1O1.txt](https://github.com/PeculiarVentures/PKI.js/files/5333464/GTS.CA.1O1.txt)

root cert:

[Builtin Object Token_GlobalSign Root CA - R2.txt](https://github.com/PeculiarVentures/PKI.js/files/5333469/Builtin.Object.Token_GlobalSign.Root.CA.-.R2.txt)
