### ISSUE TITLE
Is there anything about generate a csr from private key ?

### ISSUE THREAD

**Issue by smallMote** [PeculiarVentures/PKI.js#299]

**Comment by YuryStrozhevsky** [comment]
[**This**](https://github.com/PeculiarVentures/PKI.js/tree/master/examples/PKCS10ComplexExample)

**Comment by smallMote** [comment]
Thanks!! I looked at that case and implemented the same function, but my real purpose is how to use the private key to match the certificate. Can you give me some suggestions?Thank you very match!!!

**Comment by YuryStrozhevsky** [comment]
Not sure I understood your needs correctly, but in the example [**there is**](https://github.com/PeculiarVentures/PKI.js/blob/master/examples/PKCS10ComplexExample/es6.js#L92) line of code where generates private key. About right way on "how to use private key with certificate" you could check [**this example**](https://github.com/PeculiarVentures/PKI.js/tree/master/examples/CertificateComplexExample).

**Comment by smallMote** [comment]
> Not sure I understood your needs correctly, but in the example [**there is**](https://github.com/PeculiarVentures/PKI.js/blob/master/examples/PKCS10ComplexExample/es6.js#L92) line of code where generates private key. About right way on "how to use private key with certificate" you could check [**this example**](https://github.com/PeculiarVentures/PKI.js/tree/master/examples/CertificateComplexExample).

Thank you very much !!! I've solved the problem I've had!(*^▽^*)
