### ISSUE TITLE
How to sign certificate with my own CA

### ISSUE THREAD

**Issue by efkan** [PeculiarVentures/PKI.js#30]
Hello,

Above all, I want to say 'thank you for these useful tools'.

I've looked at CreateNewX509Certificate example. 
I'm trying to understand.  I couldn't see any imported a CA key and a cert :)

When using OpenSSL, firstly a `private key` is generated, secondly a `CSR` is generated and thirdly a `certificate` is generated using `CA key` and `certificate`.

I would like to know, how to generate a certificate using a CA key and certificate?

**Comment by YuryStrozhevsky** [comment]
In fact all examples in PKIjs make "self-signed" certificates. In order to make certificates, signed by private key from CA certificate, you need firstly import CA private key and certificate and then generate a new, user certificate. Regarding importing private key and certificate you can see [this example](https://github.com/GlobalSign/PKI.js/tree/master/examples/How%20To%20Encrypt%20CMS%20via%20certificate). Regarding "more generic" certificate example you can check [this example](https://github.com/GlobalSign/PKI.js/tree/master/examples/Certificate%20complex%20example).

**Comment by efkan** [comment]
Really great job!

I need pretty much time to learn how to use :)

**Comment by daveamit** [comment]
@YuryStrozhevsky I'm trying to do same thing, sadly the links are dead :( ! Can you please point me in right direction. I'm trying to achieve following:
```
1. I already have CA (with private key) stored somewhere.
2. I was to generate CSR (With new keys --- happens on client side)
3. Accept the CSR (with CA)
```
Any help would be appreciated!

Thanks!

**Comment by rmhrisk** [comment]
Take a look at this example: https://github.com/PeculiarVentures/PKI.js/tree/master/examples/CertificateComplexExample


Since this bug was created PKIjs 2.X was released which is why the old links no longer work.

**Comment by daveamit** [comment]
Thanks @rmhrisk for prompt response! 

Great example, though I have one question, how do I generate a CSR? CSR has to come from a different machine. basically I'm working on an IoT project, device will send CSR as part of their activation. There is a constrain that Key pair has to be generated on the Device (they are generated by a hardware component) and private key never leave the IC.

**Comment by YuryStrozhevsky** [comment]
@daveamit The "CSR example" [is here](https://github.com/PeculiarVentures/PKI.js/tree/master/examples/PKCS10ComplexExample). Take into account that CSR is a format officially described as PKCS#10.

**Comment by daveamit** [comment]
Thanks @YuryStrozhevsky

**Comment by daveamit** [comment]
Hi @YuryStrozhevsky,
    Thanks for the help. I'm now able to (programmatically via this awesome lib - *pkijs*):
   1. Successfully generate CSR and also able to verify (Thanks to the superb examples)
   2. Generate the CA certificate (Basically a self-signed certificate)

Now, I'm stuck with the final step. _How do I sign the CSR with the CA that I have?_ I understand how to generate Self sign a certificate.
And If I understand correctly, to do a self sign I put **my own information** with **my own Public key** and then sign with **my own Private key** (hence, the self sign). So to sign a CSR, Is it ok if I do following?
1. Verify the CSR.
2. Extract information from the CSR like CN, O etc (with public key).
3. Build a new certificate with the extracted information and public key from the CSR (Subject Key)
4. Then Sign with CA's private key.

Am I correct or I'm missing something?

Thanks in advance.

**Comment by rmhrisk** [comment]
You understand correctly

**Comment by daveamit** [comment]
Thanks @YuryStrozhevsky / @rmhrisk !
I was able to generate proper certs and use with my existing infrastructure. This would  **not have been possible without pkijs**, even with my limited understanding I was able to get it done in few hours (with awesome support from you guys)

Thanks again. I guess we can close this issue now.
