### ISSUE TITLE
Parse CMS

### ISSUE THREAD

**Issue by alex-jss** [PeculiarVentures/PKI.js#302]
I try to check the [Parse CMS](https://pkijs.org/examples/CMSSigned_complex_example.html) example, but I get the error: `Object's schema was not verified against input data for ContentInfo`.
Tell me why I can not parse the CMS?
CMS - [testFile.pdf.zip](https://github.com/PeculiarVentures/PKI.js/files/5886778/testFile.pdf.zip)

**Comment by YuryStrozhevsky** [comment]
It is correctly parsed when you decode it from BASE-64. You need to carefully read titles: **Load binary CMS Signed**.

**Comment by alex-jss** [comment]
@YuryStrozhevsky Tell me pleace, how can I decode `extnValue` and `parsedValue` to get readable values?
I used `arrayBufferToString` from `pvutils` and only got this.

**Comment by alex-jss** [comment]
@YuryStrozhevsky  Can you also tell me how to decode correctly `1.2.643.100.111` correctly to get a readable value? I used `arrayBufferToString` and `bufferToHexCodes`.
![image](https://user-images.githubusercontent.com/44188728/106388741-593b5800-63f9-11eb-9feb-906eb9982ac0.png)

**Comment by YuryStrozhevsky** [comment]
This is not an "informational board" where you can ask any questions you like. If you found any issues in PKIjs then please provide a test data first.
