### ISSUE TITLE
Question: Create Private Key with ECDSA and Password

### ISSUE THREAD

**Issue by Julchenwsf** [PeculiarVentures/PKI.js#317]
Hello,

i try to use your library, but i did not find out how to create a keypair? Can you show me an short example?

Best regards Julia

**Comment by rmhrisk** [comment]
Hello @Julchenwsf, this library does not create cryptographic keys, instead, it uses WebCrypto for all cryptographic operations. Instead, this library creates and uses the ASN.1 data-structures that are often associated with such keys. This is a good resource on how to use WebCrypto https://github.com/diafygi/webcrypto-examples.

WebCrypto itself doesn't support the concept of a password, I suspect what you are trying to do is to export the generated key to a file in an encrypted form but there are several formats for this depending on what application you want to use it with.
