### ISSUE TITLE
Is it possible to convert `.pem` cert+key files into one `.jks` format

### ISSUE THREAD

**Issue by xiaohuilam** [PeculiarVentures/PKI.js#319]
Thank you a lot!

**Comment by rmhrisk** [comment]
It is but you would need to do it.

Looks like this could be useful. https://www.npmjs.com/package/jks-js

**Comment by xiaohuilam** [comment]
It looks like the npmjs package `jks-js` only the `.jks` to `.pem` converter.
But thank you anyway!
