### ISSUE TITLE
Example of x509 v3 Certificate Extensions Decoding

### ISSUE THREAD

**Issue by yaroslava-tkachuk** [PeculiarVentures/PKI.js#320]
Hi,

I have been searching for any working example of x509 v3 certificate extensions decoding - unfortunately, with no luck. I am createing a Pkijs Certificate object from raw data and getting extensions array. extnValue is an OctetString object which I am struggling to decode to an integer (JS number type). Would highly appreciate any example on how to decode extensions values.

I am using only Pkijs and Asn1js libraries. 
Extending them  with asn1js/org/pkijs/common and pkijs/org/pkijs/x509_schema:

`var merge = require("node.extend");

var common = require("asn1js/org/pkijs/common");
var _asn1js = require("asn1js");
var _pkijs = require("pkijs");
var _x509schema = require("pkijs/org/pkijs/x509_schema");

// #region Merging function/object declarations for ASN1js and PKIjs
var asn1js = merge(true, _asn1js, common);

var x509schema = merge(true, _x509schema, asn1js);

var pkijs_1 = merge(true, _pkijs, asn1js);
var pkijs = merge(true, pkijs_1, x509schema);`

causes an error - Error: EMFILE: Too many open files (on WIndows).

Will be really grateful for any advise / sample extensions decoding code snippet.

Kind regard,
Yari

**Comment by microshine** [comment]
Try [@peculiar/x509](https://github.com/PeculiarVentures/x509#decoded-x509-certificate). It supports X509 extensions and allows extending it by registering your own

**Comment by microshine** [comment]
PKIjs implements X509 extensions too. See [source code](https://github.com/PeculiarVentures/PKI.js/blob/master/src/Extension.js#L170-L399) how it parses well-known extensions

**Comment by YuryStrozhevsky** [comment]
@yaroslava-tkachuk 
[**Example**](https://github.com/PeculiarVentures/PKI.js/tree/master/examples/CertificateComplexExample)

**Comment by yaroslava-tkachuk** [comment]
Thanks a lot for the answers!
Eventually, I have figured out that I was getting already decoded extensions, but there were some additional bitstring values at the beginnig (probably, some ASN1 related stuff). 
`.extnValue.toJSON().valueBeforeDecode` and skipping additional data worked for me to get a hex string representing my ASN1:INTEGER extension values.
Again, thanks a lot for the fast replies!
