### ISSUE TITLE
Use in QuickJS

### ISSUE THREAD

**Issue by Jonas-Metzger** [PeculiarVentures/PKI.js#321]
I need to compile some existing Node.js code (which uses PKI.js) to C, so I'm switching to QuickJS instead of Node.js. How do I use PKI.js in QuickJS?

**Comment by rmhrisk** [comment]
We have no experience with QuickJS. As PKIjs is a pure JS library with minimal dependencies and QuickJS just looks like alternate engine I imagine it just works?
