### ISSUE TITLE
Adding the principal name of the subscriber in the SubjectAltName extension as a UPN (1.3.6.1.4.1.311.20.2.3)

### ISSUE THREAD

**Issue by xomilders** [PeculiarVentures/PKI.js#323]
Hi,

I am using PKIJS to generate PKCS10 and am having a bit of a hard time determining precisely how to construct this OtherName value for 1.3.6.1.4.1.311.20.2.3 like so:

<img width="785" alt="Screen Shot 2021-07-13 at 2 12 32 PM" src="https://user-images.githubusercontent.com/64909799/125508721-3411f423-b8c3-4bbf-96e4-01a12e9529b1.png">

I have tried to figure out how to properly construct the OtherName, and I drew from this post, but I think maybe using a sequence is wrong (see https://stackoverflow.com/questions/44290311/how-can-the-upnname-user-principal-name-be-set-with-bouncycastle-x509v3certifi). I have tried adding the ObjectIdentifier and the Utf8String as separate GeneralNames instead of using a sequence, but this is also not quite it. 

```
function generateSubjectAltNames(upn, email) {

    var subAltPrincipalSeq = new asn1js.Sequence({
        value: [
            new asn1js.ObjectIdentifier({ value: "1.3.6.1.4.1.311.20.2.3" }),
            new asn1js.Utf8String({ value: upn })
        ]
    });

    var altNames = new pkijs.AltName({
        altNames: [
            new pkijs.GeneralName({
                type: 1, // rfc822Name
                value: email
            }), 
            new pkijs.GeneralName({
                type: 0, // Other Name
                value: subAltPrincipalSeq
            })
        ]
    });

    var altNamesExt = new pkijs.Extension({
        extnID: "2.5.29.17",
        critical: false,
        extnValue: altNames.toSchema().toBER(false)
    });

    return altNamesExt;
}

```

Thank you for shedding any light on my issue and for all your efforts creating and maintaining PKIJS.

Best,

Seth Milder

**Comment by xomilders** [comment]
BTW, this is the structure I am attempting to create:

` 2.5.29.17: Flags = 0, Length = 43
    Subject Alternative Name
        RFC822 Name=xxx@xxxx.com
        Other Name:
             Principal Name=xxx@xxxx.com
    AltName: 2 entries:
    AltName[0] CERT_ALT_NAME_RFC822_NAME: "xxx@xxxx.com"
    AltName[1] CERT_ALT_NAME_OTHER_NAME: 1.3.6.1.4.1.311.20.2.3 Principal Name: 
      CERT_RDN_UTF8_STRING, Length = 22 (22 Characters)
        "xxx@xxxx.com"

        6c 6e 32 37 33 38 66 5f  35 31 38 34 40 69 63 65   xxx@xxx
        72 74 2e 63 6f 6d                                  x.com

        6c 00 6e 00 32 00 37 00  33 00 38 00 66 00 5f 00   x.x.x.x.x.x.f._.
        35 00 31 00 38 00 34 00  40 00 69 00 63 00 65 00   x.x.x.x.@.x.x.x.
        72 00 74 00 2e 00 63 00  6f 00 6d 00               x.x...c.o.m.


    0000  30 41 81 17 6e 65 77 75  73 65 72 34 31 37 34 40   0A..xxx@
    0010  65 78 6f 73 74 61 72 2e  63 6f 6d a0 26 06 0a 2b   xxx.com.&..+
    0020  06 01 04 01 82 37 14 02  03 a0 18 0c 16 6c 6e 32   .....7.......xx
    0030  37 33 38 66 5f 35 31 38  34 40 69 63 65 72 74 2e   xxx@xxx.
    0040  63 6f 6d                                           com
0000: 30 41					; SEQUENCE (41 Bytes)
0002:    81 17					; CONTEXT_SPECIFIC[1] (17 Bytes)
0004:    |  6e 65 77 75 73 65 72 34  31 37 34 40 65 78 6f 73  ; xxxxx@xxxx
0014:    |  74 61 72 2e 63 6f 6d                              ; xxx.com
001b:    a0 26					; OPTIONAL[0] (26 Bytes)
001d:       06 0a				; OBJECT_ID (a Bytes)
001f:       |  2b 06 01 04 01 82 37 14  02 03
            |     ; 1.3.6.1.4.1.311.20.2.3 Principal Name
0029:       a0 18				; OPTIONAL[0] (18 Bytes)
002b:          0c 16				; UTF8_STRING (16 Bytes)
002d:             6c 6e 32 37 33 38 66 5f  35 31 38 34 40 69 63 65  ; xxxx@xxx
003d:             72 74 2e 63 6f 6d                                 ; xx.com
                     ; "xxx@xxx.com"
`

I fiddled with it a bit, and this code seems to get close to the mark:

`	var altNames = new pkijs.AltName({
							altNames: [
								new pkijs.GeneralName({
									type: 1, // rfc822Name
									value: _me.Config.Configuration.Rfc822Name
								}),
								new pkijs.GeneralName({
									type: 0, // Other Name
									value:
										new asn1js.ObjectIdentifier({ value: "1.3.6.1.4.1.311.20.2.3" })

								}),
								new pkijs.GeneralName({
									type: 0, // Other Name
									value:
										new asn1js.Utf8String({ value: _me.Config.Configuration.UPNName })
								})
							]
						});

						var altNamesExt = new pkijs.Extension({
							extnID: "2.5.29.17",
							critical: false,
							extnValue: altNames.toSchema().toBER(false)
						});
`

It produces this structure, which while seemingly close, is clearly wrong:

`2.5.29.17: Flags = 0, Length = 43
    Subject Alternative Name

    0000  30 41 81 17 73 65 74 68  2e 6d 69 6c 64 65 72 40   0A..xxx@
    0010  65 78 6f 73 74 61 72 2e  63 6f 6d a0 0c 06 0a 2b   xxxx.com....+
    0020  06 01 04 01 82 37 14 02  03 a0 18 0c 16 6d 69 6c   .....7.......xxxx
    0030  64 65 72 73 5f 38 33 33  31 40 69 63 65 72 74 2e   xxx@xxxx.
    0040  63 6f 6d                                           com
0000: 30 41					; SEQUENCE (41 Bytes)
0002:    81 17					; CONTEXT_SPECIFIC[1] (17 Bytes)
0004:    |  73 65 74 68 2e 6d 69 6c  64 65 72 40 65 78 6f 73  ; xxxx@xxx
0014:    |  74 61 72 2e 63 6f 6d                              ; tar.com
001b:    a0 0c					; OPTIONAL[0] (c Bytes)
001d:    |  06 0a				; OBJECT_ID (a Bytes)
001f:    |     2b 06 01 04 01 82 37 14  02 03
         |        ; 1.3.6.1.4.1.311.20.2.3 Principal Name
0029:    a0 18					; OPTIONAL[0] (18 Bytes)
002b:       0c 16				; UTF8_STRING (16 Bytes)
002d:          6d 69 6c 64 65 72 73 5f  38 33 33 31 40 69 63 65  ; xxxx@xx
003d:          72 74 2e 63 6f 6d                                 ; xx.com
                  ; "xxxx@xxx.com"

    0000  30 81 9a 30 3c 06 09 2b  06 01 04 01 82 37 15 07   0..0<..+.....7..
    0010  04 2f 30 2d 06 25 2b 06  01 04 01 82 37 15 08 87   ./0-.%+.....7...
    0020  c4 9d 7d 82 8a d9 52 87  99 8d 31 8f ee 06 85 98   ..}...R...1.....
    0030  cc 09 6b 86 db d3 0c 86  dc c0 6c 02 01 64 02 01   ..k.......l..d..
    0040  2e 30 0e 06 03 55 1d 0f  01 01 ff 04 04 03 02 00   .0...U..........
    0050  30 30 4a 06 03 55 1d 11  04 43 30 41 81 17 73 65   00J..U...C0A..se
    0060  74 68 2e 6d 69 6c 64 65  72 40 65 78 6f 73 74 61  xx@xxx
    0070  72 2e 63 6f 6d a0 0c 06  0a 2b 06 01 04 01 82 37   x.com....+.....7
    0080  14 02 03 a0 18 0c 16 6d  69 6c 64 65 72 73 5f 38   .......xxx
    0090  33 33 31 40 69 63 65 72  74 2e 63 6f 6d            xxx@xxx.com
0000: 30 81 9a					; SEQUENCE (9a Bytes)
0003:    30 3c					; SEQUENCE (3c Bytes)
0005:    |  06 09				; OBJECT_ID (9 Bytes)
0007:    |  |  2b 06 01 04 01 82 37 15  07
`
Thanks,

Seth Milder

**Comment by microshine** [comment]
### JS
```js
const altName = new pkijs.GeneralNames({
  names: [
    new pkijs.GeneralName({
      type: 0,
      value: new asn1js.Sequence({
          value: [
            new asn1js.ObjectIdentifier({ value: "1.3.6.1.4.1.311.20.2.3" }),
            new asn1js.Constructed({
              idBlock: {
                tagClass: 3,
                tagNumber: 0 // [0]
              },
              value: [new asn1js.Utf8String({ value: "some other name" })],
            }),
          ]
        }).valueBlock,
    }),
  ],
});

const altNameExt = new pkijs.Extension({
  extnID: "2.5.29.17",
  critical: false,
  extnValue: altName.toSchema().toBER(),
  parsedValue: altName,
});

const altNameRaw = altNameExt.toSchema().toBER();
```

### Enoced raw (HEX)
```hex
302a0603551d1104233021a01f060a2b060104018237140203a0110c0f736f6d65206f74686572206e616d65
```

### ASN.1
```asn
SEQUENCE (2 elem)
  OBJECT IDENTIFIER 2.5.29.17 subjectAltName (X.509 extension)
  OCTET STRING (35 byte) 3021A01F060A2B060104018237140203A0110C0F736F6D65206F74686572206E616D65
    SEQUENCE (1 elem)
      [0] (2 elem)
        OBJECT IDENTIFIER 1.3.6.1.4.1.311.20.2.3 universalPrincipalName (Microsoft UPN)
        [0] (1 elem)
          UTF8String some other name
```

**Comment by xomilders** [comment]
This is fantastic! Thank you so much! It works perfectly now. You guys rock 🙂

Best,
Seth

________________________________
