### ISSUE TITLE
Nested SignedData's

### ISSUE THREAD

**Issue by curtdept** [PeculiarVentures/PKI.js#327]
@microshine  I have a CMS someone nested with 20 certs in it. Openssl seems to parse it ok but I can for the life of me get it to parse in node. Any suggestions on how to parse it effectively?

![image](https://user-images.githubusercontent.com/23644717/129986008-6c24231e-a369-4bae-bdb0-d752fb7f84cd.png)

**Comment by rmhrisk** [comment]
Was your issue resolved?

**Comment by curtdept** [comment]
Not really, I ended up just containerizing and wrappering openssl to dump a bunch of pem files, then reading them back.

**Comment by rmhrisk** [comment]
Please provide a sample file.
