### ISSUE TITLE
Usage in Node.js

### ISSUE THREAD

**Issue by a-i-to** [PeculiarVentures/PKI.js#330]
I'd like to use pki.js on the server side (node.js). We do not expect to run it in a browser.

Main usage:
1. Generating a key pair and issuing a certificate
2. CMS sign and verify

Question 1: Is such usage correct?
Question 2 Is it a good idea to use `node-webcrypto-ossl` even if it is not for testing purposes?
Question 3 Are there any other limitations in the node environment?

**Comment by rmhrisk** [comment]
1. This is fine
2. Lastest node has webcrypto 
3. No

**Comment by a-i-to** [comment]
Thanks. I am going to use LTS (v14.17.5), so I will use the external library for a while.

**Comment by microshine** [comment]
Use `@peculiar/webcrypto` for NodeJS v14. It uses NodeJS Crypto API and doesn't require C++
