### ISSUE TITLE
Calls to Promise.reject should wrap strings in Error objects

### ISSUE THREAD

**Issue by benpetermorris** [PeculiarVentures/PKI.js#339]
As it stands, we can't discern where the rejection happened in a catch statement, since the strings provide no stack trace.

Passing `Error` objects to `Promise.reject` would be much more useful.

**Comment by microshine** [comment]
I've published `beta` version of pkijs. Please try it. It fixes the issue

```
npm i pkijs@beta

# or

npm i pkijs@3.0.1-2
```
