### ISSUE TITLE
Integration with external Key-Management Systems

### ISSUE THREAD

**Issue by gnarea** [PeculiarVentures/PKI.js#344]
For security reasons, I'd like to move away from having private keys in the app's memory and use a KMS/HSM instead. This isn't currently supported, is it? The current implementation of PKI.js depends heavily on WebCrypto private keys, but I don't know if there's a way to make this work today.

I _think_ one (ugly) way to make this work relatively easily is by having a [webcrypto provider](https://github.com/PeculiarVentures/webcrypto-core/blob/master/src/provider.ts) whose private `CryptoKey`s actually represent pointers to a key in a KMS/HSM. Of course, this would mean that methods like `exportKey()` would have to throw errors. This workaround would also require updating methods like `EnvelopedData.decrypt()` to take a `CryptoKey` private key (instead of or in addition to an `ArrayBuffer`) and `EnvelopedData.encrypt()` to take a private key when using DH ([instead of generating one internally](https://github.com/PeculiarVentures/PKI.js/blob/9337d256353ffda89569d1ca51222b2e09293ff0/src/EnvelopedData.js#L868-L878)).

The ideal solution IMHO would be to make this explicit by creating an abstraction for private keys, which would only support a subset of operations; e.g.:

```typescript
interface Key {
  getAlgorithm: () => AlgorithmIdentifier;
}

interface AsymmetricKey extends Key {
   getPublicKey: () => Promise<CryptoKey>;
}

interface SigningKey extends AsymmetricKey {
  sign: (...) => Promise<ArrayBuffer>;
}

interface EncryptionKey extends AsymmetricKey {
  encrypt: (...) => Promise<ArrayBuffer>;
}

interface SymmetricKey extends Key {
  encrypt: (...) => Promise<ArrayBuffer>;
  decrypt: (...) => Promise<ArrayBuffer>;
}
```

... but that'd be a much more invasive change.

Thoughts?

**Comment by rmhrisk** [comment]
See node-webcrypto-p11

**Comment by gnarea** [comment]
Thanks @rmhrisk! 

I want to use GCP KMS, which offers a [C library for PKCS#11](https://github.com/GoogleCloudPlatform/kms-integrations/blob/master/kmsp11/docs/user_guide.md), so it seems like I'd simply need to initialise the `Crypto` class in `node-webcrypto-p11` with the path to GCP KMS' shared object `libkmsp11.so`.

However, the issues above with `EnvelopedData` would still prevent me from using `node-webcrypto-p11`, unless I'm missing something. I also use `SignedData` and `Certificate`, but I believe those are fine.

**Comment by gnarea** [comment]
FYI, I ended up integrating the `@google-cloud/kms` library in a [new RSA-PSS provider](https://github.com/relaycorp/awala-keystore-cloud-js/blob/728c7fbbf5972d961f597d8d5bc753191289f560/src/lib/gcp/GcpKmsRsaPssProvider.ts). I may move it to a separate NPM package if other folks find it useful.

[GCP KMS doesn't support (EC)DH](https://issuetracker.google.com/issues/231334600), and our protocol only supports `EnvelopedData` with ECDH, so that's as far as I can take the KMS integration today.

**Comment by rmhrisk** [comment]
Sounds good
