### ISSUE TITLE
Optionally allow engine to be passed explicitly

### ISSUE THREAD

**Issue by gnarea** [PeculiarVentures/PKI.js#348]
Would you accept a PR that allowed `EnvelopedData.encrypt()`, `EnvelopedData.decrypt()`, `SignedData.sign()` and `SignedData.verify()` to take the `engine` as an argument, whilst still falling back to `getEngine()`/`getCrypto()` when the argument is unset?

The current approach depends on global variables:

https://github.com/PeculiarVentures/PKI.js/blob/9230ae8e2ca5af49900b5d74ba4f608b0b967f24/src/common.js#L85

... Which can be problematic for various reasons, but in this particular case I'm concerned that it limits the engine to just one: Since I'm distributing a library that uses PKI.js, I'd rather not alter the global state for third-party apps, especially if they also use PKI.js for other purposes.

**Comment by microshine** [comment]
Going to implement this feature in v3.0.0

**Comment by microshine** [comment]
I've published `beta` version of pkijs. Please try it

```
npm i pkijs@beta

# or

npm i pkijs@3.0.1-2
```

**example**

```js
const cryptoEngine = new pkijs.CryptoEngine({
  name: "some",
  crypto: self.crypto,
  subtle: self.crypto.subtle,
});

const { privateKey, publicKey } = await cryptoEngine.generateKey(alg, false, ["sign", "verify"]);

await certificate.sign(privateKey, hashAlg, cryptoEngine);
```

**Comment by gnarea** [comment]
Thanks @microshine! I'll try it in my lib as soon as I can upgrade it to PKI.js v3 (see #353)
