### ISSUE TITLE
Example given from pkijs.org does not work with typescript

### ISSUE THREAD

**Issue by jabberwocky1994** [PeculiarVentures/PKI.js#371]
Hi,

I'm trying to parse a CRL file and I've copy&pasted [this example](https://stackoverflow.com/questions/63107888/how-to-parse-certificate-revocation-list-crl-in-node-js/63112091#63112091) from stackoverflow. This example works.

I'm not transitioning the project from javascript to typescript and now I'm getting the following error:
```
<project_root>/node_modules/pkijs/build/index.js:408
        this.valueBeforeDecode = asn1.result.RDN.valueBeforeDecodeView.slice().buffer;
                                                                       ^
TypeError: Cannot read properties of undefined (reading 'slice')
```
After trying out the example CRL from pkijs.org, to make sure that it wasn't my own CRL, I got the same result.

**Comment by microshine** [comment]
Looks like you are using old version of asn1js. `valueBeforeDecodeView ` was implemented in `asn1js@3.0.0`. Please update your version and try again.

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/7333669/212850122-cea3baea-c569-4ac5-aef6-ec14dff1aed1.png">
