### ISSUE TITLE
Uncaught ReferenceError: stringToArrayBuffer is not defined

### ISSUE THREAD

**Issue by lexcorp** [PeculiarVentures/PKI.js#74]
Hi, I'm testing, the PDF example, I'm using a root certificate and a user certificate generated in DogTag Certificate System.
By selecting the root certificate (extension "crt"), I get the message:
Uncaught ReferenceError: stringToArrayBuffer is not defined

![captura2](https://cloud.githubusercontent.com/assets/5751288/19018417/3e1a752e-8825-11e6-9b7f-edf5d31aaa1e.JPG)

**Comment by rmhrisk** [comment]
@lexcorp all of the sample in this version require you to put the "org" directory from the PKIjs repository and from the ASN1js repository into the examples folder, this would look like this:

```
/PDFjs/examples
                            PDFexample.html
                            README.md
                            Test.pdf
                            pdfjs
                            org/
                                  pkijs/
                                           asn1.js
                                           cms_schema.js
                                           cms_simpl.js
                                           common.js
                                           ocsp_tsp_schema.js
                                           ocsp_tsp_simpl.js
                                           pkcs12_schema.js
                                           pkcs12_simpl.js
                                           x509_schema.js
                                           x509_simpl.js
```

Also we have built a new, es6-version of PKIjs, you can find it here: https://github.com/PeculiarVentures/pkijs-es6

We have not yet revised all the samples but it would be the best place to work if you were to build on the library as we will no longer be maintaining this once we declare 2.x (the ES6 version).

**Comment by lexcorp** [comment]
Thanks Ryan, the example works and tells me "PDF Successfully verified", however the message continues to appear on the console.

![verify_sucess](https://cloud.githubusercontent.com/assets/5751288/19018926/c99072a8-8838-11e6-99b2-58ca99bb4568.JPG)

**Comment by rmhrisk** [comment]
Not sure what to tell you, on OSX, in Firefox:

![image](https://cloud.githubusercontent.com/assets/1619279/19018937/82ccb4f4-8828-11e6-9ebb-cee282335533.png)

And in Chrome:

![image](https://cloud.githubusercontent.com/assets/1619279/19018940/a0318e98-8828-11e6-9c8f-af02e4e1cd1a.png)


There seems to be something in your environment causing the console error.

**Comment by rmhrisk** [comment]
Sorry, I didn't read your message close enough (it is late). Please email me your two input files.

**Comment by lexcorp** [comment]
Thanks for your attention and patience,

Probably as you say something in my environment is generating the error.
What is different is that only use a CA root file with extension crt.
Deputy files that I use as an example

2016-10-02 0:50 GMT-05:00 Ryan Hurst <notifications@github.com>:

**Comment by lexcorp** [comment]
I experiment with another file extension ".der" and does not generate any error in the console, indicating me not completely supports files with extension ".crt"

**Comment by rmhrisk** [comment]
It should work with PEM files.

We built this : https://github.com/PeculiarVentures/tl-create to create trust lists, it produces PEM output.

Ryan
