### ISSUE TITLE
Extend or Improve PDF example

### ISSUE THREAD

**Issue by lexcorp** [PeculiarVentures/PKI.js#75]
Include example of validation of signatures and certificates in PDF documents with PDF viewer's Mozilla pdf.js or extend or improve PDF example https://github.com/PeculiarVentures/PKI.js/tree/master/examples/PDF%20example 

**Mozilla PDF.js PDF Viewer**
![pdfviewer](https://cloud.githubusercontent.com/assets/5751288/19019065/0a98eeba-883e-11e6-826a-4f00ed06339c.png)
**Open PDF File**
![openpdf](https://cloud.githubusercontent.com/assets/5751288/19019066/135c475e-883e-11e6-9d6e-fe3ad419892b.png)
**Validate Signature Button**
![validatesignatures](https://cloud.githubusercontent.com/assets/5751288/19019067/1b1e81e6-883e-11e6-8196-d02e1b863d91.png)
**Use of menu slide**
![menuslide](https://cloud.githubusercontent.com/assets/5751288/19019068/2399ef72-883e-11e6-9323-06bb25188d18.png)
**Menu Slide In**
![menuslidein](https://cloud.githubusercontent.com/assets/5751288/19019069/2b877dee-883e-11e6-9a14-e3197fe11a65.png)

**Menu Slide project and demo**
https://github.com/adchsm/Slidebars
**Demo**
https://www.adchsm.com/slidebars/

**Comment by rmhrisk** [comment]
We actually have something like this, just better ;)

We are not ready to release it but happy to share a video of it, in confidence, send me an email with your samples from your other bug and ill make you a video after I debug the issue.

Ryan

**Comment by rmhrisk** [comment]
Closing this issue as we will not be doing any further work on the non-ES6 version of this sample.

**Comment by lexcorp** [comment]
Thanks Ryan, I want to work on this functionality, as have some progress, share and you decide if you include in your project.

**Comment by rmhrisk** [comment]
Happy to take pull requests. But please consider working against https://github.com/PeculiarVentures/pkijs-es6.

Having built a solution here I can say verification is easy but an ability to sign files robustly is more complex. We built our own PDF parser / builder library to do this.

**Comment by rmhrisk** [comment]
This will also be of value if you want to go down this path further : https://unmitigatedrisk.com/?p=554

**Comment by lexcorp** [comment]
Ryan thank you very much, I'll take a look at this information.

**Comment by rmhrisk** [comment]
@lexcorp add me on Skype, I am sure I can help.

**Comment by rmhrisk** [comment]
I will add here for posterity sake if your plan for signing was to go down the path of signing via P12 that WebCrypto doesnt support the weak algorithms necessary to do that (see https://unmitigatedrisk.com/?p=543). It is possible to fix this, My plan has been to add these weak algorithms to - https://github.com/PeculiarVentures/webcrypto-liner/ and if present you could then patch PKIjs to open P12s.

You larger issue would be the signing itself, its more complicated than it seems on the surface.
