### ISSUE TITLE
Remove examples from npm publication

### ISSUE THREAD

**Issue by T4cC0re** [PeculiarVentures/PKI.js#76]
Hi,

would it be possible for you to remove the `examples` folder from the _packaged version on npm_?
[see here](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package)

This Folder (especially the PDF Example) blows up the size of dependencies by a substantial amount. (2.7 MiB Examples vs. 1 MiB Source)

Thanks for your consideration!

**Comment by YuryStrozhevsky** [comment]
Sure, I had it in my task list. I would fix it at my Monday.

**Comment by YuryStrozhevsky** [comment]
Closed. But please aware that ES5 version of PKIjs would be replaced by [ES6 version of PKIjs](https://github.com/PeculiarVentures/pkijs-es6) very soon. Thus consider changing your code - ES5 version would not be supported anymore.
