### ISSUE TITLE
Verification against input data for PKCS10

### ISSUE THREAD

**Issue by DenianArthurShades** [PeculiarVentures/PKI.js#77]
Hi,

we keep randomly getting the following error when calling org.pkijs.simpl.PKCS10 in our system: 

> Error: Object's schema was not verified against input data for PKCS10

What we do is this (within a function where csr is a parameter):

> var stringPEM = csr.replace(/(-----(BEGIN|END)( NEW)? CERTIFICATE REQUEST-----|\n)/g, "");
> var asn1 = org.pkijs.fromBER(base64ToBuffer(stringPEM));
> var pkcs10Simpl = new org.pkijs.simpl.PKCS10({schema: asn1.result});

Now, since we get the csr from our UI, we're pretty sure that it's just a problem with the entered certificates, but we can't seem to reproduce this. How would we go about "verifying the object's schema" so we can get more detailed feedback?

**Comment by YuryStrozhevsky** [comment]
In fact PKIjs (and ASN1js) do not provide you any details on this error. So, you need to debug it yourself. There is no way how to get you any details - ASN.1 schema would be verified against predefined schema or not.

**Comment by rmhrisk** [comment]
No update so closing
