### ISSUE TITLE
Warning: WebCrypto is not available

### ISSUE THREAD

**Issue by lexcorp** [PeculiarVentures/PKI.js#82]
Always response Warning: WebCrypto is not available
var crypto = org.pkijs.getCrypto();
      if (console.log) console.log(crypto);
      if (typeof crypto === 'undefined') {
        warn('WebCrypto is not available');
// Don't show any signature information
        this._capability.resolve(emptyResult);
        return;
      }

**Comment by YuryStrozhevsky** [comment]
Yesterday PKI.js "master" branch was changed with V2 code. The V2 code is incompartible with V1 code of  PKI.js. If you do need PKI.js V1 then please specify correct NPM package number during installation of PKI.js

**Comment by lexcorp** [comment]
thank you very much Yury... I'll try...

**Comment by lexcorp** [comment]
Hey yury, I can't find version1 V1 of PKI.js for npm... :(
