### ISSUE TITLE
PKCS#12 incorrect password error

### ISSUE THREAD

**Issue by sokolov-maxim** [PeculiarVentures/PKI.js#84]
Steps to reproduce 

1. Generate any PKCS#12 on [examples page](https://pkijs.org/examples/PKCS12SimpleExample.html) with a password.
1. Try to extract key using OpenSSL command with the same password
    `openssl pkcs12 -in pkijs_pkcs12.p12 -nocerts -out key.pem -nodes`
    the result is an error: `Mac verify error: invalid password?`
1. Try to import into Windows certification store with the same password using certmgr.msc 
    the result is an error: `The password you entered is incorrect`

**Comment by YuryStrozhevsky** [comment]
Check [this link](https://unmitigatedrisk.com/?p=543) for some additional explanations about PKCS#12 and OpenSSL/Windows integration. As a small conclusion: Windows will not understand **any** of PKCS#12 bundles made by PKI.js, OpenSSL will understand only **some** of them.

Also please carefully read note on the example's page you were referring to:
```
Unfortunately current versions of Windows and OpenSSL only support using weak cryptographic primitives in PKCS#12. WebCrypto does not support these weaker mechanisms so we can not fully parse files all files created by them.

With that said OpenSSL does support some stronger options, specifically it allows creation of PKCS#12’s using AES-CBC. You can create such a file with this command:

openssl pkcs12 -export -inkey key.pem -in test.cer -out test.p12 -certpbe AES-256-CBC -keypbe AES-256-CBC
```
