### ISSUE TITLE
Certificate(s) validation against CRLs

### ISSUE THREAD

**Issue by tysonite** [PeculiarVentures/PKI.js#85]
Right now there is `CertificateChainValidationEngine` which may `verify` certificate chain based on trusted certificates and additional certificates (e.g. end user certificate). As well it may accept CRLs previously prepared for certificates validation against them. However, in a general case the user knows CRLs which will be required only after certification path is built. But `verify` function requires them to passed at the very beginning.

So the proposal is to allow one of the following:
1. Add an API to obtain certificate path(s) based on trusted certificates and additional certificates. The provided certificate path(s) might be used to obtain CRLs for passing them into `verify`.
1. Add an optional way to verify certificate(s) against CRL during `verify`.

**Comment by YuryStrozhevsky** [comment]
At the moment we are almost ready to release new, more generic verification engine. I will think about your proposal, it looks reasonable. I will inform you about our decision about it.

**Comment by asnov** [comment]
Hi! Any news? Did you release a new generic verification engine?

**Comment by rmhrisk** [comment]
Yes the new chain engine did ship, I can speak to if/how @YuryStrozhevsky addressed this issue though.

Ryan

**Comment by asnov** [comment]
Hi Ryan, as I saw from the code the issue with CRLs in the new chain engine is addressed in no way. Am I right?

**Comment by rmhrisk** [comment]
@asnov I will talk to @YuryStrozhevsky and get back to you.

**Comment by YuryStrozhevsky** [comment]
@asnov @rmhrisk No, at the moment we do not have a support for building certificate path first and only then apply revocation checking. I will think about it: probably we will add a special flag for certificate engine.

**Comment by YuryStrozhevsky** [comment]
@tysonite @asnov You could use empty "crl" array during first turn of chain building. By passing empty CRL list you will have "all certs are not revoked" condition. After the first turn you will have correctly built certificate chain and could gather all neccessary CRLs and make a second turn with correct "crl" (or "ocsp") array.

**Comment by Omgan** [comment]
@YuryStrozhevsky How verify cert against CRL?

**Comment by YuryStrozhevsky** [comment]
You could check NISTPKITS example for the code template.
