### ISSUE TITLE
Prompt user to select client certificate

### ISSUE THREAD

**Issue by urosberce** [PeculiarVentures/PKI.js#86]
Hi, I have a situation where I want user of my web app (developed in asp.net mvc) to be able at some point to sign a document he creates with his client certificate if he wants to. And when he clicks "sign" I want his browser to prompt him to select the certificate he wants to sign with. I see no way to do it with this lib as it is now (show the prompt window), and I think it would be a great addition.....Does Web Crypto API even enable u to do that?

Thanks!

**Comment by YuryStrozhevsky** [comment]
Web Crypto API has no access to Windows certificate storage or any other OS-specific certificate storage. The only way to use certificate inside Web Crypto is to encode it into BASE-64, then pass to Web Crypto application, the parse using PKI.js for example.

**Comment by urosberce** [comment]
That's a pitty. Thanks for your answer!
