### ISSUE TITLE
CSR Extensions support for PKI.js

### ISSUE THREAD

**Issue by sfuser16** [PeculiarVentures/PKI.js#90]
The current implementation of PKI.js does not list extensions details but only lists subject information.
I've a requirement to also list the extensions(SANs and any other if present in CSR).
Searching a bit through the issues(Thanks to Ryan to route me to this issue), I could find this quite similar issue. Just the difference is that I need the Subject Alt Name information while parsing and not generating CSR.
I went through the Issue #50.

This is the same request that I have.
I'm a little new to JS and was wondering which method should I add the code shared in the Issue #50 to the existing JS file so as to get this working. Displaying the data later shouldn't be an issue later once I could parse the data from CSR.

FYI, I'm developing a CSR parsing feature similar to what we see beneath Parse button on https://pkijs.org/examples/PKCS10_complex_example.html .
I could achieve the Subject, Public Key, Signature Algorithm details as in the link but could not achieve the extensions information(SubjectAltName and others extensions if part of the CSR).
Appreciate a quick assistance here.

**Comment by rmhrisk** [comment]
@sfuser16 I believe you are confused, specifically this:

```
"The current implementation of PKI.js does not list extensions details but only lists subject information."
```

Is incorrect, #50 was written against the older version of PKIjs which is probably why you are confused.

You can see the source to the PKCS#10 support here: https://github.com/PeculiarVentures/PKI.js/blob/master/src/CertificationRequest.js#L34

The extensions will be represented in this array, you can grab them with:
```
var atttributes = pkcs10.attributes;
```
Then you can enumerate through each one:
```
for(let j = 0; j < pkcs10.attributes[i].values.length; j++)
{

}
```

You want to look at each one, looking for the Subject Alternate Name extension, its OID is `2.5.29.17`.

Once you find it you can decode it.

PKIjs is modeled exactly after the respective RFCs, in other words, if in doubt look at the RFC.

**Comment by sfuser16** [comment]
Hi @rmhrisk ,
I might be missing on something here but I'm not referring to older version associated with #50 here.
If you review the attached JS file, it refers to , I've added a few console.log statements to see the values for pkcs10.attributes but it doesn't work. 
I created a CSR with SANs(attached here) and ran it through the html file later checking in Chrome console the output of log statements.
The CertificationRequest instance created correctly identifies all values under typesAndValues array within the subject but if I don't see any entry for 2.5.29.17 in the object instance.

[PKIjs issue.zip](https://github.com/PeculiarVentures/PKI.js/files/817773/PKIjs.issue.zip)

**Comment by rmhrisk** [comment]
@sfuser16 sorry, yes I missed a step.

In your sample, you see the PKCS9 extension attribute: 1.2.840.113549.1.9.14

The RFC for that is: https://tools.ietf.org/html/rfc2985

This extension looks like:

```
   extensionRequest ATTRIBUTE ::= {
           WITH SYNTAX ExtensionRequest
           SINGLE VALUE TRUE
           ID pkcs-9-at-extensionRequest
   }

   ExtensionRequest ::= Extensions
```

ExtensionRequest gets you to the extensions: you can see how to work with them here: https://github.com/PeculiarVentures/PKI.js/blob/5b9c35c154c48b232b45cc2a908c88e2f56a8447/src/Extensions.js

@YuryStrozhevsky may have more to add.

**Comment by YuryStrozhevsky** [comment]
You could check how to work with extensions inside CSR by visiting [this link](https://github.com/PeculiarVentures/PKI.js/blob/master/examples/PKCS10ComplexExample/es6.js#L104).

**Comment by YuryStrozhevsky** [comment]
In was an error with the PKCS#10 extensions in this example. Now it is fixed, thanks. I will also update "live example" on pkijs.org soon.

**Comment by sfuser16** [comment]
Hi @YuryStrozhevsky , Thanks for the info. I'm not sure if I'm not able to get this correctly but I reviewed the commit and accordingly to map the change in my file(bundle.js in attached zip file) changed line #15710 modifying from "extensionsArray" to "extensions" and re-ran the scenario in html. But couldn't see the extension information in console logs. I thought that extnID in the js file is 2.5.29.14 and the CSR I added has SubjectAltName OID as 2.5.29.17 . So, I changed that too by modifying extnID: "2.5.29.14" to extnID: "2.5.29.17"but still couldn't parse the extension info in the object structure created. Am I missing something which you could help me with?

**Comment by YuryStrozhevsky** [comment]
In the standard PKI.js example we do not have a routine for parsing PKCS#10 extension. You could parse PKCS#10 extension using additional code:
```javascript
if(pkcs10.attributes[i].type === "1.2.840.113549.1.9.14")
{
	const extensions = new Extensions({ schema: pkcs10.attributes[i].values[0] });
}
```
After this inside "extensions" object you will have "parsedValue" property (in case if extesion would be recognized by PKI.js). For your specific test case inside "parsedValue" you will have "AltName" object with 3 "altNames".

**Comment by sfuser16** [comment]
That worked!! Thanks a ton @YuryStrozhevsky and @rmhrisk for your persistent and quick support for getting this fixed.

**Comment by sfuser16** [comment]
@YuryStrozhevsky  , Just curious for this one last question. How about custom extensions as you mentioned above "_(in case if extension would be recognized by PKI.js)_" . I could see the extnID field in "extensions" object for custom extensions. But I don't think we could capture the extension value in this case with the above approach. Correct me if I'm wrong.

**Comment by YuryStrozhevsky** [comment]
First of all [here](https://github.com/PeculiarVentures/PKI.js/blob/master/src/Extension.js#L154) you could find how the "extension recognition" works internally. There you could find a list of extensions which could be recognized by PKI.js automatically. 

Then I think I need to explain how PKI.js works in a "bigger picture". All PKI-related data is a ASN.1 structures. And in order to handle work with all these ASN.1 data we are using [ASN1.js](https://github.com/PeculiarVentures/ASN1.js). All these objects like "Extensions", "AltName" etc are only a "simplifiers" for ASN.1 data, there are made "on top" of ASN.1. So, for a non-standard extension you would need to deal with ASN.1 data by yourself. In case of extension type you would need to parse "extnValue" value like it done [in this line of code](https://github.com/PeculiarVentures/PKI.js/blob/master/src/Extension.js#L150) and then work with ASN1.js structures.

**Comment by sfuser16** [comment]
Got it, thanks for the nice and detailed explanation.

**Comment by mourkeita** [comment]
Hello,

Im using pkijs but i have some issues when i try to add SAN to my CSR.

Here is a snippet that i'm using to generate CSR attributes: and it does not work
			pkcs10.attributes.push(new Attribute({
				type: "1.2.840.113549.1.9.14", // pkcs-9-at-extensionRequest
				values: [new Extensions({
					extensions: [new Extension({
						extnID: "2.5.29.17",
						critical: false,
						extnValue: new Utf8String({value : parseSAN()}).toBER(false)
					})]
				}).toSchema()]
			}));

can you help me please ? 

Thanks :)

**Comment by rmhrisk** [comment]
Please file a new bug this is not related to this closed issue
