### ISSUE TITLE
Failed to load resource: net::ERR_FILE_NOT_FOUND (bundle.js)

### ISSUE THREAD

**Issue by hanselacacia** [PeculiarVentures/PKI.js#95]
Hi. My question can be a bit silly. I downloaded the examples to run them in my environment. But when executing the html of the examples, the browser gives the error: "Failed to load resource: net :: ERR_FILE_NOT_FOUND". This is because the bundle.js file does not exist in the folder.

I can see that in the examples there is no such file. How do I get it or can I run the example?

Thank you. 

Apologies for my english. I use traductor.

**Comment by rmhrisk** [comment]
You need to build the samples, I don't have a computer handy but if you look at package.json you will see commands to build individual samples and one to build all samples.

**Comment by hanselacacia** [comment]
Excellent. Thank you so much for the help Ryan.
