### ISSUE TITLE
CertificationRequest wrong OID for signature

### ISSUE THREAD

**Issue by microshine** [PeculiarVentures/PKI.js#97]
I'm using `RSA-SHA256` key for request signing

```javascript
pkcs10.sign(privateKey)
    .then(() => {
        // ...
    })
```

But I've got `1.2.840.113549.1.1.5` - sha1RsaEncryption for signature algorithm.

There is optional parrameter for digest alg in `sign` method. And it use `SHA-1` as default. RSA keys have hash parameter in key algorithm. It would be better to use this param. Current [code](https://github.com/PeculiarVentures/PKI.js/blob/master/src/CertificationRequest.js#L334)

```javascript
defParams.algorithm.hash.name = privateKey.algorithm.hash ? privateKey.algorithm.hash.name : hashAlgorithm;
```

**Comment by YuryStrozhevsky** [comment]
@microshine If you will use this code all would be fine
```javascript
pkcs10.sign(privateKey, "SHA-256")
```
