### ISSUE TITLE
Hash algorithm selector in CSR create example doesn't work

### ISSUE THREAD

**Issue by microshine** [PeculiarVentures/PKI.js#98]
I'm trying to create request with sha256RsaEncription but I have sha1RsaEncryption

![image](https://cloud.githubusercontent.com/assets/7333669/24926111/2733faa4-1f03-11e7-8267-1f0875c3cc42.png)

**Comment by YuryStrozhevsky** [comment]
@microshine This is a simple problem in example's script: in function handling hash algorithm change the UI element had wrong name. Fixed, thanks.
